### ISSUE TITLE
[Feature] Make torch an  optionall dependancy

### ISSUE THREAD

**Issue by eddiebergman** [automl/SMAC3#1004]
I'm fairly certain it''s not a strict requirement of SMAC, at least with most of it's components

**Comment by dengdifan** [comment]
Is that a mandatory requirement? If I remember correctly, that should already be an optional dependeancy

**Comment by dengdifan** [comment]
And actually, we can drop the torch requirement for SMAC version >=2.0. It is only required by SMAC 1.4.x
