### ISSUE TITLE
Issue in _get_best_configs of SuccessiveHalving

### ISSUE THREAD

**Issue by sudoRicheek** [automl/SMAC3#1019]
https://github.com/automl/SMAC3/blob/d5d54562333c6845c06227de15faec30ef553d23/smac/intensifier/successive_halving.py#L551

Here `all_keys` is defined to be of the same length as `configs`. But here:

https://github.com/automl/SMAC3/blob/d5d54562333c6845c06227de15faec30ef553d23/smac/intensifier/successive_halving.py#L556

Changes are made to the `configs`. And here:

https://github.com/automl/SMAC3/blob/d5d54562333c6845c06227de15faec30ef553d23/smac/intensifier/successive_halving.py#L561

`configs` and `all_keys` are passed to the `sort_by_crowding_distance()` function, which are required to be of the same length. Am I missing something?

I replaced 

https://github.com/automl/SMAC3/blob/d5d54562333c6845c06227de15faec30ef553d23/smac/intensifier/successive_halving.py#L561 

with

```
all_keys = [from_keys for _ in selected_configs]
selected_configs = sort_by_crowding_distance(rh, selected_configs, all_keys)[:n_configs] 
```

and it works fine

**Comment by helegraf** [comment]
You are correct, thanks for pointing this out!
