### ISSUE TITLE
A problem about the sobol.rng_seed

### ISSUE THREAD

**Issue by Car-pe** [automl/SMAC3#1036]
#### Description

In sobol_design.py
sobol_gen = Sobol(d=dim, scramble=True, seed=self._rng.randint(low=0, high=10000000))
the sobol_gen.rng_seed is always 8325804, and when I replaced "seed=self._rng.randint(low=0, high=10000000)" with "seed=numpy.random.randint(low=0, high=10000000)", this problem was fixed. I'm wondering is there something wrong?
Thank you !!

**Comment by alexandertornede** [comment]
This is intended behavior as the internal rng object is initialized with the SMAC seed. Your "fix" changed the behavior since the random generator is not initialized with a seed and hence, generates different numbers every run.
