### ISSUE TITLE
[BUG] [QUESTION] How to setup AlgorithmConfigurationFacade for multiple algorithms and hyperparameters?

### ISSUE THREAD

**Issue by simonprovost** [automl/SMAC3#1041]
Dear **Authors**, we hope you are doing well.

#### Description
We are exploring the use of SMAC for the optimisation of multiple algorithms and their hyperparameters. After successfully experimenting with the HyperparameterOptimizationFacade for a single algorithm, we are now looking to extend this to multiple algorithms.

We believe that we should use the AlgorithmConfigurationFacade for this purpose as suggested in the SMAC3 paper (SMAC4AC now AlgorithmConfigurationFacade). However, we found that the documentation for this feature is sparse, leaving us uncertain about the correct approach. We kindly request some guidance on using the AlgorithmConfigurationFacade correctly. To give back to the community, and you may be busy on a plethora of sides, we could also plan to provide examples for enhancing the documentation in a pull request over the summer.

One specific question we have is regarding the setup of the configspace for the AlgorithmConfigurationFacade. We have searched through the documentation and test cases but could not find relevant examples. Any exemples around?

As a final step in our experimentations, we plan not to only optimise algorithms and hyperparmeters, but actual custom Scikit-learn pipeline candidate for a specific use case. We would like to confirm whether our intended use of AlgorithmConfigurationFacade aligns with this goal or walk towards the right direction? If so, how does the configuration of the candidates can be made based on a given search space (probably something with the condition operations ConfigSpace allows users to do?) ?

#### Steps/Code to Reproduce
We have not encountered a problem with any specific code; this is a general usage question.

#### Expected Results
We are hoping for guidance on how to use the AlgorithmConfigurationFacade for tuning multiple algorithms and their hyperparameters. Specifically, we would appreciate an example or a detailed explanation of how to correctly set up the configspace for this purpose.

#### Actual Results
Currently, we are unable to proceed due to the limited understanding and lack of examples in the documentation.

#### Versions
We are using SMAC with Poetry on a MacBook Pro m2 (2022) running on OSX Ventura stable.

We thank you very much in advance for your time!
Cheers

**Comment by eddiebergman** [comment]
Hiyo, I think this may have been my fault with an update to `ConfigSpace`. The `Configuration` object was acting as a pseudo dictionary where technically you could access values which are disabled. I fixed this in #1043, not sure when it gets merged, likely next Tuesday. Can you try using that specific version if possible and see if it fixes your problem?

**Comment by simonprovost** [comment]
Heya @eddiebergman ! Long time no see. You may not recall, but I do, and I am clearly excited to be helping the real game, it's exciting!

In the meantime, I greatly appreciate your prompt response. I was scouring the web with every neuron in my brain-net in search of examples where I may have erred. I do not yet know enough about SMAC3's content, but your pull request worked beautifully. However, I only made a few tweaks to slightly improve the entire procedure. As a result, I supplied a brief review directly on the pull request, I hope I was permitted to do so; I merely wished to suggest improvements for such a great initiative! :) 

Cheers and closing the issue thanks to your help once more
