### ISSUE TITLE
Error with Importing from ConfigSpace

### ISSUE THREAD

**Issue by TianningGao** [automl/SMAC3#1046]
#### Description
Python cannot import the hyperparameter type class from ConfigSpace. I wanted to run the SVM code from basic examples but got some import errors. 
There was no error if just import the whole package by "import smac; import ConfigSpace".

#### Steps/Code to Reproduce
import numpy as np
import os
from typing import List, Union, Callable
from opt_base import OptimizerBase
from ConfigSpace import Configuration, ConfigurationSpace
from ConfigSpace import Categorical, Float, Integer
from smac import DefaultInitialDesign, HyperparameterOptimizationFacade, Scenario
exit()

#### Expected Results
No error.

#### Actual Results
Reported by python:

`Traceback (most recent call last):`
`File "opt_smac.py", line 6, in <module>`
`from ConfigSpace import Categorical, Float, Integer`
`ImportError: cannot import name 'Categorical' from 'ConfigSpace' (/home/idwwwoqq808/.local/lib/python3.8/site-packages/ConfigSpace/__init__.py) `

#### Versions
SMAC3 version: 1.1.1
Python version: 3.8.10
OS: WSL-Ubuntu 20.04

**Comment by eddiebergman** [comment]
Hi @TianningGao,

What version of `ConfigSpace` are you using?
`pip list | grep ConfigSpace`

Are you able to run `python -c "from ConfigSpace import Categorical"` from the same environment?

A fix you could try is `pip install -U ConfigSpace`

**Comment by TianningGao** [comment]
The ConfigSpace version is 0.4.20. Python reports the same error when I run `from ConfigSpace import Categorical`. I also tried import Float and Integer but python reported same error:
`Python 3.8.10 (default, Jun 22 2022, 20:18:18)`
`[GCC 9.4.0] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> from ConfigSpace import Categorical`
`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`ImportError: cannot import name 'Categorical' from 'ConfigSpace' (/home/idwwwoqq808/.local/lib/python3.8/site-packages/ConfigSpace/__init__.py)`
`>>> from ConfigSpace import Float`
`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`ImportError: cannot import name 'Float' from 'ConfigSpace' (/home/idwwwoqq808/.local/lib/python3.8/site-packages/ConfigSpace/__init__.py)`
`>>> from ConfigSpace import Integer`
`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`ImportError: cannot import name 'Integer' from 'ConfigSpace' (/home/idwwwoqq808/.local/lib/python3.8/site-packages/ConfigSpace/__init__.py)`
`>>>`

**Comment by TianningGao** [comment]
I switched to Python 3.10.6 and this problem disappeared.
The SMAC3 version is 2.0.1 and ConfigSpace version is 0.7.1

**Comment by eddiebergman** [comment]
Glad to hear it worked, closing but feel free to re-open with a comment if the same issue occurs
