### ISSUE TITLE
Racing: Configs worse than existing incumbent are not rejected `bug`

### ISSUE THREAD

**Issue by PhilippBordne** [automl/SMAC3#1068]
#### Description

I wanted to use the tell-interface of the HPOFacade (which uses racing for intensification, the related class being `Intensifier`) to warmstart the optimizer with data from previous runs which were all collected on the same seed, no instances were used.

#### Steps/Code to Reproduce

https://gist.github.com/PhilippBordne/722c336dd0981859bfade198171f9c29

#### Expected Results
All configurations worse than the incumbent should be in the `_rejected_config_ids` list after using the tell interface for warmstarting. They should still be in it after `__post_init__` of `AbstractIntensifier` was run when starting the actual optimization loop. `__post_init__` will call `update_incumbents(config)` on the runhistory again and thus also update the `_rejected_config_ids` list.

#### Actual Results
The configs worse than the incumbent are in the `_rejected_config_ids` list after using the tell interface for warmstarting if they were "told" in an order that improves the cost with every new config. But they are not in the list after running `__post_init__` (They are all removed during the `update_incumbents` cycle on existing configs in `RunHistory` at the end of `__post_init__`). This can lead the subsequent optimization run to fail because the configs which are erroneously not in the `_rejected_config_ids` list will fill up the queue and make the intensifier use up all its retries on them. 
For details see the linked code to reproduce.

#### Proposed fix
The issue is caused by the current configs being _removed_ from `_rejected_config_ids` if the incumbent doesn't change during `update_incumbents(config)`, which is also the case if newly evaluated configs are worse than the existing incumbent. This can be fixed by inserting a simple check if the config is among the incumbents after `update_incumbents`.
A PR implementing this is incoming.

#### Versions

2.0.2

**Comment by eddiebergman** [comment]
@PhilippBordne
