### ISSUE TITLE
'LocalAndSortedRandomSearch' object has no attribute 'update'

### ISSUE THREAD

**Issue by Husam94** [automl/SMAC3#1077]
#### Description

Set number of challengers and local search iterations for HPO 

#### Steps/Code to Reproduce

aqua = HyperparameterOptimizationFacade.get_acquisition_maximizer(scenario, 
                                                                      challengers=challengers, 
                                                                      local_search_iterations=local_search_iterations)

...

smac = HyperparameterOptimizationFacade(scenario,
                                            smaco, 
                                            initial_design = indes,
                                            acquisition_function = aqua,
                                            intensifier = intense,
                                            random_design = randi, 
                                            overwrite = overwrite)

#### Actual Results

File ~/miniconda3/envs/new/lib/python3.11/site-packages/smac/facade/abstract_facade.py:319, in AbstractFacade.optimize(self, data_to_scatter)
    316     raise ValueError("data_to_scatter must be None or dict with some elements, but got an empty dict.")
    318 try:
--> 319     incumbents = self._optimizer.optimize(data_to_scatter=data_to_scatter)
    320 finally:
    321     self._optimizer.save()

File ~/miniconda3/envs/new/lib/python3.11/site-packages/smac/main/smbo.py:300, in SMBO.optimize(self, data_to_scatter)
    296     callback.on_iteration_start(self)
    298 try:
    299     # Sample next trial from the intensification
--> 300     trial_info = self.ask()
    302     # We submit the trial to the runner
    303     # In multi-worker mode, SMAC waits till a new worker is available here
    304     self._runner.submit_trial(trial_info=trial_info, **dask_data_to_scatter)

File ~/miniconda3/envs/new/lib/python3.11/site-packages/smac/main/smbo.py:153, in SMBO.ask(self)
    150     callback.on_ask_start(self)
    152 # Now we use our generator to get the next trial info
--> 153 trial_info = next(self._trial_generator)
    155 # Track the fact that the trial was returned
    156 # This is really important because otherwise the intensifier would most likly sample the same trial again
    157 self._runhistory.add_running_trial(trial_info)

File ~/miniconda3/envs/new/lib/python3.11/site-packages/smac/intensifier/intensifier.py:226, in Intensifier.__iter__(self)
    223 # For each intensification of the incumbent, we also want to intensify the next configuration
    224 # We simply add it to the queue and intensify it in the next iteration
    225 try:
--> 226     config = next(self.config_generator)
    227     config_hash = get_config_hash(config)
    228     self._queue.append((config, 1))

File ~/miniconda3/envs/new/lib/python3.11/site-packages/smac/main/config_selector.py:201, in ConfigSelector.__iter__(self)
    197             raise ValueError("Runhistory is empty and the cost value of the incumbent is unknown.")
    199         x_best_array, best_observation = self._get_x_best(X_configurations)
--> 201     self._acquisition_function.update(
    202         model=self._model,
    203         eta=best_observation,
    204         incumbent_array=x_best_array,
    205         num_data=len(self._get_evaluated_configs()),
    206         X=X_configurations,
    207     )
    209 # We want to cache how many entries we used because if we have the same number of entries
    210 # we don't need to train the next time
    211 self._previous_entries = Y.shape[0]

AttributeError: 'LocalAndSortedRandomSearch' object has no attribute 'update'

#### Versions

smac 2.0.2

**Comment by alexandertornede** [comment]
Hi, 

thanks for the bug report, we will look into it!

**Comment by alexandertornede** [comment]
@dengdifan Can you please have a look into it?

**Comment by dengdifan** [comment]
Hello, 

thanks for the information, you need to assign `aqua` to `acquisition_maximizer` instead of `acquisition_function`. Please let me know if it helps.
