### ISSUE TITLE
How to add trials/walltime after a optimize call ends

### ISSUE THREAD

**Issue by oddg** [automl/SMAC3#1103]
#### Description

I ran `myfacade.optimize` and it completed successfully. Now I want to re-optimize but with a larger budget on `n_trials` and `walltime_limit` while reusing the data collected on the first scenario.
How can I do that?

#### What I tried.

The documentation explains how to use [prior over the optimum](https://automl.github.io/SMAC3/v2.0.2/examples/1_basics/6_priors.html) but it is not clear how to find that prior from the previous successful optimization.

I tried to reuse the `intensifier` of the first facade without success.

**Comment by dengdifan** [comment]
Hi,

you could create a new facade with the enlarged `n_trials` and `walltime_limit`, then use the [tell]( https://github.com/automl/SMAC3/blob/main/examples/1_basics/3_ask_and_tell.py ) function to tell the optimizer the `TrialValue` and `TrialInfo` from your previous runs (which can be read from the `runhistory` generated by your first SMAC run).
Please let me know if that helps

**Comment by oddg** [comment]
Thanks @dengdifan  for the reply!

This is what I was looking for. I ended doing something like below
```
for (trial_key, trial_value) in complete_facade.runhistory.items():
    trial_info = TrialInfo(
        config=complete_facade.runhistory.get_config(trial_key.config_id),
        instance=trial_key.instance,
        seed=trial_key.seed,
        budget=trial_key.budget
    )
    new_facade.tell(trial_info, trial_value)
```
