### ISSUE TITLE
random forest function problem

### ISSUE THREAD

**Issue by quchongqi** [automl/SMAC3#1105]
Hello,  I have a question about random forest  function.
     In the readme, it is stated that the random forest is implemented using C++, but there are no .cpp files, .i files, or .os files in the source code. Moreover, in this source code for smac.model.random_forest.random_forest, it is observed that the random forest is written in python. So I don't know how to use C++ to speed up the random forest function. Could you please tell me? Thank you very much.

**Comment by dengdifan** [comment]
Hi,
 You can find the codes for the random forest from this repo: https://github.com/automl/random_forest_run
Then, the C++ codes are packed with `swig and  added as an dependencies to SMAC
