### ISSUE TITLE
Install numpy and scipy via `setup_requires`

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#112]
Scipy can now be installed from within setup.py (see [changelog](https://github.com/scipy/scipy/releases)). We should try to reduce duplication of requirements specification and update the installation procedure accordingly.

**Comment by KEggensperger** [comment]
@mfeurer: Is this also fixed with #114

**Comment by mfeurer** [comment]
There are still issues with scikit-learn and pyrfr, which both need numpy to be installed. To the best of my knowledge, this only works with `pip install -r` so far. Since #114 deduplicates the requirements, I'm closing this now.
