### ISSUE TITLE
Feature request: Improve cross platform compatability

### ISSUE THREAD

**Issue by ErikVogelLUH** [automl/SMAC3#1138]
I do not understand why this repo uses its own implementation of random forests when there is a perfectly fine implementation in sklearn. If I understand it correctly, the only reason this library does not work on other platforms is the implementation of the random forests. Furthermore, using a house-made implementation increases the probability of bugs and the complexity of the code.

**Comment by benjamc** [comment]
Hi ErikVogelLUH,
the custom random forest implementation has two reasons: (i) enable instances for algorithm configuration and some other algorithmic details which are non-standard (ii) speed as there was no fast python implementation. The latter now has changed and we actually are working on transitioning to a popular RF python implementation. 
Related to #1116 .
