### ISSUE TITLE
Support NumPy > 2.0.0

### ISSUE THREAD

**Issue by Turakar** [automl/SMAC3#1144]
The current version of SMAC3 does not support NumPy >= 2.0. It would be nice to add support. Is this planned?

See also: https://numpy.org/doc/stable/numpy_2_0_migration_guide.html

**Comment by benjamc** [comment]
Hi, yes this will be in the development branch soon and will go into the next release.

**Comment by Turakar** [comment]
Thanks!

**Comment by benjamc** [comment]
It's in the development branch, will close this issue now. If you have any issues, please let us know.
