### ISSUE TITLE
facade refuse to tuning laters instances when tuning them one-by-one in a loop

### ISSUE THREAD

**Issue by sam-my-2023** [automl/SMAC3#1145]
question/feature request/bug

#### Description

When tuning instances one by one in a loop, the facade refuse to tuning laters one as it will use the first tuning results and say the max trial number is reached.
#### Expected Results

every tuning per instance should be independent

#### Actual Results

[INFO][abstract_initial_design.py:95] Reducing the number of initial configurations from 220 to 1 (max_ratio == 0.25).
[INFO][abstract_initial_design.py:147] Using 1 initial design configurations and 0 additional configurations.
[INFO][smbo.py:498] Continuing from previous run.
[INFO][smbo.py:271] Optimization process was already finished. Returning incumbent...

**Comment by sam-my-2023** [comment]
never mind it's solved by adding separate folder to output_dir to scenario per instance.

**Comment by benjamc** [comment]
Perfect :) will close the issue, feel free to reopen if you have further issues
