### ISSUE TITLE
FAIL: test_memout (test_tae.test_exec_func.TestExecuteFunc) on OSX

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#115]
The unit test [test_memout](https://github.com/automl/SMAC3/blob/development/test/test_tae/test_exec_func.py#L62) is failing on OSX. @sfalkner can you please confirm that the pynisher works on OSX?

**Comment by sfalkner** [comment]
In principle, it should, but I have no way of testing it :(

**Comment by mfeurer** [comment]
Hm, this seems to be a known issue: [here](http://stackoverflow.com/questions/30269238/limit-memory-usage) and [here](http://stackoverflow.com/questions/3274385/how-to-limit-memory-of-a-os-x-program-ulimit-v-neither-m-are-working#comment4987496_3276945). All other unit tests work fine on OSX. Maybe SMAC will only have limited capabilities on OSX (not being able to limit the memory of the target algorithm)? Could a different limit (physical memory limit) alleviate the problem?

**Comment by mfeurer** [comment]
This issue is open since more than three years, and we didn't put any effort in supporting OSX in the meantime -> closing this for now.

**Comment by eddiebergman** [comment]
Just an update that this is recognized and made explicit in pynisher 1.0.0
* https://github.com/automl/pynisher#details
