### ISSUE TITLE
[Docs] intensifier type mismatch between docs and code of AlgorithmConfigurationFacade

### ISSUE THREAD

**Issue by bbudescu** [automl/SMAC3#1162]
In the table at the beginning of the "Facade" [section](https://automl.github.io/SMAC3/main/3_getting_started.html#facade) of the "Getting Started" Guide, it is stated that the Algorithm Configuration facade is using Hyperband by default. However, when actually running the code, one can see that a "Default" `Intensifier` is actually [returned](https://github.com/automl/SMAC3/blob/9d194754a5fed3ec48be06987cfc24ee99b76af5/smac/facade/algorithm_configuration_facade.py#L107) by `AlgorithmConfigurationFacade.get_intensifier()`

**Comment by dengdifan** [comment]
Hi,
Thanks for the information. The default `intensifier` for the AC facade should indeed be `default`. We will fix that in the next release!

**Comment by bbudescu** [comment]
Hi,
Thanks for looking into the problem. Also, I can see that not long before I posted this issue, someone else also mentioned it in theirs (https://github.com/automl/SMAC3/issues/1160). Sorry for the repost. It was just a coincidence. I actually skimmed through that one, but somehow missed the reference to this issue.

**Comment by bbudescu** [comment]
I see you added #1165, which is exactly about this, so, from my point of view, this issue has become redundant. Should I just close it?
