### ISSUE TITLE
[Documentation] AlgorithmConfigurationFacade uses Intensifier not Hyperband

### ISSUE THREAD

**Issue by timruhkopf** [automl/SMAC3#1165]
#### Description
In issue #1160 there is correct note, that for the AlgorithmConfigurationFacade, we use the Intensifier class (compare: [get_intensifier](https://github.com/automl/SMAC3/blob/937eb2cae720656d741d5ab26a68d3ade348d046/smac/facade/algorithm_configuration_facade.py#L102) not the hyperband, which is wrongly documented. 

> Note also that the table in https://automl.github.io/SMAC3/main/3_getting_started.html says that the AlgorithmConfigurationFacade uses the Hyperband Intensifier, which, however I don't think is true.

**Comment by benjamc** [comment]
Fixed in #1155
