### ISSUE TITLE
Why do we round the cutoff?

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#117]
Why do we use math.ceil on the cutoff and cast it to `int` in `execute_ta_run`?

```
        if cutoff is not None:
            cutoff = int(math.ceil(cutoff))
```

**Comment by mfeurer** [comment]
We need to cast it to int because otherwise the pynisher will complain. We need to make sure it's `> 1`, because a cutoff of `0` means no time limit.

**Comment by mlindauer** [comment]
but we could do this only in the code where we use the Pynisher, right?

**Comment by mfeurer** [comment]
That's correct. Are there cases where you want to use cutoffs less than a second?

**Comment by mlindauer** [comment]
In fact, the runsolver (which we use in our AClib benchmark) also requires a cutoff >= 1.0. However, I believe that the target algorithm wrapper (or whatever limits the runtime cutoff) should be responsible for handling the running time cutoff and not SMAC already (except if we optimize an python function and use the pynisher).

**Comment by mfeurer** [comment]
Good point. We could move this piece of code to the respective TAE. Would that only be the python function TAE called via the pynisher?
