### ISSUE TITLE
Configuration should not be evaluated based on warmstarted runhistory with foreign instances

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#118]
In the course of fixing this problem (see title), I would also like to work on the runhistory code to make it more efficient. To this end, a question: do we really want to support other aggregation function than average? (<- @mfeurer )
If not, we could substantially speed up the `update_cost()` method in `RunHistory`.

**Comment by mfeurer** [comment]
My intention was to update the cost only based on a subset of instances. One could supply a function like `instance_subset_average` to the code which takes care of this. Of course, if there are easier solutions to achieve this we should go for them.

**Comment by mlindauer** [comment]
fixed in #121
