### ISSUE TITLE
SMAC crashes if first run of solution_quality scenario is a timeout

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#125]
If the first run of SMAC3 is a timeout and we optimize for solution quality (cost),
runhistory2epm does not provide any data point for the RF 
and the RF will crash with an empty X matrix.

```
  File "/work/ws/nemo/fr_tl1023-aclib-0/aclib2/configurators/smac3/smac/epm/rf_with_instances.py", line 114, in train
    data = pyrfr.regression.numpy_data_container(self.X, y, self.types)
  File "pyrfr/regression_source.pyx", line 125, in pyrfr.regression.numpy_data_container.__cinit__ (pyrfr/regression.cpp:3575)
IndexError: Out of bounds on buffer access (axis 0)
```

As specified in smac_facade, we use only "successful" for soluation quality scenarios:

```
            elif scenario.run_obj == 'quality':
                runhistory2epm = RunHistory2EPM4Cost\
                    (scenario=scenario, num_params=num_params,
                     success_states=[StatusType.SUCCESS, ],
                     impute_censored_data=False, impute_state=None)
```

I think that a neat solution would be if SMAC could also handle "unsuccessful" runs (TIMEOUT, CRASH) in solution quality scenarios.
For example, we could try to force the user to provide an imputation value of unsuccessful runs in solution quality scenarios.

btw: the issue occurs on the svm_mnist scenario in AClib2.

**Comment by mlindauer** [comment]
@mfeurer told me that we should look in the paper "Bayesian Optimization with Unknown Constraints" to solve this issue in a clean way.
However, I would prefer to have an interim solution in the meantime.

**Comment by mfeurer** [comment]
Sorry, my answer was incorrect. If the first run is a timeout, SMAC should do random search until it finds a feasible solution (only then it makes sense to model something). I will go ahead and implement this.
