### ISSUE TITLE
Add method get_target_algorithm_runner to SMAC class

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#128]
The example of the random forest depicts why this is necessary:
```
def_value = smac.solver.intensifier.tae_runner.run(cs.get_default_configuration(), 1)[1]
```
The user should not know about the solver and intensifier class...

**Comment by shukon** [comment]
Will it suffice to simply return `smac.solver.intensifier.tae_runner` (branch issue/#128, 1baacb3) or is the `tae_runner` supposed to be a class-member?

**Comment by mlindauer** [comment]
yes, it suffice.
