### ISSUE TITLE
divide by zero encountered

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#130]
This is an annoying warning.
It happens in the trunc_norm in the censored data imputation.
The problem is that the bounds (a,b) have the same CDF value (d = CDF(b) - CDF(a)).
Since we compute `a` and `b` by `(censored_y - y_mean) / y_stdev`,
the warning is typically raised if `y_stdev` is very small such that `a` and `b` get very large.
I don't know whether it is a crucial warning, but we should fix it somehow; at least to not confuse our users.

@KEggensperger Do you have any idea how to fix this?

```
site-packages/scipy/stats/_continuous_distns.py:4828: RuntimeWarning: divide by zero encountered in true_divide
  mu = (pA - pB) / d   # correction sign
site-packages/scipy/stats/_continuous_distns.py:4829: RuntimeWarning: divide by zero encountered in true_divide
  mu2 = 1 + (a*pA - b*pB) / d - mu*mu
site-packages/scipy/stats/_continuous_distns.py:4829: RuntimeWarning: invalid value encountered in subtract
  mu2 = 1 + (a*pA - b*pB) / d - mu*mu
```

**Comment by mlindauer** [comment]
my idea: if the standard deviation is very small, only the mean really matters.
so, we could impute max(mean,lower_bound).
What do you think?

**Comment by mfeurer** [comment]
Can this be closed?

**Comment by mlindauer** [comment]
yes
