### ISSUE TITLE
Crash if first run is memory out

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#131]
SMAC crashes if the first run of the TA is memory out.
Right now, the first run has to either a successful run or a "real" timeout (time > cutoff). 
Even if the memout is encoded as a timeout, SMAC will crash because `runhistory2epm` will only pass "real timeouts" to the EPM.

**Comment by mfeurer** [comment]
This is more or less a duplicate of #125, would be fixed by my proposed solution.
