### ISSUE TITLE
Never return a configuration with CRASHED runs

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#14]
Originally reported by: **Marius Lindauer (Bitbucket: [mlindauer](https://bitbucket.org/mlindauer), GitHub: [mlindauer](https://github.com/mlindauer))**

---

We should ensure that SMAC3 will never return a configuration with CRASHED runs. If runs crashed, the configuration has some unknown issues that should be avoided.

right now, CRASHED will be counted in the same way as a TIMEOUT. but in fact, a CRASHED run should be much more worse than a TIMEOUT.

---
- Bitbucket: https://bitbucket.org/aadfreiburg/smac3/issue/14

**Comment by mlindauer** [comment]
This will be resolved with PR #229 by adding a new argument to set a default cost value

**Comment by mlindauer** [comment]
This issue is more or less solved by adding a new scenario option to specifiy the quality of crashed runs. So, the user can decide how important CRASHED runs are. 

For running time scenarios, we still use PAR_factor * cutoff.
