### ISSUE TITLE
Aborted runs can spam runhistory

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#147]
SMAC stores the output of each run in the runhistory. If the configuration budget is exhausted and SMAC is in the intensification method, it tries to start new runs, but only to make the target algorithm executor figure out that no time is left. Each of these trials is then logged in the runhistory. In case there are > 100 challengers left for intensify to evaluate, these might all be tried before the intensification time budget is spent. This results in lots of aborted runs in the runhistory, which makes it unnecessarily hard to analyze it.

**Comment by mlindauer** [comment]
Why are these runs in the runhistory at all?
`ExecuteTARun.start()` returns the result directly and does not add it to the runhistory if the budget was exhausted.

**Comment by mfeurer** [comment]
Nevermind, this is special to my implementation of the target algorithm executor...
