### ISSUE TITLE
invalid syntax? from Auto-sklearn to SMAC

### ISSUE THREAD

**Issue by Aaaaaaare** [automl/SMAC3#148]
Hi! 

Sorry, I'm quite new with Python. Does this SMAC works on python 2.7? I came here from AutoSklearn: I installed all dependencies and when i try to run the example that is on the webpage (the simple code that im copying at the end of this paragraph), I got an error: 

 from smac.facade.smac_facade import SMAC
  File "/usr/local/lib/python2.7/dist-packages/smac/facade/smac_facade.py", line 43
    scenario: Scenario,
            ^
SyntaxError: invalid syntax

(The error comes from some nested imports, but it occurs at that file).

The code is the following:

import autosklearn.classification
import sklearn.cross_validation
import sklearn.datasets
import sklearn.metrics
digits = sklearn.datasets.load_digits()
X = digits.data
y = digits.target
X_train, X_test, y_train, y_test = \
    sklearn.cross_validation.train_test_split(X, y, random_state=1)
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(X_train, y_train)
y_hat = automl.predict(X_test)
print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))

Sorry again for asking such a simple question, but im not sure how to fix it

**Comment by mlindauer** [comment]
Hi,

SMAC is only compatible with Python >3.4, since we use type hints in the code, which are not compatible with Python 2.x. 
We recommend to install a recent anaconda with Python >3.5 to run SMAC and auto-sklearn.

Cheers,
Marius

PS: Sorry, the entire team is on vacation right now and we can only answer sporadically.

**Comment by Aaaaaaare** [comment]
Thank you very much! I follow your advice and now I have both running!
