### ISSUE TITLE
Add individual exceptions

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#155]
The TAE should throw exceptions if

1. The configuration budget is empty (e.g., `BudgetExhaustedException`)
    * SMAC should gracefully exit
1. The algorithm returned ABORT (or the first run was a CRASHED) (e.g., `TAEAbortException`)
    * SMAC should terminate asap, but still return current incumbent.

These exception have to be handled in the code accordingly.

**Comment by shukon** [comment]
So when a BudgetExhaustedException is raised, SMAC should not return any incumbent? I thought that just indicates that the time is up?

**Comment by mlindauer** [comment]
Sorry, this was a misunderstanding.
The `SMAC` object should **always** return an incumbent.
