### ISSUE TITLE
Use consistent naming for loggers

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#159]
Currently, loggers have names like:

* localsearch
* intensifier
* SMBO

This makes it hard to disable them in applications building on SMAC. Having names like

* smac.smbo.Localsearch
* smac.intensify.Intensifier

etc. would make it easier to set a log level for the whole SMAC package and/or set the log level for a submodule of SMAC.

**Comment by shukon** [comment]
Changed names (I hope I got them all) in branch issue/#159. Not sure how/whether to add functionality for setting log-levels.
