### ISSUE TITLE
Introduce option to not abort on first crash

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#160]
Aborting on the first run will make it hard to run random search with the ROAR algorithm because randomly drawing a configuration which's hyperparameter don't work will make the whole optimization run crash -> solution: disable aborting with a flag in the scenario file/object

**Comment by mlindauer** [comment]
I thought the first configuration in the initial design is the default configuration and it would be weird if this already crashes. 
Furthermore, I would say that your configuration space is not so well designed, if the probability is so high to sample crashing configurations often.

Nevertheless, I do not object such an option.

**Comment by mfeurer** [comment]
Sorry, I meant full random search with a random initial design. I hope it makes more sense then.

**Comment by mlindauer** [comment]
@shukon Please take care of this issue.
