### ISSUE TITLE
incumbents in runhistory

### ISSUE THREAD

**Issue by aaronkl** [automl/SMAC3#179]
After I use fmin_smac I only have access to the runhistory. However in order to benchmark SMAC it would be nice if the runhistory also includes the incumbent trajectory such that I can plot performance over iterations / time.

**Comment by mlindauer** [comment]
not obvious, but you could use for the time being:
`smac.solver.intensifier.traj_logger.trajectory`

**Comment by mlindauer** [comment]
in the dev branch, you can now use `smac.get_trajectory()`
