### ISSUE TITLE
Show incumbent change diff

### ISSUE THREAD

**Issue by wanko** [automl/SMAC3#186]
@shukon : please see whether we can only show the diff between challenger and incumbent when we change it  --- greetings from marius

**Comment by shukon** [comment]
I am not sure I understand what you mean.
`INFO:intensifier:Challenger is better than incumbent by 0.0146 on 1 runs.` instead of `INFO:intensifier:Challenger (0.3459) is better than incumbent (0.3605) on 1 runs.`?

**Comment by mlindauer** [comment]
no, the diff between the configurations, not the performance values.
