### ISSUE TITLE
Force runs on default in intensify

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#188]
We should add an option such that intensification always runs the default on a new instance-seed pair, because 

1. to prevent over-tuning on heterogeneous instance sets
2. some ideas of better scaling solution quality values across instances...

**Comment by frank-hutter** [comment]
Agreed, that option seems to help sometimes in SMAC2. 
Just make sure to first run the incumbent, so that adaptive capping can kick in and we do not incur too much overhead in scenarios where the default is really slow.

**Comment by mlindauer** [comment]
I don't know whether I agree with running the def after the inc. but maybe we can discuss this offline.

**Comment by mlindauer** [comment]
fixed in #247
