### ISSUE TITLE
Limit maxR

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#19]
Originally reported by: **Matthias Feurer (Bitbucket: [mfeurer](https://bitbucket.org/mfeurer), GitHub: [mfeurer](https://github.com/mfeurer))**

---

Currently, maxR is set to 2000. This might be useful for algorithm configuration, but it isn't for machine learning with five-fold cross-validation. We need to add this as an argument.

---
- Bitbucket: https://bitbucket.org/aadfreiburg/smac3/issue/19

**Comment by mfeurer** [comment]
Since #138, there is also a minR flag which needs to be added.
