### ISSUE TITLE
Is the restore scenario option missing?

### ISSUE THREAD

**Issue by musamarcusso** [automl/SMAC3#193]
Hi, 

I have been using the smac script for my work and I read in the [manual](http://www.cs.ubc.ca/labs/beta/Projects/SMAC/v2.10.03/manual.pdf) (page 6) that it is possible to restart the scenario using the stored states with the option --restore-scenario, but I couldn't do it, though. The help gives the following options 

usage: smac [-h] --scenario_file SCENARIO_FILE [--seed SEED]
            [--verbose_level {INFO,DEBUG}]

optional arguments:
  -h, --help            show this help message and exit

Required Options:
  --scenario_file SCENARIO_FILE
                        scenario file in AClib format (default: None)

Optional Options:
  --seed SEED           random seed (default: 12345)
  --verbose_level {INFO,DEBUG}
                        random seed (default: 20)

Is this option still available or am I missing something?

**Comment by mlindauer** [comment]
Hi,

SMAC3 (Python) does not support all modes and options of SMAC2 (Java). Although it is on our todo-list to re-implement the restoring function, it is not yet implemented.

Best,
Marius

**Comment by musamarcusso** [comment]
Hi, 

thanks for the information! I'll be following the updates here to check when this is available.

Best regards,
Musa

**Comment by mlindauer** [comment]
Dear Musa,

I'm very sorry that it took so long too provide this feature. However, we merged it today into the development branch and it will be part of the next release. Any feedback is highly appreciated.

Best,
Marius

**Comment by musamarcusso** [comment]
Hello Marius,
no need to be sorry, I'm happy it is available :) I will update SMAC on my machine and try it out. I will give a feedback in case I find any issues.
Best, 
Musa
