### ISSUE TITLE
use instance as string or an ID of an instance in runhistory?

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#2]
Originally reported by: **Marius Lindauer (Bitbucket: [mlindauer](https://bitbucket.org/mlindauer), GitHub: [mlindauer](https://github.com/mlindauer))**

---

The runhistory was designed to get only an id of instance to save memory. right now, all methods expect a string here. we should change this... assigned to me :-)

---
- Bitbucket: https://bitbucket.org/aadfreiburg/smac3/issue/2

**Comment by mfeurer** [comment]
Wasn't this solved by #32?

**Comment by mlindauer** [comment]
no, #32 used only IDs for configurations but not for instances.
