### ISSUE TITLE
Increasing verbosity in boolean scenario-arguments

### ISSUE THREAD

**Issue by shukon** [automl/SMAC3#201]
Currently, any value not in `1, "true", True` evaluates to False without any warning. This does not feel like expected behaviour (and in my case unnecessary bug-searching), especially in cases where e.g. TRUE evaluates to False. So if there is no good reason, I propose making `Scenario._is_truthy` explicit in accepting a number of values as True/False and raise an exception for unexpected values.
https://github.com/automl/SMAC3/blob/master/smac/scenario/scenario.py#L26

**Comment by mlindauer** [comment]
agreed.

**Comment by mlindauer** [comment]
Thanks.
