### ISSUE TITLE
No termination with "runcount-limit" lesser then a number of possible combinations

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#21]
Originally reported by: **Anatolii Domashnev (Bitbucket: [ayaro](https://bitbucket.org/ayaro), GitHub: [ayaro](https://github.com/ayaro))**

---

In one of my settings it's possible that the size of my config space is rather small (only 26 possible configurations). With a fixed "runcount-limit" (e.g. 50), my algorithm fails to terminate.

Linux Mint 18, Python 3.5.2

---
- Bitbucket: https://bitbucket.org/aadfreiburg/smac3/issue/21

**Comment by mfeurer** [comment]
Related to #25. The underlying functionality should live in the ConfigSpace and I opened the following issue https://github.com/automl/ConfigSpace/issues/31.

**Comment by mfeurer** [comment]
The upcoming version of the configspace package will have a new method `estimate_size()` which can be used to check if a configuration space is finite. Based on that one could add functionality to deal with a limited configuration space, for example by [enumerating all configurations](https://automl.github.io/ConfigSpace/master/API-Doc.html#ConfigSpace.util.generate_grid) and using those in the EI optimization or by keeping track of whether all configurations have already been sampled (after enumerating them).

**Comment by alexandertornede** [comment]
#25 #718

**Comment by sarah-segel** [comment]
Will be addressed in #959, thus this issue is closed.
