### ISSUE TITLE
Optimization goes crazy when target algorithm returns np.NaN

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#225]
If the target algorithm return `np.NaN`, the following check in `intensification.py` evaluates to `False` ([here](https://github.com/automl/SMAC3/blob/master/smac/intensification/intensification.py#L432)):

    if chal_perf > inc_perf and len(chall_runs) >= self.minR:

This results in an incumbent change. If the next configuration is working fine again (i.e. not returning an `np.NaN`), it becomes the new incumbent and the optimization goes on normally. If all configurations return `np.NaN`, each new configuration will become the new incumbent.

Can be reproduced by changing the return value in the rosenbrock example to always return NaN.

**Comment by shukon** [comment]
Does it make sense to treat NaN like CRASHED, so this could be caught at TAE-level? Something like
```
if self.run_obj == "runtime" and np.isnan(runtime) or np.isnan(cost):
    status = StatusType.CRASHED
```

**Comment by mfeurer** [comment]
Good idea :) @KEggensperger @mlindauer what do you think?

**Comment by KEggensperger** [comment]
Yes, that's what I would have proposed as well: Treating NaNs as CRASHED.
I assume this also applies to -inf and inf

**Comment by shukon** [comment]
Implemented in branch https://github.com/automl/SMAC3/tree/issue/%23225_check_TA_for_nan.

**Comment by mlindauer** [comment]
this issue is solved by adding a scenario option to define the quality of crashed runs. see #229

**Comment by mlindauer** [comment]
Unfortunately, this issue is not completely solved.
Unexpectedly, one of my TAs returned a nan and SMAC accepted it without complaining enough. 
So, we have to look in this issue again.

**Comment by mlindauer** [comment]
I couldn't reproduce it, so closed again.
