### ISSUE TITLE
landscape.io Hiatus

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#244]
https://landscape.io/hiatus:
"Checking paused for open source projects for a few months."

I wonder whether we need landscape.io at all. Is anyone looking into the errors and warnings? 
Our score of 66% looks rather bad and is not a praise for our code.
Considering these points I would argue for dropping landscape.io.

**Comment by mfeurer** [comment]
No, it would be good to look at them and actually fix them, but I don't see anyone having time to do that. Therefore, I agree on dropping landscape.io.

**Comment by KEggensperger** [comment]
Landscape.io seems to work again, so I close that issue.
