### ISSUE TITLE
Issues with pyrfr-0.40

### ISSUE THREAD

**Issue by musamarcusso** [automl/SMAC3#248]
Hello, 

I installed the latest version of SMAC from the master branch and ran `pip install -r requirements.txt`, but I can't get around this issue:

INFO:	Reading scenario file: scenario_20170512150837.txt
INFO:	Output to smac3-output_2017-05-12_15:08:37_(792757)
Traceback (most recent call last):
  File "/home/mam0box/Software/SMAC3/scripts/smac", line 20, in <module>
    smac.main_cli()
  File "/home/mam0box/Software/SMAC3/smac/smac_cli.py", line 91, in main_cli
    initial_configurations=initial_configs)
  File "/home/mam0box/Software/SMAC3/smac/facade/smac_facade.py", line 129, in __init__
    pca_components=scenario.PCA_DIM)
  File "/home/mam0box/Software/SMAC3/smac/epm/rf_with_instances.py", line 73, in __init__
    self.rng = regression.default_random_engine(seed)
AttributeError: module 'pyrfr.regression' has no attribute 'default_random_engine'

I tried reinstalling pyrfr but didn't get anywhere. Any ideas on how I could solve this?

**Comment by mlindauer** [comment]
Hi,

do you use anaconda? If yes, please try to install the dependencies of the pyrfr within anaconda:
`conda install gcc swig`

afterwards, please first deinstall pyrfr and then install it again:
```
pip uninstall pyrfr
pip install pyrfr
```

If the issue still exists afterwards, please post the output of `pip install pyrfr`.

Best,
Marius

**Comment by musamarcusso** [comment]
Hi Marius, 
I don't use anaconda, I tried installing `pyrfr` with `pip` and by installing manually the package. I have one machine where I haven't updated neither SMAC or `pyrfr` and I can still run the simulation.

**Comment by mlindauer** [comment]
Could you please post the log of the installation of `pyrfr`,
i.e., the output of `pip install pyrfr`.

**Comment by musamarcusso** [comment]
Sorry for taking so long. In the end we managed to install here `pyrfr` successfully and then came an issue with `sklearn`.
File "/home/mam/Software/SMAC3/scripts/smac", line 12, in <module>
    from smac.smac_cli import SMACCLI
  File "/home/mam/Software/SMAC3/smac/smac_cli.py", line 8, in <module>
    from smac.facade.smac_facade import SMAC
  File "/home/mam/Software/SMAC3/smac/facade/smac_facade.py", line 23, in <module>
    from smac.optimizer.smbo import SMBO
  File "/home/mam/Software/SMAC3/smac/optimizer/smbo.py", line 10, in <module>
    from smac.optimizer.acquisition import AbstractAcquisitionFunction
  File "/home/mam/Software/SMAC3/smac/optimizer/acquisition.py", line 7, in <module>
    from smac.epm.base_epm import AbstractEPM
  File "/home/mam/Software/SMAC3/smac/epm/base_epm.py", line 7, in <module>
    from sklearn.exceptions import NotFittedError
ImportError: No module named 'sklearn.exceptions'

even though with `sudo pip install sklearn` it said that everything was installed correctly (`pip install sklearn` didn't work due to permissions). The same happened using `pip3`.
What solved it was using `sudo apt-get install python3-sklearn`.

**Comment by mlindauer** [comment]
without knowing some more details, I can only guess the issues. 

I would guess that an old sklearn version was already installed, which was not compatible with SMAC. I will check whether we will have a required minimal sklearn version in the future.
`sudo pip install sklearn` : probably an old `sklearn` version was already installed on your machine and `pip` does not update a version without the option `-U`
`pip install sklearn` (permissions): in the future, you could consider to use the option `--user` to install it in your user-space, you could use a `virtualenv`, or you could use anaconda, which also lives in the user-space.

Since all issues are now resolved, can we close this ticket?

Best,
Marius

**Comment by musamarcusso** [comment]
Yes, you can close the ticket. 
I did uninstall all the packages and installed them again, I still had the same issues. Sorry if I am vague, these issues happened under the user of a colleague, but for mine it still worked fine on the same PC, so I think that using the `--user` option might be the solution. 
Anaconda will have to wait a little, I have a lot of ROS dependencies that I don't want to have to fix eventually.
Thanks for the feedback!
