### ISSUE TITLE
target functions with additional input arguments

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#255]
Sometimes the objective functions need an additional argument (e.g. a dataset/path/etc) which for simplicity is not treated as an instance. When using `partial` to set this argument optimization crashes with:

> TypeError:  run_cfg() got an unexpected keyword argument 'instance'

This unexpected behaviour is due to [this piece of code](https://github.com/automl/SMAC3/blob/development/smac/tae/execute_func.py#L34) which automatically assumes that the third argument is `instance` if there is a third argument.

What would be the right way to handle additional arguments given our current implementation?

```from smac.configspace import ConfigurationSpace
from ConfigSpace.hyperparameters import UniformFloatHyperparameter

from smac.tae.execute_func import ExecuteTAFuncDict
from smac.scenario.scenario import Scenario
from smac.facade.smac_facade import SMAC

from functools import partial

def run_cfg(cfg, seed, one_more_input):
    return 1*one_more_input

cs = ConfigurationSpace()
some = UniformFloatHyperparameter("some", 0.0, 0.5, default=0.0)

cs.add_hyperparameters([some, ])

# SMAC scenario oject
scenario = Scenario({"run_obj": "quality",   # we optimize quality (alternative runtime)
                     "wallclock_limit": 30,
                     "cs": cs,               # configuration space
                     "deterministic": "true",
                     })

# This crashes
f_run_cfg = partial(run_cfg, one_more_input=3)
smac = SMAC(scenario=scenario, rng=np.random.RandomState(42),
            tae_runner=f_run_cfg)

incumbent = smac.optimize()
```

**Comment by mlindauer** [comment]
We could check for named arguments instead of checking the length of the signature,
e.g., 
`self._accepts_instance = inspect.signature(ta).parameters.get("instance") is not None`

**Comment by sfalkner** [comment]
You can also create a function whose signature actually has only two variables. Simply replace your definition of ```f_run_cfg``` by
```
f_run_cfg = lambda c,seed: run_cfg(c,seed, one_more_input=3)
```
and your example runs through just fine (except for some missing import statements in the beginning)

**Comment by mlindauer** [comment]
@KEggensperger is this still an open issue?

**Comment by vlavorini** [comment]
Not sure if it worth to create a new issue for this. Is it possible to add the additional input argument while calling SMAC? Something like 

    smac = SMAC(scenario=scenario, rng=np.random.RandomState(42),
            tae_runner=f_run_cfg(what_to_put_here, one_more_input=3))

**Comment by mlindauer** [comment]
I would guess that you can simply use:

```
smac = SMAC(scenario=scenario, rng=np.random.RandomState(42),
        tae_runner=lambda c,seed: run_cfg(c,seed, one_more_input=3))
```

If you don't like `lambda`, you could also go for https://docs.python.org/3/library/functools.html#functools.partial
