### ISSUE TITLE
Finish API documentation

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#265]
Currently, the API documentation is not fully done as not all methods of all classes are rendered in the sphinx doc.

**Comment by mfeurer** [comment]
This was partially fixed via #278 which fixed which functions are rendered. However, not all functions/classes are correctly annotated at the moment.

**Comment by shukon** [comment]
@mfeurer I'm currently not aware of what the remaining problem is, could you clarify it?

**Comment by mfeurer** [comment]
@KEggensperger fixed this in #288 and @mlindauer in #289. Thanks for reminding me to close this.
