### ISSUE TITLE
Rename solution quality

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#266]
I find the term solution quality very strange as SMAC is actually minimizing a loss. Therefore, I propose to replace the term quality by loss/cost and use the term minimize instead of optimize throughout the package.

**Comment by mlindauer** [comment]
In principle, I agree. However, we support right now the keyword "quality" in our scenario files because of historic reasons and I'm hesitant to drop this support. 
We could change everything to "loss" or "cost", but we should still silently support the old keyword "quality".

**Comment by mlindauer** [comment]
Now, SMAC3 outputs lines such as:
`INFO:   Updated estimated error of incumbent on 59 runs: 2.8620`

"Error" is very confusing and I would say it is even wrong.
I would expect that an error can be minimized to 0, but this is obviously not true for running time (and also for many other quality scenarios).

I strongly request to change the output to use "cost".

**Comment by sfalkner** [comment]
+1 on renaming quality to loss and silently accepting quality as a valid flag.
I would be careful with the term 'cost' as this could be confused with a cost associated with running a configuration (like runtime).

**Comment by mlindauer** [comment]
please discuss the use of the word "cost" with Frank... I already surrendered ;-)
