### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by shukon** [automl/SMAC3#267]
SMAC validation missing. A few questions regarding implementation:

- should new runs be added to existing runhistory?
- how to control "budget" for non-deterministic runs? Via Stats with wallclock/cpu-limits or rather setting a certain number of runs (i.e. at least 20 runs per instance)?
- should there be a scenario-option like "validate = True/False" to activate automatic validation after a smac-run? 
- validation on train-instances as an option?
- should one seed be used for all instances or rather completely independent instance-seed-pairs?
- anything else you think is important?

**Comment by mlindauer** [comment]
> should new runs be added to existing runhistory?

smac-validate should have the option to read in already existing runhistories and use them to avoid rerunning already validated runs. however, it would be better if smac-validate would write its on runhistorie in the end consisting only of the validation runs and nothing more.

btw: the only required input arguments should be the scenario and a trajectory file.

> how to control "budget" for non-deterministic runs? Via Stats with wallclock/cpu-limits or rather setting a certain number of runs (i.e. at least 20 runs per instance)?

wallclock/cpu-limit should not matter for smac-validate. 
Repeated runs for non-deterministic algorithms is our default. 
However, the default should be set to 1.

> should there be a scenario-option like "validate = True/False" to activate automatic validation after a smac-run?

For the first version, "validate" has not be part of a smac run. Therefore, no.

> validation on train-instances as an option?

Yes.
In detail, we would need the following:
* for the instance set: TRAIN or TEST or TRAIN+TEST
* for the configuration to be validated: DEF or INC or DEF+INC or TIME
where "TIME" means that the incumbent over time will be validated,
e.g., performance of the incumbent at time steps 2^0, 2^1, 2^2, 2^3, ...

> should one seed be used for all instances or rather completely independent instance-seed-pairs?

for deterministic algorithms, the seed can be fixed to 0.
for non-deterministic algorithms, you need n instance-seed pairs depending on the option discussed in question 2. These instance-seed pairs have to be the same for all validated configurations.

> anything else you think is important?

highly parallelized validation on a cluster would be nice, i.e., 1 master that knows all the validation runs, and 1000 workers on a cluster that do the actual target algorithm runs and report the results to the master. for this, please also see my e-mail regarding `joblib`.

**Comment by mfeurer** [comment]
I think an option to validate the whole trajectory as in SMAC2 would be great, something like an ALL option.
