### ISSUE TITLE
Writing pcs to disk only for old pcs format supported

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#268]
Right now, SMAC always tries to write the pcs to disk assuming the old pcs format. It would be better to use the new pcs format, but @KEggensperger said that probably not all features are already implemented for it.
So, the ConfigSpace first needs to be fixed and then we have to change the pcs writer in SMAC.

**Comment by mfeurer** [comment]
Is this fixed by merging PR #272?

**Comment by mlindauer** [comment]
Yes
