### ISSUE TITLE
No such file or directory: 'python' when installing python 3.5.2 after uninstalling python 2.7

### ISSUE THREAD

**Issue by loshchil** [automl/SMAC3#284]
I uninstalled python 2.7 on my fresh Ubuntu 16 and then I installed python 3.5.2. 
When calling the branin example, the code fails suggesting that 'python' does not exist because it actually the case and only 'python3' exists / is callable. 

`python3 ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.smac_cli.SMACCLI:SMAC call: ../../scripts/smac --scenario branin_scenario.txt
INFO:smac.scenario.scenario.Scenario:Reading scenario file: branin_scenario.txt
INFO:smac.scenario.scenario.Scenario:Output to smac3-output_2017-07-26_14:25:26_(659782)
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: -1
INFO:smac.stats.stats.Stats:#Target algorithm runs: 0 / 500.0
INFO:smac.stats.stats.Stats:Used wallclock time: 0.00 / inf sec
INFO:smac.stats.stats.Stats:Used target algorithm runtime: 0.00 / inf sec
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_facade.SMAC:Final Incumbent: None
Traceback (most recent call last):
File "../../scripts/smac", line 20, in 
smac.main_cli()
File "/home/ilya/work/SMAC3/smac/smac_cli.py", line 86, in main_cli
optimizer.optimize()
File "/home/ilya/work/SMAC3/smac/facade/smac_facade.py", line 339, in optimize
incumbent = self.solver.run()
File "/home/ilya/work/SMAC3/smac/optimizer/smbo.py", line 104, in run
self.incumbent = self.initial_design.run()
File "/home/ilya/work/SMAC3/smac/initial_design/single_config_initial_design.py", line 80, in run
instance_specific=self.scenario.instance_specific.get(rand_inst, "0"))
File "/home/ilya/work/SMAC3/smac/tae/execute_ta_run.py", line 147, in start
instance_specific=instance_specific)
File "/home/ilya/work/SMAC3/smac/tae/execute_ta_run_old.py", line 80, in run
p = Popen(cmd, shell=False, stdout=PIPE, stderr=PIPE, universal_newlines=True)
File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
restore_signals, start_new_session)
File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'python'`

**Comment by mlindauer** [comment]
It is somehow weird that you have installed Python but `python` is not available. 
I don't know a general solution to weird system setups.

**Comment by sfalkner** [comment]
It's not a weird setup at all. There is actually a PEP (https://www.python.org/dev/peps/pep-0394/) about that. It is just that Anaconda  ignores it and ```python``` refers to whatever your installed version is. Ubuntu on the other hand honours the naming convention and ```python``` equals ```python2``` which doesn't exists in this case.
As SMAC is in python, there is a way to find out which python executable is running this process:
```
>>> import sys
>>> sys.executable
'/usr/lib/python-exec/python3.4/python'
```
The result of that should be used to start the new subprocess. This ensures that it will automatically use whatever python interpreter the user started SMAC in, including cases where this interpreter is not the system-wide ```python``` command.

**Comment by mlindauer** [comment]
I have no problem to change the example such that it uses `python3 `instead of `python`.

However, I don't really like the idea of using the same python for the target algorithm as for SMAC.
We had already exemplary use cases where the user wanted to use different python installations (e.g., different virtualenvs) for SMAC and the target algorithm. 

In the end, this is only the example and not a general issue of SMAC. So, I'm open for solutions as long the example is still as simple as possible. (sys.executable sounds a bit cryptic to me).

**Comment by sfalkner** [comment]
If you change it to python3, then the example doesn't work on systems with only python 2.x installed. Not that this would be relevant any more.
But in general, I think that SMAC should have an option to specify the python interpreter for a function to be minimized that defaults back to the one running SMAC itself. I can see use-cases where you need a different interpreter, but the average user doesn't even think about that. So the target algorithm runner class should give the user an option for that, probably when instantiated.

**Comment by mlindauer** [comment]
I don't quite understand your point.
Right now, a user has two options:

1. he/she uses the TAE class that calls TAE via the shell. this is can be completely independent of Python or also a different python interpreter
2. he/she uses the TAE class that minimizes a python function. In this case, we never go outside of the python interpreter that runs SMAC (afaik).

**Comment by sfalkner** [comment]
That is not quite correct. If you limit the resources with the pynisher a separate subprocess is created which could potentially use a different python version. But I see your point; that could be covered with the TAE via the shell.
