### ISSUE TITLE
Feature request: report the best objective function value found so far and the best possible/known objective function value (if available)

### ISSUE THREAD

**Issue by loshchil** [automl/SMAC3#285]
After running 
`python ../../scripts/smac --scenario branin_scenario.txt`
the algorithm outputs x1 and x2 of the suggested solution / incumbent. 
`INFO:smac.facade.smac_facade.SMAC:Final Incumbent: Configuration:
x1, Value: 3.142580841213171
x2, Value: 2.3410491529064674`
It would be useful to see how good this solution is, i.e., its objective function value. Also, it might be useful to report the best possible/known objective function value (if available).

**Comment by mfeurer** [comment]
@shukon @mlindauer can this be closed?
