### ISSUE TITLE
time_bound should be an integer

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#287]
I just came across this:

https://github.com/automl/SMAC3/blob/development/smac/optimizer/epils.py#L172

time_bound is defined to be an integer, but is set to 0.01

**Comment by mlindauer** [comment]
Is the docstring wrong or the value passed?

**Comment by KEggensperger** [comment]
The docstring and the type annotation were wrong. Nevertheless, I changed it and pushed it to the API doc PR
