### ISSUE TITLE
pSMAC crashed at file reading because of race condition

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#292]
When one pSMAC run writes its runhistory json file and another run reads the same file at the same time, the reading run may fail because the json file is not valid at this moment.
(So far, I believed that this is more a theoretical problem, but I encountered that problem in practice.)

We would need a way to lock files for writing them before we can read them--- parallel reading shouldn't be a problem. 
A solution could be the following package:
https://pypi.python.org/pypi/filelock/

**Comment by mfeurer** [comment]
In auto-sklearn we use the deprecated [lockfile](https://pypi.python.org/pypi/lockfile/). Maybe the packages they suggest as a replacement are worth looking into, too.
