### ISSUE TITLE
Not meant for comparison benchmarks?

### ISSUE THREAD

**Issue by amueller** [automl/SMAC3#293]
[This page](http://www.ml4aad.org/algorithm-configuration/smac/) says "not meant for comparison benchmarks". What does that mean?

**Comment by mlindauer** [comment]
Our official recommendation is still to use SMAC written in Java if someone wants to compare different algorithm configuration systems.
I hope this answers your question.

**Comment by amueller** [comment]
Why? Is there a comparison in terms of speed?
I don't think this recommendation is very helpful unless you quantify it and say "this will be much slower than the java implementation" or "this is not stable yet and results might be different".

**Comment by mlindauer** [comment]
> Why? 

From a research perspective, SMAC3 (Python) and SMAC2 (Java) slightly differ. If someone wants to compare against the exact algorithm as described in SMAC paper, he/she should use SMAC2.

Of course, we have comparison benchmarks between SMAC3 and SMAC2. And we are very confident that SMAC3's performance is very similar to the performance of SMAC2 --- sometimes slightly worse and sometimes slightly better.
So, from a user perspective, using SMAC3 is perfectly fine.

**Comment by amueller** [comment]
Cool, that makes sense. Are the benchmarks published somewhere? And maybe you can put that explanation in the docs?
So  "SMAC3 performs similarly but implements a slightly different algorithm than published in [SMAC paper]" is a fair summary?

Thank you!

**Comment by mlindauer** [comment]
> Are the benchmarks published somewhere?

No, they are not. Maybe we could add some figures in the documentation at some point if this would help.

> And maybe you can put that explanation in the docs?

The docs already say:
"This version is not meant to be a reference implementation for SMAC according the above cited LION paper. Please use SMAC v2 (Java) for comparisons against SMAC."
https://automl.github.io/SMAC3/stable/

If you think that this is not sufficient, I'm happy to extend it further.

> So "SMAC3 performs similarly but implements a slightly different algorithm than published in [SMAC paper]" is a fair summary?

Yes.

**Comment by amueller** [comment]
I guess I just find the remark (not meant for comparison benchmarks) a bit
cryptic. Maybe either remove it, given the warning in the other place, or
replace it by (not a reference implementation of \cite). Given what you
said it totally makes sense to use it for benchmarks, just not for
attributing it to the original paper.

Sent from phone. Please excuse spelling and brevity.

On Aug 3, 2017 09:35, "Marius Lindauer" <notifications@github.com> wrote:

Are the benchmarks published somewhere?

No, they are not. Maybe we could add some figures in the documentation at
some point if this would help.

And maybe you can put that explanation in the docs?

The docs already say:
"This version is not meant to be a reference implementation for SMAC
according the above cited LION paper. Please use SMAC v2 (Java) for
comparisons against SMAC."
https://automl.github.io/SMAC3/stable/

If you think that this is not sufficient, I'm happy to extend it further.

So "SMAC3 performs similarly but implements a slightly different algorithm
than published in [SMAC paper]" is a fair summary?

Yes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/automl/SMAC3/issues/293#issuecomment-319970575>, or mute
the thread

**Comment by mlindauer** [comment]
Ok. I removed it.
Thanks for the pointers.
