### ISSUE TITLE
Make a Target Algorithm runner that works directly with python functions

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#3]
Originally reported by: **Tobias Springenberg (Bitbucket: [stokasto](https://bitbucket.org/stokasto), GitHub: [stokasto](https://github.com/stokasto))**

----------------------------------------

Currently the Scenario needed to create an SMBO instance directly requires parsed command line arguments and parses a pcs file.
Furthermore the code assumes that the target algorithm will be a file that is executed (and results are shoved through a pipe).

Both of these are often not the case, as a result we had to specialize Scenario in auto-sklearn and in other places.
This is not really user friendly. We probably way to to have a scenario sub-class that can be instantiated solely within python without external files. 

What is more important though is that we need a runner that can directly execute python functions.

----------------------------------------
- Bitbucket: https://bitbucket.org/aadfreiburg/smac3/issue/3

**Comment by mfeurer** [comment]
This feature is introduced by #55 in form of the class `FuncSmac`. Issue #49 also covers this. Closing it for now.
