### ISSUE TITLE
Problem with GPU

### ISSUE THREAD

**Issue by ffalfred** [automl/SMAC3#300]
Hello,

I have added a fmin_smac function to my python code, for a couple of hyperparameters of a neural network done by Lasagne and Theano. However, this is what it appears when trying to run the code:

Error when tring to find the memory information on the GPU: initialization error
Error freeing device pointer 0x2302548000 (initialization error). Driver report 0 bytes free and 0 bytes total
CudaNdarray_uninit: error freeing self->devdata. (self=0x7f7b60cef9b0, self->devata=0x2302548000)
Exception ignored in: 'garbage collection'
MemoryError: error freeing device pointer 0x2302548000 (initialization error)
Fatal Python error: unexpected exception during garbage collection

I dont have any clue why this problem appears.

Thanks in advance

**Comment by mfeurer** [comment]
Hi, I recall this error happening when we set a memory limit and used GPUs. However, the `fmin_smac` should not invoke a memory limit on the target function. @mlindauer do you think we can use make the option to not use the pynisher the standard for the `fmin_smac` interface?

**Comment by mlindauer** [comment]
@ffalfred 
Thanks for reporting this issue. 

@mfeurer since a user does not see the memory limit and runtime limit for each TAE call through the `fmin_smac` interface anyway, this sounds very reasonable.

**Comment by mfeurer** [comment]
I'm currently thinking about making this a bit more general. If the user does neither provide a memory nor a time limit, we don't need the pynisher. Then we can also remove the new boolean flag again. What do you think?

**Comment by mlindauer** [comment]
> What do you think?

I thought you wanted the fmin-interface to be very similar to the scipy fmin!?
But I'm fine with adding two more arguments (mem_limit, time_limit).

**Comment by mlindauer** [comment]
@mfeurer how to resolve this issue? We still use the pynisher in our fmin interface (if I'm not wrong). Should I simply disable it in the fmin interface?
