### ISSUE TITLE
execute_ta_run_old.py breaking on the latest version

### ISSUE THREAD

**Issue by musamarcusso** [automl/SMAC3#305]
Hello, 

I updated SMAC recently and an error started happing now when I try to run pSMAC. This uses the smac script and a wrapper. 

INFO:smac.smac_cli.SMACCLI:SMAC call: /home/mam/catkin_ws/src/uuv_simulator/uuv_evaluation/scripts/smac --scenario scenario_2017-08-16_12:09:08_16354.txt --verbose INFO --seed 22012 --shared_model True --input_psmac_dirs smac3-output*
Traceback (most recent call last):
  File "/home/mam/catkin_ws/src/uuv_simulator/uuv_evaluation/scripts/smac", line 49, in <module>
    smac.main_cli()
  File "/usr/local/lib/python3.5/dist-packages/smac-0.6.0-py3.5.egg/smac/smac_cli.py", line 99, in main_cli
    optimizer.optimize()
  File "/usr/local/lib/python3.5/dist-packages/smac-0.6.0-py3.5.egg/smac/facade/smac_facade.py", line 365, in optimize
    incumbent = self.solver.run()
  File "/usr/local/lib/python3.5/dist-packages/smac-0.6.0-py3.5.egg/smac/optimizer/smbo.py", line 160, in run
    time_bound=max(self.intensifier._min_time, time_left))
  File "/usr/local/lib/python3.5/dist-packages/smac-0.6.0-py3.5.egg/smac/intensification/intensification.py", line 162, in intensify
    self._add_inc_run(incumbent=incumbent, run_history=run_history)
  File "/usr/local/lib/python3.5/dist-packages/smac-0.6.0-py3.5.egg/smac/intensification/intensification.py", line 263, in _add_inc_run
    instance_specific=self.instance_specifics.get(next_instance, "0"))
  File "/usr/local/lib/python3.5/dist-packages/smac-0.6.0-py3.5.egg/smac/tae/execute_ta_run.py", line 168, in start
    instance_specific=instance_specific)
  File "/usr/local/lib/python3.5/dist-packages/smac-0.6.0-py3.5.egg/smac/tae/execute_ta_run_old.py", line 64, in run
    for p in config:
TypeError: 'NoneType' object is not iterable

I saw that the error occurs [here](https://github.com/automl/SMAC3/blob/master/smac/tae/execute_ta_run_old.py#L64) and all SMAC instances break. However, I have one machine were a slightly [older version](https://github.com/automl/SMAC3/blob/d7f1a78a14631c9b3760a3dd59f24ce458dab9d1/smac/tae/execute_ta_run_old.py) of SMAC is running and everything runs with pSMAC normally.
Could you help me figure this out?
Thanks in advance.

**Comment by mlindauer** [comment]
Hi,

sorry, most of our team is on vacation this week (including me).

Here some questions to narrow the search:

1. Have you also updated all requirements? `pip install -r requirements.txt --upgrade`
1. Is this a pSMAC issue or a general SMAC issue?
1. Can you provide a minimal working example such that we can reproduce the issue?

Best,
Marius

**Comment by musamarcusso** [comment]
Hello Marius,

1. Yes, I did update the requirements and it upgraded the packages without issues apart from this one from `pyrfr`

```
Could not find .egg-info directory in install record for pyrfr>=0.5.0 from https://pypi.python.org/packages/29/26/483591f369e9b030497dc5eee9a9b3a90ee4668b449159d396f7758e6c3c/pyrfr-0.5.tar.gz#md5=97b8fdfde20386cee9ed2000c4f9ec53 (from -r requirements.txt (line 10))
```

I installed it later on from the GitHub repository, even though there was some weird problems regarding headers installed on my `/usr/local/include` that broke my other projects I was trying to compile. But from the error message, I don't think this issue comes from `pyrfr`.

2. This happens in both cases, with and without the shared model flag.

3. I will make the example here and also see if this happens again, I will send you the files so that you can check it.

Best,

Musa

**Comment by musamarcusso** [comment]
Hi, I'm still working on the example, but meanwhile I could find a way to make things work again by getting cloning SMAC3 and fetching the working version with `git fetch origin 855cfa344b53948ba2f80ae69f64c7ac63e82b43` and then installing the requirements with `cat requirements.txt | xargs -n 1 -L 1 pip3 install --user`. The examples in the SMAC3 folder still work, by the way, only the newest version doesn't run with the configuration I had working before.

**Comment by mlindauer** [comment]
Dear Musa,

> but meanwhile I could find a way to make things work again by cloning SMAC3 and fetching the working version with git fetch origin 855cfa344b53948ba2f80ae69f64c7ac63e82b43

Is this the last commit that works fine for you?
So, the reason would be in the next commit.

> only the newest version doesn't run with the configuration I had working before.

could you please post some parts of this configuration?

**Comment by uuvsimulator** [comment]
Hi @mlindauer, after I updated the latest version of `pyrfr` things went back to normal. I think this issue can be closed now.

**Comment by musamarcusso** [comment]
Hi @mlindauer, after updating `pyrfr` to the latest version, the issue didn't come up anymore. I think this issue can be closed.

**Comment by mlindauer** [comment]
Ok, thanks for reporting it anyway.
