### ISSUE TITLE
Cooling down fraction of random configurations over time

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#308]
idea from @sfalkner 
instead of every second configuration being a random configuration,
cooling down the fraction of random configurations over time.

**Comment by mlindauer** [comment]
The first step was done in #356, but we need some more stuff to do it right... so, not closed for now

**Comment by aaronki** [comment]
@mlindauer Could you please explain what should be done so I can continue to work on the issue?

**Comment by mlindauer** [comment]
not now, let's talk about that another time.

**Comment by mfeurer** [comment]
@mlindauer can we close this?

**Comment by mlindauer** [comment]
yes, thanks for reminding me.
