### ISSUE TITLE
Scenario options docs not rendered properly

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#310]
As can be seen here: https://automl.github.io/SMAC3/stable/apidoc/smac.scenario.scenario.html

Also, it would be great if the scenario object actually had a link to the scenario object: https://automl.github.io/SMAC3/stable/apidoc/smac.scenario.scenario.html

**Comment by shukon** [comment]
Not sure if this is what you mean, rendering as fields now (see screenshot) and adding a link to the scenario-api in branch https://github.com/automl/SMAC3/tree/issue/%23310_scenario_options/doc

![smac3_scen_opts](https://user-images.githubusercontent.com/9417378/30004512-01376558-90d1-11e7-8001-b764719c49cb.png)

**Comment by mfeurer** [comment]
Yes, that's exactly what I meant. It looks great! And I just realized that one of my links was incorrect, please excuse this.

**Comment by shukon** [comment]
#313 fixed this
