### ISSUE TITLE
Non-Deterministic although random seed fixed

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#317]
SMAC is non-deterministic although it optimizes solution quality, the budget is limited by target algorithm runs and a random seed was given. In this setting, SMAC should have a deterministic behavior.

**Comment by aaronki** [comment]
Created a script to check deterministic behaviour: [https://gist.github.com/aaronki/a7c06f442448e0d819696e71d8e4e4eb](url)

**Comment by mfeurer** [comment]
This should be fixed now. Could you please check and close if applicable?

**Comment by mfeurer** [comment]
Actually, this is not fixed - at least the unit test `test_deterministic` fails for me if I do not add `intensification_percentage` to the scenario - I assume this test fails as I'm adding plateau walking and now the optimization of the acquisition function takes longer.
