### ISSUE TITLE
Installation error on OSX

### ISSUE THREAD

**Issue by engelen** [automl/SMAC3#330]
Users running OSX regularly encounter a problem installing SMAC3-based packages because of a compilation error of `pyrfr`. I'm opening this issue to make people encountering this when installing SMAC aware of the issue; a potential fix has already been provided in [this auto-sklearn issue](https://github.com/automl/auto-sklearn/issues/360). Quoting the solution from there:
> Ok, I was able to install and launch the package, still I am not sure it will 100% work.
>
> Basically you must have, a version of gcc more recent than the 4.7 and have xcode installed.
> 
> You cannot install pyrfr by pip, and the only option is to download the package and install it manually.
> Be careful to download the 0.6.1 version of the package. If you install the 0.7, auto-sklearn will try to downgrade it at the 0.6.1, downloading it from the repository giving you once again the error.
>
> open the folder were you unzipped the codes and search for the setup.py file.
> just change the following line:
> extra_compile_args = ['-O2', '-std=c++11']
> into:
> extra_compile_args = ['-O2', '-std=c++11', '-stdlib=libc++', '-mmacosx-version-min=10.7']
>
> and then install it from the terminal (don't forget to be in the right folder) with the instuction:
sudo python setup.py install

**Comment by aaronki** [comment]
Note: MacOS is not officially supported by SMAC3.
The error reported could not be reproduced with the following two setups:
1)
  * MacOS High Sierra 17.3.0
  * python 3.6.4
  * run: pip3 install smac (the system's default C compiler is used)
2)
  * MacOS High Sierra 17.3.0, Anaconda 5.0.1 environment
  * Anaconda's gcc 4.8.5
  * Anaconda's Python 3.6.3
  * run: pip install smac
Closing this issue
