### ISSUE TITLE
SMAC always generates an output dir

### ISSUE THREAD

**Issue by aaronkl** [automl/SMAC3#357]
SMAC generates an output directory even though I set "output_dir": ""  in the Scenario object as it is described in the code.

**Comment by shukon** [comment]
Possible fix: https://github.com/automl/SMAC3/tree/issue/%23357_always_output_dir
Mainly fixing the relatively new `create_output_directory` to not create output-dir on empty string and fix some resulting test-failures in traj-logging.
@mlindauer you are assigned, can I take over and do PR?

**Comment by mlindauer** [comment]
Of course. Thank you!
