### ISSUE TITLE
Wrong parameters order

### ISSUE THREAD

**Issue by palmieri** [automl/SMAC3#367]
Hi all, 

we have realized that when using fmin_smac, the input parameters given to the function are processed in the wrong order if their count is higher than 9. 

For instance when executing this command: 

x, cost, _ = fmin_smac(func=to_minimize,
                       x0=[0.5, 20, 0.7, 0.15, 10, 0.5, 1.0, 0.1, 0.25, 1.0, 0.5],
                       bounds=[(0, 1), (5, 25), (0.1, 2.0), (0.0, 1.5), (2, 20), (0, 1), (1, 1.3), (0.001, 1), (0.001, 2), (0.05, 9), (0.2, 0.8)],
                       maxfun=2000,
                       rng=3)

the input parameters are swapped in the following way, as reported in the configspace.pcs file:

x1 real [0.0, 1.0] [0.5]
x10 real [0.05, 9.0] [1.0]
x11 real [0.2, 0.8] [0.5]
x2 real [5.0, 25.0] [20.0]
x3 real [0.1, 2.0] [0.7]
x4 real [0.0, 1.5] [0.15]
x5 real [2.0, 20.0] [10.0]
x6 real [0.0, 1.0] [0.5]
x7 real [1.0, 1.3] [1.0]
x8 real [0.001, 1.0] [0.1]
x9 real [0.001, 2.0] [0.25]

Any idea what's happening there? Thanks for your help!

Best, 

L.

**Comment by KEggensperger** [comment]
Yes, you are right. 

The issue is that the configuration gets "sorted" before calling your function which changes the order of parameters compared to your input: https://github.com/automl/SMAC3/blob/master/smac/tae/execute_func.py#L251

Should be relatively easy to fix.

**Comment by palmieri** [comment]
great! Thanks!
