### ISSUE TITLE
trajectory files use different CPU and wallclocktime

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#37]
SMAC outputs two trajectory files (traj_aclib2.json and traj_old.csv), but they do not use the same timestamps. Currently SMAC reads the time for writing to each file separately, we might want to change that such that CPU and wallclocktime is measured only once. 

https://github.com/automl/SMAC3/blob/master/smac/utils/io/traj_logging.py#L74

**Comment by mlindauer** [comment]
agreed. 
(I would be in favor to simply fix this directly in the dev branch)

**Comment by KEggensperger** [comment]
Yes, I will do this.

**Comment by KEggensperger** [comment]
Now, the use the same time, but showing exactly the same value is not possible as json.dump does not allow to specify a format and therefore always uses more decimal points than the csv. This happens for any value in both files.

I am not sure whether we will ever encounter this problem, but merging json and csv trajectory files can cause problems. Therefore, I will leave this issue open until we decide whether we need a solution.

**Comment by mlindauer** [comment]
@KEggensperger : thanks for the fix.

I don't think the precision of seconds is crucial here.
Merging both files should be also trivial since both have the same number of entries.
I close this issue until we have a real problem with it.
