### ISSUE TITLE
Move examples to sphinx gallery?

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#372]
[sphinx gallery](https://github.com/sphinx-gallery/sphinx-gallery) provides a easy way to render examples in a sphinx documentation. Most important, it does not rely on line numbers as our current examples do and would be less brittle.

**Comment by mfeurer** [comment]
We should also start unit-testing our examples to avoid issues like #389 .

**Comment by mfeurer** [comment]
The examples are ported to sphinx gallery, we still need to port the actual documentation.

**Comment by mfeurer** [comment]
Based on PR #697 we should also integrate them with mybinder.

**Comment by KEggensperger** [comment]
@mfeurer Can I close this? I created a new issue for adding Binder support.
