### ISSUE TITLE
Scenario Refactoring

### ISSUE THREAD

**Issue by aaronki** [automl/SMAC3#373]
Move options not directly regarding the scenario out of the scenario class (called SMAC options below, will be named smac_options in the code)

**Comment by mlindauer** [comment]
Scenario:
algo
execdir
deterministic
paramfile
run_obj
overall_obj
cost_for_crash
cutoff_time
memory_limit
tuner-timeout
wallclock_limit
runcount_limit
instance_file
test_instance_file
feature_file
instances
test_instances
initial_incumbent
features

SMAC options:
abort_on_first_run_crash
always_race_default
intensification_percentage
minR
maxR
output_dir
input_psmac_dirs
shared_model
