### ISSUE TITLE
Validation fails if instances without features are present

### ISSUE THREAD

**Issue by shukon** [automl/SMAC3#377]
As described [here](https://github.com/automl/CAVE/issues/114).

**Comment by AndreBiedenkapp** [comment]
There is a small mistake in my first description of the error. The feature_dict is just empty but will always be created.
https://github.com/automl/SMAC3/blob/2ec1fa9dd5403b189a3a79c20c4cc2774b2d8fd6/smac/scenario/scenario.py#L398-L400

https://github.com/automl/SMAC3/blob/2ec1fa9dd5403b189a3a79c20c4cc2774b2d8fd6/smac/utils/io/input_reader.py#L135-L156

So if no feature file is passed the feature_dict is always {}

**Comment by shukon** [comment]
fixed with #378
