### ISSUE TITLE
Cryptic warnings in validator

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/SMAC3#387]
Example output:
```bash
WARNING:root:validate_1__test_rng__2135392491
WARNING:root:validate_2__test_rng__491263
WARNING:root:validate_2__test_rng__1298508491
WARNING:root:validate_2__test_rng__630311759
WARNING:root:validate_2__test_rng__396591248
WARNING:root:validate_2__test_rng__799981516
WARNING:root:validate_2__test_rng__1484172013
WARNING:root:validate_2__test_rng__1704103302
WARNING:root:validate_2__test_rng__166716594
WARNING:root:validate_2__test_rng__1800426750
WARNING:root:validate_2__test_rng__795511698
INFO:smac.utils.validate.Validator:Collected 30 runs from 2 configurations on 20 instances with 1 repetitions. Reusing 10 runs from given runhistory.
```
The logger object of the Validator class is not used.
i.e. `logging.warning(msg)` is used instead of `self.logger.warning(msg)`.
This results in the leading `WARNING:root:` instead of `WARNING:smac.utils.validate.Validator:`
which is why I wasn't sure where the messages originated.

I don't think the messages are very helpful. Looking at the code I now know what they intend to show but I think they need to be reworked if they are intended to be read by a user.

Also I'm not sure if warning is the correct loglevel here. To me it looks like debugging output. However if the messages get reworked this might be better suited as INFO

**Comment by aaronki** [comment]
Fixed in PR #400
