### ISSUE TITLE
Remove filelock

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#394]
At the moment we use a soft filelock to make sure two SMACs sharing a directory do not read/write at the same time. This might cause one SMAC to wait infinitely long or other race conditions.

We would prefer to solve this via ``mv``, so SMAC should first write to a temporary file and then mv that to the final destination. See also comments in: https://github.com/automl/SMAC3/pull/391

**Comment by mfeurer** [comment]
Also, we need to document how synchronization works.
