### ISSUE TITLE
Setup static code checkers

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#395]
Which run on travis-ci, otherwise we're constantly having issues with code checking platforms. This should prevent issues like #388.

**Comment by KEggensperger** [comment]
MYPY is triggered with on travis-ci.
Also fixed #86

**Comment by mfeurer** [comment]
I added flake8 in #525

**Comment by mfeurer** [comment]
We have mypy and flake8 up and running. Do we want anything else, maybe black (https://github.com/psf/black):

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters. Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead. Black makes code review faster by producing the smallest diffs possible.

**Comment by mfeurer** [comment]
Closing this as there wasn't any answer.
