### ISSUE TITLE
Remove objective

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#398]
Currently, we're only using the function `average_cost` from the module [objective](https://github.com/automl/SMAC3/blob/master/smac/optimizer/objective.py). The objective function is an argument to the `RunHistory`. Since we're only using `average_cost`, I propose to drop this to make the interface of `RunHistory` easier.

**Comment by mlindauer** [comment]
I'm still hesitant to agree to this proposal. There are use cases in which average is not the correct aggregation. Nevertheless, the code assumes "average" for aggregation right now and would break if we would change it.
