### ISSUE TITLE
Constraint in Search Space

### ISSUE THREAD

**Issue by vivekaxl** [automl/SMAC3#403]
Similar to #299 

I am trying to optimize through a space of options where the valid configurations are sparse. Does SMAC3 support such operations? I couldn't find an example---could you please point me to the file?

**Comment by mlindauer** [comment]
Dear Vivek,

Unfortunately, SMAC does not handle such search spaces well if the constraints are unknown. The underlying model will try to learn the valid/invalid parts of the search space; but preliminary experiments showed that SMAC fails to do it efficiently. 
Implementing a more efficient approach for highly constrained search spaces is on our todo list for our next hackathon in April. 

Last but not least, please note that SMAC supports conditional constraints very efficiently and in our experience, this is often sufficient for constraints that are known to users.
For more details, please look into our documentation of the **old** SMAC implementation:
http://www.cs.ubc.ca/labs/beta/Projects/SMAC/v2.10.03/manual.pdf
--> 4.4 Parameter Configuration Space Format

Best,
Marius

**Comment by vivekaxl** [comment]
Thank you, Marius. 

I looked at the documentation (Section 4.4) and saw that I could specify forbidden parameter clauses. In my current scenario, it is easier to define the valid parameters rather than forbidden ones (# of valid parameters << # of invalid parameters). Is there a way I can pass this information?

**Comment by mlindauer** [comment]
Unfortunately, I think the answer is no.
But could you please give us an example how you would like pass this information?

**Comment by vivekaxl** [comment]
Most of my experiments involve explicitly defining the configuration space (which is a CSV format) since more often than not the dependency between the parameters are not known. I was wondering if there was a way to encode the csv file in the ConfigSpace data structure. Any ideas how that can be done?

**Comment by mlindauer** [comment]
So, you can enumerate all possible configurations?
That's quite unusual in our experiments, but we have also thought about whether it would make sense to have such a feature in our configspace for some special cases; @mfeurer considered to implement it at some point. 
If would have such an enumerated configuration space, it should fairly easy to also read in an already enumerated configspace. 
I will talk with @mfeurer about this; however, most likely this feature will not be implemented in the near future---maybe within the next 6 months.

**Comment by aryandeshwal** [comment]
I have a similar situation where I know the constraints for input parameters. I have a sequence of 0/1 values as input configuration and the constraint is that the sequence when expanded into a matrix form should be a graph. Is it possible to use the forbidden clause over a function of the input? What I mean is something of the form "Forbidden (is_graph(x), False)" where is_graph(x) is a function of input configuration? Thank you!

**Comment by mlindauer** [comment]
Our forbidden constraints allow to define simple constraints in the configuration space. However, we strongly recommend to avoid such forbidden constraints because SMAC does not implement a constraint solver and thus it gets quite hard to sample from a constraint space.

**Comment by aryandeshwal** [comment]
Thank you for the response!

**Comment by alexandertornede** [comment]
Closed as this is continued in #884 .
