### ISSUE TITLE
"hot start" with previous data

### ISSUE THREAD

**Issue by vlavorini** [automl/SMAC3#404]
Hello,

    it will be useful to load previous calculations for new rounds of optimization.
So, if I already ran SMAC, and have the history recorded on disk, add the possibility of using that saved data for new optimization rounds.

Thank you!

**Comment by mlindauer** [comment]
Hi,

Sorry for the late reply. Somehow I missed that you issued this issue.
Could you please provide more details of what you want.

We have already an option to resume SMAC runs (also with increased budgets):
https://automl.github.io/SMAC3/stable/basic_usage.html#restoring-states

Furthermore, we have a paper on warmstarting SMAC on other scenarios:
https://arxiv.org/abs/1709.04636
Unfortunately, one of our student assistants jumped off and we are lacking the manpower right now to port this feature into the master branch.

Cheers,
Marius
