### ISSUE TITLE
Could not make output directory 

### ISSUE THREAD

**Issue by chenhuims** [automl/SMAC3#405]
Hello, I'm trying to run through the rosenbrock_2d example provided here (https://github.com/automl/SMAC3/blob/master/examples/rosenbrock.py). But I get the following error
OSError: Could not make output directory: smac3-output_2018-04-09_21:43:45_268877/run_1.
Btw, the SMAC3 package is installed on the header node of a Spark cluster. Any thoughts about how to debug this issue? 
Thank you in advance!

**Comment by mlindauer** [comment]
Hi,

Thanks for reporting this issue.
Could you please provide more details?

 * Have you checked that you have write permissions in the folder where you executed SMAC?
 * We use a simple `os.makedirs()`. Could you please try to run it manually?
 * Do you start SMAC several times in parallel at the same time with the same random seed? In theory, there is a small chance (race condition) that two SMAC processes will try to create the same directory at the same time which could raise this error. If that's the case, I would recommend to use different seeds for each SMAC run.

Best,
Marius

**Comment by chenhuims** [comment]
Hi Marius,
To provide a bit more information, I'm able to run `os.makedirs()` on the Spark cluster. Besides, I only run SMAC once at a time.

**Comment by mlindauer** [comment]
Hi,

We changed the error handling for this exception.
Please try our current dev branch.

Cheers,
Marius

**Comment by alexandertornede** [comment]
Since the output directory is now called smac3_output, this should not be an issue anymore.
