### ISSUE TITLE
How to tell if pSMAC running?

### ISSUE THREAD

**Issue by bsesar** [automl/SMAC3#430]
Dear smac3 team members,

I am not certain that I am running pSMAC in parallel mode and would like to hear your opinion if I am doing something wrong.

Here is my Python code for SMAC:

`scenario = Scenario({"run_obj": "quality",
                     "runcount-limit": 600,
                     "cs": cs,
                     "deterministic": "true",
                     "shared_model": True,
                     "output_dir": "/home/cdsw/runs",
                     "input_psmac_dirs": "/home/cdsw/runs*"                     
                    })

smac = SMAC(scenario=scenario, tae_runner=calculate_rmse, rng=np.random.RandomState(), run_id=runID)`

I run the above code on 4 machines, where each machine has its own runID. I've checked the /home/cdsw/runs folder, and indeed, there are 4 folders: run_1, run_2, run_3, and run_4.

My expectation is that, when one run finds a better parameter set, all of the other runs become aware of that better parameter set. However, when a run finds a better solution, how can I tell that the solution was propagated to other runs?

Also, if I add additional runs (e.g., run_5, run_6, etc.) once the first four runs are finished, will these new runs use the information stored in the previous runs?

Cheers,

Brani

P.S.

I increased the logging verbosity to DEBUG, and got this message (among many others):

`DEBUG:smac.optimizer.smbo.SMBO:Shared model mode: Finished loading new runs, found 0 new runs.`

Why is SMAC not finding other runs?

**Comment by mlindauer** [comment]
Dear Branimir,

I would expect that your output directory structure looks like:

```
runs
└── run_1
└── run_2
└── run_3
...
```

Right?
So, you would need to set `input_psmac_dirs` to `runs/run*`

> My expectation is that, when one run finds a better parameter set, all of the other runs become aware of that better parameter set.

That's not quite correct. All other runs will be aware of all evaluated parameter sets (configurations). However, to ensure diversity in the search process, the runs are not aware of the best parameter set of the other runs.

> Also, if I add additional runs (e.g., run_5, run_6, etc.) once the first four runs are finished, will these new runs use the information stored in the previous runs?

Yes. However, the search starts again with the default configuration.

Best,
Marius

**Comment by bsesar** [comment]
Thanks, Marius :) I've changed the `input_psmac_dirs` variable as you suggested and the debug log now reports loading of all runs.

Just to make it clear to future users, perhaps the  [pSMAC manual](https://automl.github.io/SMAC3/stable/psmac.html) could be updated with a more specific example? Something like
`
scenario = Scenario({...
                "shared_model": True,
                "input_psmac_dirs": "smac3-output*/run_*"
                })
`

**Comment by mlindauer** [comment]
Hi,

Thanks for the feedback.
In fact, I will change the interface because I think the way how you wanted to use it is more intuitive. 

Cheers,
Marius
