### ISSUE TITLE
Any chance of a Windows version?

### ISSUE THREAD

**Issue by MotoRZR** [automl/SMAC3#435]
Currently unable to run Linux in our corporate environment.  A windows version would be helpful!

**Comment by mfeurer** [comment]
Some users had success running SMAC in the Linux/BASH subsystem on Windows 10 (https://github.com/automl/auto-sklearn/issues/431).

**Comment by MotoRZR** [comment]
Thanks.  The issue is that we have one of those large corporate IT policies that force us to use Windows.  We are larger financial institution.  We are currently also on Windows 7.  WSL would not be allowed.  You mention Linux subsystem and their heads would explode.  Unfortunately.

**Comment by mlindauer** [comment]
Hi,

Sorry, we are a poor research group that has not enough manpower to support platforms other than Linux. We are happy to accept pull requests to fix this.

Best,
Marius Lindauer
