### ISSUE TITLE
Running smac over a distributed compute cluster

### ISSUE THREAD

**Issue by Mestalbet** [automl/SMAC3#444]
Hi,

I am trying to use psmac over a Dask cluster.  I define my scenario like this:

 scenario = Scenario({"run_obj": "quality",  
                      "runcount-limit": 50,  
                      "cs": cs,              
                      "deterministic": True,
                      "shared_model": True, 
                      "input_psmac_dirs": "/shared_data/smac_runs/run*",
                      "output_dir": "/shared_data/smac_runs/"})

I then submit smac.optimize to each worker. 

I get the error: daemonic processes are not allowed to have children. 

Any suggestions?

Cheers,
Noah

**Comment by mlindauer** [comment]
Sorry, we have no experiences with Dask clusters.

Maybe our pynisher tool (for limiting the compute resources for the target function call) could be the issue. So, you could try to deactivate it if you pass the argument `use_pynisher=False` to your `ExecuteTAFuncDict()`

Cheers,
Marius

**Comment by Mestalbet** [comment]
Hi, 

Thanks for your response. I run Smac using the instructions in your Quickstart guide. There are three steps:
1 - Create a configuration
2 - Create a scenario
3 - Create a smac object

1)
cs = ConfigurationSpace()
2) 
scenario = Scenario({...})
3)
smac = SMAC(...)

and then call optimize. 

Where are you suggesting adding the use_pynisher=False flag to this process? I tried all three to no avail. 

Cheers,
Noah

**Comment by Mestalbet** [comment]
Thanks, I'll give it a try and report back.

**Comment by Mestalbet** [comment]
Hi,

I figured out that it needs to be run as  follows:
```python
cs = ConfigurationSpace()
scenario = Scenario({...})
def errortomimize:
  return( trainmodel( **cfg), use_pynisher = False))
tae = ExecuteTAFuncDict(errortomimize,use_pynisher=False)
smac = SMAC(scenario=scenario, rng=np.random.RandomState(i), tae_runner=tae)
```
I'll report back how it works out - distributing SMAC opens up a really huge opportunity for big improvements. You can search a much larger space. 

Cheers,
Noah

**Comment by Mestalbet** [comment]
Hi,

So we're on our way but I have run into another problem specifying the output and input directories for pSMAC. 

I get the message ```No such file or directory: '/shared_data/smac_runs/run_1/Scenario.txt``` even though I see that the file exists. 

Any ideas?

Cheers,
Noah

**Comment by mlindauer** [comment]
I assume that this issue is solved. If not, please re-open.
