### ISSUE TITLE
getting final result from pSMAC on a distributed compute cluster

### ISSUE THREAD

**Issue by Mestalbet** [automl/SMAC3#446]
Hi,

I have managed to run pSMAC on a distributed DASK cluster. I run it as follows:
```python
cs = ConfigurationSpace()
scenario = Scenario({"run_obj": "quality",  
                         "runcount-limit": 50,  
                         "cs": cs,              
                         "deterministic": True,
                         "shared_model": True, "initial_incumbent": 'RANDOM',
                         "output_dir": "/shared_data/smac3-output/runs/",
                         "input_psmac_dirs": "/shared_data/smac3-output/runs/run_*"})

def errortomimize:
  return( trainmodel( **cfg), use_pynisher = False))
tae = ExecuteTAFuncDict(errortomimize,use_pynisher=False)
smac = SMAC(scenario=scenario, rng=np.random.RandomState(i), tae_runner=tae, run_id = i)
```
_where i in this case is the worker number._

This creates a directory structure in the shared space like the following:
```
----smac3-output/runs
                                |
                                |_______run_1
                                |_______run_2
                                             . . .
                                |_______run_N
```
_where N is the number of workers in the cluster._

However, if you look at the traj_aclib2.json in each run_* subdirectory, they are identical.  I tried adding ```verbose_level = "DEBUG" ``` to ```errortomimize``` but I don't get any output from this. 

Any idea what the problem is? How can I tell whether pSMAC is actually sharing the model (as opposed to just running the same thing _N_ times)? 

Cheers,
Noah

**Comment by mlindauer** [comment]
As the first lines of your script, you should add:

```import logging
logging.basicConfig(level=logging.DEBUG)
```
Afterwards you should see lines such as:
```DEBUG:smac.optimizer.smbo.SMBO:Shared model mode: Loaded 5 new runs from ...```

**Comment by Mestalbet** [comment]
Hi,

Thanks!! So I managed to get the logs thanks to your advice. The model runs on all nodes but the returned incumbent has a configuration for each node. 

![image](https://user-images.githubusercontent.com/4837338/42304119-56d0ef60-802d-11e8-857e-75dbc09affb9.png)

**Comment by mlindauer** [comment]
Yes, the parallel SMAC runs do not coordinate which configuration is considered as the incumbent (i.e., the currently best known configuration) and thus, each run will return its own incumbent.

**Comment by Mestalbet** [comment]
Hi,

Thanks. I managed to see the output.  It looks like it's working correctly - how do I return the final incumbent values after a distributed run? I can see the values in the log...

Thanks again,
Noah

**Comment by mlindauer** [comment]
You can use `smac.get_runhistory()` to get a handle on the runhistory (i.e., all evaluated target algorithm runs). 
`runhistory.get_cost(incumbent)` returns the estimated empirical cost.

**Comment by Mestalbet** [comment]
Hi,

Thanks! Awesome. In the distributed mode, I get multiple smac objects - since there was one created  on each worker. So I am not sure how to implement your suggestion. 

Cheers,
Noah

**Comment by Mestalbet** [comment]
They all have access to their own SMAC object -that's my point. Each one writes to a run_<run_id> directory which is also accessed through input_psmac_dirs variable.

**Comment by mlindauer** [comment]
Sorry, I don't understand your problem.
Each SMAC object returns its own incumbent configuration.
You only have to decide which of these to use in the end.
One simple way is to ask each SMAC object how it estimates the empirical cost of its incumbent configuration and you simply choose the best one.

**Comment by Mestalbet** [comment]
Okay, I understand now. I have to figure out how to get the intermediate result (the smac object) from the computational graph.  The issue is optimizing the distributed computation (the final result is a list of incumbents not the smac objects).  Of course, it's trivial to get the smac objects but non-trivial (for me anyway) to optimize the computation then. 

I'll post the solution here when I have it so it helps other people wanting to run SMAC in a distributed computation setting. 

Thanks.

**Comment by brenting** [comment]
@Mestalbet 
I was having the same problem. If you run pSMAC on a cluster using the command line (which I assume you did), you are using the SMACCLI object. This object creates the SMAC object within the smac package, which is only accessible when you modify the package.

You can also rebuild the entire runhistory afterward and use that to predict the cost of every final incumbent of the parallel pools. I'll explain below with commented code.

```python
import os
import glob
import logging

from smac.optimizer import pSMAC
from smac.scenario.scenario import Scenario
from smac.runhistory.runhistory import RunHistory
from smac.utils.io.traj_logging import TrajLogger

# get a list of all the directories with smac logs
pool_dirs = glob.glob(<smac_dir>/run_*)

# initiate runhistory object
runhistory = RunHistory(aggregate_func=None)

# get configuration space via scenario. 
# You need just 1 scenario file for the config_space as it does not differ per pool.
# I just select the one in the first folder
scen_file = os.path.join(pool_dirs[0], 'scenario.txt')
config_space = Scenario(scen_file).cs

# construct history using parallel smac logs
# Here you load the entire run history into the object 'runhistory' that is included
pSMAC.read(runhistory, pool_dirs, config_space, logging.getLogger())

for pool_dir in pool_dirs:
    # get the file name of the trajectory jason file in this pool
    traj_path = os.path.join(pool_dir, 'traj_aclib2.json')

    # read the trajectory
    trajectory = TrajLogger.read_traj_aclib_format(fn=traj_path, cs=config_space)

    # get the last incumbent of the trajectory in this pool
    last_incumbent = trajectory[-1]['incumbent']

    # get the estimated cost of the incumbent using the runhistory of ALL pools
    est_cost = runhistory.get_cost(last_incumbent)

    # you can now use 'est_cost' and 'last_incumbent' to your liking. 
    # however, 'last_incumbent' is a ConfigSpace object. To convert to dictionary, see below
    last_incumbent_dict = last_incumbent.get_dictionary()
```

@mlindauer 
What I do notice is that earlier incumbents sometimes have a lower estimated cost. Should I check all incumbents that are logged instead of only the last one, or is there an explanation for that?

**Comment by brenting** [comment]
I do indeed use instances for SMAC, so I have probably been doing it wrong then.

Can I then conclude to following?:
Within a single worker, the cost of the SMAC incumbent can be estimated by using its own run history only. This estimated cost can then be used to compare it against incumbents of other workers.

**Comment by mlindauer** [comment]
In general, you should only compare the final incumbents against each other. You can do it based on the performance estimate of the runhistory if each worker looked at a representative set of instances for the final incumbent (i.e., the instance subset is not too small).
You could also try to fit an EPM model on the runhistories from all workers and use the predictions from the EPM to compare incumbents. However, that approach requires that you have good instance features.
