### ISSUE TITLE
psmac does not work

### ISSUE THREAD

**Issue by fayeshine** [automl/SMAC3#448]
DEBUG:smac.optimizer.smbo.SMBO:Shared model mode: Finished loading new runs, found 0 new runs.
I run 3 instances at the same time, but each turn there's no new runs

**Comment by musamarcusso** [comment]
I have seen the same thing happening, but still haven't figure out how to solve it.

**Comment by musamarcusso** [comment]
> "input_psmac_dirs": 'smac3-output*/run_1'
> 
> it seems that I add "/run_1" in "input_psmac_dirs", then it can found other instances
> maybe the documentation should be updated

Or `smac3-output*/run_*` in case you happen to using different seeds?
