### ISSUE TITLE
Add function target value as termination criterion

### ISSUE THREAD

**Issue by guoxin1122** [automl/SMAC3#450]
Hi,
I was trying to add a termination criterion for SMAC, say function target value (ftarget=fopt+precision), but I kind of lost in so many modules. Could you just give me any instruction to do that? Thanks for your help in advance.

**Comment by mlindauer** [comment]
Hi,

There is a main loop in the `smac.optimizer.smbo` `run` method. This controls the termination:
https://github.com/automl/SMAC3/blob/master/smac/optimizer/smbo.py#L203

**Comment by guoxin1122** [comment]
Thank you so much! It works now.

Best regards,
Xin Guo

On 18 Aug 2018, at 11:41, Marius Lindauer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

There is a main loop in the smac.optimizer.smbo run method. This controls the termination:
https://github.com/automl/SMAC3/blob/master/smac/optimizer/smbo.py#L203
