### ISSUE TITLE
SMAC3 warm staring

### ISSUE THREAD

**Issue by asheracuk** [automl/SMAC3#452]
If I already have a file runhistory.json, how can I use it to warm start SMAC? 

When I added argument "runhistory = "./runhistory.jason"" to SMAC, it fails. But I don't know how to correctly use it.

Really needs help!

**Comment by mlindauer** [comment]
Hi @asheracuk 

Would you like to warmstart SMAC or do you want to continue an existing run of SMAC?
For me, warmstarting refers to apply SMAC to the same target algorithm but a different instance set.

For continuing an existing run, you can find the docu here: https://automl.github.io/SMAC3/stable/basic_usage.html#restorestate

The warmstarting feature is only partially implemented in the development branch. 

Best, 
Marius

**Comment by mlindauer** [comment]
Hi,

That option is right now not implemented in the master branch. Furthermore, the argument `runhistory2epm` is not meant for warmstarting but to pass an object which can transform runhistories to EPM data.

We have an experimental version of warmstarting implemented in the development branch. The option is called `warmstart-runhistory`. However, I would advise against using the dev branch at the moment.

Best,
Marius
