### ISSUE TITLE
What does 'instance' mean in source code?

### ISSUE THREAD

**Issue by usafchn** [automl/SMAC3#454]
When I read SMAC3 source code, I saw word 'instance' appear in many place, but I can't understand what is a 'instance' and what does 'instance' stand for? 

for example, in file smac/epm/rf_with_instances.py:
```
    def _train(self, X: np.ndarray, y: np.ndarray, **kwargs):
        """Trains the random forest on X and y.

        Parameters
        ----------
        X : np.ndarray [n_samples, n_features (config + instance features)]
            Input data points.
        Y : np.ndarray [n_samples, ]
            The corresponding target values.

        Returns
        -------
        self
```

what is "instance features"?

**Comment by mlindauer** [comment]
Hi Lu,

We call inputs to the target algorithm "instances". For example, a dataset as an input to a machine learning algorithm could be an instance; or a concrete instance of a planning problem for an AI planning solver could be an instance. Instances are relevant if you want to find a configuration that performs well across the given instances / inputs.
If you want to know more about instances, I would recommend the following paper:
https://ml.informatik.uni-freiburg.de/papers/09-JAIR-ParamILS.pdf

Best regards,
Marius

**Comment by usafchn** [comment]
Thanks, @Marius, There is another question: if the input dataset is an instance, what does 'multiple instances' stand for ?  I listed two guesses below, which one is correct ?
1. The original input dataset can be split into different subsets, each one is an instance 
2. One machine learning algorithm could run on different datasets and you treat every dataset as an instance.

**Comment by mlindauer** [comment]
Hi,

That depends what you want. In principle, both are possible; however, the first one is the common approach.

Best,
Marius

**Comment by usafchn** [comment]
Thank you, I see.

**Comment by mlindauer** [comment]
You are welcome.
