### ISSUE TITLE
optimize a high-dim continuous function on a finite grid

### ISSUE THREAD

**Issue by daidaixiong** [automl/SMAC3#473]
I'm trying to optimize a high dimensional (100+) continuous function, but only on a finite grid (about 20000 points), does SMAC support that? Thanks

**Comment by mlindauer** [comment]
You could try to define your search space as 100+ ordinal parameters and let SMAC optimize that. In principle that should work, but we never tried so far.

**Comment by mlindauer** [comment]
I will close this issue for now. If there are further questions related to this use case, please feel free to open the issue again.
