### ISSUE TITLE
The API is hard to use and poorly documented

### ISSUE THREAD

**Issue by KOLANICH** [automl/SMAC3#475]
#### Description
* I don't understand the logic and have to reverse-engineer it from the source. I understand how to create a space spec, but what I miss, is constructing optimizer object from building blocks. Could you create the docs guiding me through initializing and using the optimizer, explaining input and output of each step?

* classes for different components of optimization are scattered across different modules, which leads to ugly code, like
```python
		if isinstance(acquisitionOptimizerType, str):
			import importlib
			optModName = "smac.optimizer." + acquisitionType.__name__.lower() + "_optimization"
			optMod = importlib.import_module(optModName)
			acquisitionOptimizerType = getattr(optMod, acquisitionOptimizerType)
		self.acquisitionOptimizerType = acquisitionOptimizerType
```
* hardcode like
```python
                model = GaussianProcess(
                    types=types,
                    bounds=bounds,
                    kernel=kernel,
                    prior=prior,
                    rng=rng,
                    normalize_output=True,
                    normalize_input=True,
                )
            elif model_type == "gp_mcmc":
                model = GaussianProcessMCMC(
```

leads to confusion: I don't want to repeat this elif ladder in my code.

* one wanting to use this is burdened with low-level details, unless uses some very high level facade, like `f_min`, which is too highlevel disallowing much control. The API is heeded to be kept out burdening with low-level details, but should give enough control.

For example in order to select an acquisition function I have to pass it an already constructed model, and to construct a model I need 

```python
types, bounds = get_types(scenario.cs, scenario.feature_array)
```

which is too low-level detail. Why do I have to pack them there and then extract them out of it?

Why do I have to recreate it in own code?

I mean I shouldn't have to create lots of objects myself and import lots of modules, but the essential knobs like acquisition function or its optimizer should be available and they should be universal and should require no per-model and per-aquisition function tuning.

#### Expected Results
So the proposed way to fix it:
0. Write a good docs.
1. accept only classes names as strings;
2. consolidate all the classes serving the same purpose (acqusition functions, their optimizers, etc) in dedicated modules and make these modules iterable;
3. If a user passes a string, get the stuff from the corresponding module using getattr;
4. make all the optimizer API uniform enough, moving model-specific params into kwargs, provide sensible default values.
5. make a hierarchy of facades

**Comment by mlindauer** [comment]
Thank you for your feedback. In general, we agree with most of your concerns. Unfortunately, it is very unlikely that we will completely refactor SMAC in the near future. Therefore, I will close this issue for now.
