### ISSUE TITLE
Implement NormalIntegerHyperparameter, NormalFloatHyperparameter and other distributions

### ISSUE THREAD

**Issue by KOLANICH** [automl/SMAC3#476]
Efficiently. I already [have an inefficient implementation](https://gitlab.com/KOLANICH/UniOpt.py/blob/master/UniOpt/core/Spec.py#L159), feel free to reuse it, but it is damn inefficient (probes the same points multiple times).

**Comment by mlindauer** [comment]
Dear @KOLANICH ,

Thank you for this proposal. It is also on our agenda for quite some time, but we have not implemented it so far. 

Since this feature request does not belong to our SMAC package but to our configspace (https://github.com/automl/ConfigSpace), I will close this ticket here.

**Comment by KOLANICH** [comment]
>Since this feature request does not belong to our SMAC package, but to our configspace .

They seem to be already implemented there (at least Normal), aren't they? It is SMAC which doesn't support them.

**Comment by mlindauer** [comment]
@mfeurer could you please reply to it.

**Comment by mfeurer** [comment]
@KOLANICH is correct, they are implemented in the ConfigSpace package but not in the SMAC package.

**Comment by mlindauer** [comment]
@mfeurer could you please remind of the reason why it is not implemented in SMAC?

**Comment by mfeurer** [comment]
* It is not implemented in the original SMAC package and not compatible with the pcs format.
* So far no one was interested in it.

I'd be happy to review pull requests on this, though.

**Comment by mlindauer** [comment]
@KOLANICH we will consider this request for our next SMAC release.

**Comment by renesass** [comment]
Since we drop the pcs format in v2.0 we could integrate this feature too.
What do you think @mfeurer?

**Comment by mfeurer** [comment]
That sounds reasonable. Similarly, the beta-distributed hyperparameters could be used.

**Comment by KOLANICH** [comment]
Thanks to everyone who was involved in implementing this :+1:. I cannot test it right now because I'm a bit occupied with other urgent work, so no ETA when the SMAC3 backend for UniOpt is ready.
