### ISSUE TITLE
Write scenario with json-pcs-path as default (and read json's at all?)

### ISSUE THREAD

**Issue by shukon** [automl/SMAC3#478]
Currently, the ConfigSpace is written in `.pcs` and `.json` formats when [writing a scenario,](https://github.com/automl/SMAC3/blob/7f15a59e8851157d2a8b0647cc9d3b184c60e894/smac/utils/io/output_writer.py#L91-L98) but the path that is written to the scenario-file is the `.pcs`-one. Since the pcs-format is not fully compatible with configspace (not [recoverable for Constants](https://github.com/automl/ConfigSpace/blob/9fac2c03fbf7ac5d8b3575de96cd58e4f6c2f12e/ConfigSpace/read_and_write/pcs_new.py#L94) and certain [type-choices](https://github.com/automl/ConfigSpace/issues/100)), I propose to have the json-file be the one that is written in the scenario as the `pcs_fn`-argument.

What needs to happen to achieve that?
- [x] always have the json-format-configspace be the one that is written as the `pcs_fn` in the output_writer
- [x] I actually think we are currently [only reading in pcs-format](https://github.com/automl/SMAC3/blob/7f15a59e8851157d2a8b0647cc9d3b184c60e894/smac/utils/io/cmd_reader.py#L138-L142)!
- [x] add tests

**Comment by mlindauer** [comment]
agreed!

**Comment by shukon** [comment]
Fixed with #482
