### ISSUE TITLE
Dev-versioning

### ISSUE THREAD

**Issue by shukon** [automl/SMAC3#479]
Could we use a `dev` suffix in the version of SMAC so we can distinguish installations from master from pip-installations? Makes remote-debugging a lot easier, since `pip freeze` will result in more accurate versioning-report...
Example on non-release commits in __version__.py:
`__version__ = "0.9.0"` -> `__version__ = "0.9.0_dev"`

**Comment by mlindauer** [comment]
Good idea. Agreed.

**Comment by shukon** [comment]
Actually, I think it's common to use the next version + a suffix? So `0.9.1.dev`? Or maybe not? We have it that way in some other modules and I've seen it around, but not sure. If we use `0.9.0.dev` then I will change it in other modules accordingly... ?

**Comment by KEggensperger** [comment]
Yes, you are right, I assume it should be 0.9.1.dev? 
Unfortunately, I just merged the other version string, but I will fix that :-)

**Comment by mlindauer** [comment]
@KEggensperger please without a PR ;-)

**Comment by KEggensperger** [comment]
Yes, sure. I think, it should even be 0.10.dev

**Comment by shukon** [comment]
Ok, then I'll leave the other modules as they are (or maybe turn the `_dev` into a `.dev`). Thank you!
