### ISSUE TITLE
Automatically set stats object in TAE when passing it to SMAC

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#48]
Would make this code easier:
```
stats = Stats()
SMBO(tae_runner=ExecuteTAFunc(lambda: 1, stats=stats),
     scenario=self.scenario,
     stats=stats)
```

**Comment by mlindauer** [comment]
sorry, I don't get what you want here.

**Comment by mfeurer** [comment]
I need to create a stats object and pass it to the TAE and the SMBO object. Instead, it would be great if the SMBO object could inject the stats object it creates into the TAE. Is there any use case where the user wants to create the stats object?

**Comment by mlindauer** [comment]
right now, the stats argument of smbo is optional. if not set, smbo will generate a stats object. 

If the argument of the tae is not given, smbo will generate a tae object and will pass the stats object to the tae. 

So, you would like to keep both arguments, but smbo should always update the stats object in the tae?

**Comment by mfeurer** [comment]
Sorry, I wasn't clear about what I propose. I propose to remove both stats arguments, and add a private function to the TAE which is called by SMBO and injects the stats. The SMBO object creates a stats object. I currently don't see a reason why a user wants to provide a custom stats object.

**Comment by mlindauer** [comment]
I agree that the SMBO object could inject the stats object to the TAE.
However, why should this a private method? By definition, I would expect that a private method cannot be called by another object.

Please create a PR and we can discuss the details. OK?

**Comment by mfeurer** [comment]
Okay, will do so once #47 is merged.

**Comment by mfeurer** [comment]
Would be covered by #55

**Comment by mfeurer** [comment]
I'll check that again on Tuesday.

**Comment by mfeurer** [comment]
Covered by #55, now also tested. I'm closing this now.
