### ISSUE TITLE
About working on Windows.

### ISSUE THREAD

**Issue by nobodyczcz** [automl/SMAC3#483]
Hi,

We are working on bringing parameter tunning module to Minizinc. As Minizinc support both windows and linux, we need the tunning module also work on both. Thus we want to edit the source code of SMAC to make it work on windows. Do you have any suggestions about which part need to change?

Thank you

**Comment by mlindauer** [comment]
Hi,

I hope that SMAC itself should work on windows systems; however, some of its dependencies might be incompatible with Windows (but actually, I don't know all the details). You should try to check the following packages:

* pyrfr package (https://github.com/automl/random_forest_run)
* pynisher (https://github.com/sfalkner/pynisher)

If you are able to run SMAC on Windows, please let us know how you did it.

Cheers,
Marius

**Comment by mlindauer** [comment]
I will close this issue for now. If someone has updates on that, please let us know.
