### ISSUE TITLE
Allow passing target algorithm directly to SMAC

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#49]
instead of wrapping it into a class manually. What do you think?

**Comment by KEggensperger** [comment]
Sounds good, but it should still be possible to also use the way it is implemented now.

**Comment by mlindauer** [comment]
as the last issue, I don't get what you actually want.

**Comment by KEggensperger** [comment]
I guess what @mfeurer means is that 
 (from https://github.com/automl/SMAC3/blob/master/examples/rf.py#L124)
```
# register function to be optimize
taf = ExecuteTAFunc(rfr, stats=stats)

# Optimize
smbo = SMBO(scenario=scenario, rng=np.random.RandomState(42),
tae_runner=taf, stats=stats)
```

could be reduced to:

```
# Optimize
smbo = SMBO(scenario=scenario, rng=np.random.RandomState(42),
tae_runner=rfr, stats=stats)
```

**Comment by mfeurer** [comment]
Yes, thanks.

**Comment by mlindauer** [comment]
agreed. sounds reasonable.

**Comment by mfeurer** [comment]
Would be covered by #55
