### ISSUE TITLE
Is sphinx really a dependency of this stuff?

### ISSUE THREAD

**Issue by KOLANICH** [automl/SMAC3#512]
#### Description
When I install thks lib, for example mention it in package dependencies, it also install sphinks and bunch of its dependencies. They are unneeded.

#### Expected Results
Sphinx is needed for building docs only, so it is completely unneeded for everyone who is not going to build the docs. It should be removed from the dependencies.

#### Actual Results
It is present there.

**Comment by mfeurer** [comment]
Fixed via #567. Will be available in the next release.

**Comment by KOLANICH** [comment]
Thanks.
