### ISSUE TITLE
problems with predict_marginalized_over_instances

### ISSUE THREAD

**Issue by ndangtt** [automl/SMAC3#518]
Hello,

I've got an issue when running a [PyImp](https://github.com/automl/ParameterImportance) example. After looking at the code, it seems to me that it might be caused by a potential bug in the current SMAC code (version `0.10.0`). In particular, in [this file](https://github.com/automl/SMAC3/blob/master/smac/epm/base_epm.py), function `predict_marginalized_over_instances`, the following two lines:
```
if X.shape[1] != len(self.types):
    raise ValueError('Rows in X should have %d entries but have %d!' % (len(self.types), X.shape[1])) 
```
As `X` contains only algorithm parameters, while `self.types` contains both algorithm parameters and instance features, this `if` clause will fail.

The full decsription of the issue in PyImp repo is [here](https://github.com/automl/ParameterImportance/issues/105).

Could you please help to have a look?

Thank you!
Nguyen

**Comment by mlindauer** [comment]
@mfeurer could you please look into it. from the last commit it looks like you added that check there and actually, I also don't know whether it is correct.

**Comment by mfeurer** [comment]
Indeed, that's a bug. We already fixed this in the development version (https://github.com/automl/SMAC3/blob/development/smac/epm/base_epm.py) and the next release will make this go away. For now, you could simply disable that check to make it work.
