### ISSUE TITLE
Make run_obj a mandatory argument

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#52]
I think we should make arguments where users can really screw up the setting mandatory. One example is run_obj, which can make the algorithm behave totally wrong for a scenario. By making a few important choices required, we lower the chance of accidental misconfiguration.

**Comment by mfeurer** [comment]
And, if the run objective is runtime, cutoff should be a mandatory argument as well (if not given, SMAC crashes).

**Comment by mfeurer** [comment]
@mlindauer what's your opinion on this?

**Comment by mlindauer** [comment]
I agree that cutoff should be mandatory if it is a running time scenario.

I'm undecided whether run_obj should be mandatory. I see your point.
However in my experience, it is very crucial for new users to have a very low initial hurdle for the first use. With more required arguments, it gets a lot more complex for new users which could prevent  them to try SMAC.

**Comment by mlindauer** [comment]
Ok, we voted for making "run_obj" as a mandatory field.

@shukon could you please create a PR to resolve this issue and change it the docu accordingly
