### ISSUE TITLE
Running pSMAC on Python

### ISSUE THREAD

**Issue by sergio-verduzco** [automl/SMAC3#520]
#### Description
I have modified the SVN example in https://automl.github.io/SMAC3/master/quickstart.html#svm-example so it can run with the PSMAC module rather than SMAC, using the code I show below.

At this point, the output writer of the Scenario object threw an error which I tracked to line 121 of the file `smac/utils/io/output_writer.py`, where the `" ".join(value)` instruction is attempted when `value` is the function I am optimizing. I "fixed" this as described below, but being an SMAC newbie, I get the impression this might not be quite right. Moreover, I haven't been able to figure out how to configure my instances in Python...

#### Steps/Code to Reproduce
Here I'll describe a modifed version of your SVN example.

```
# Import ConfigSpace and different types of parameters
from smac.configspace import ConfigurationSpace
from ConfigSpace.hyperparameters import CategoricalHyperparameter, \
    UniformFloatHyperparameter, UniformIntegerHyperparameter
from ConfigSpace.conditions import InCondition

# Import SMAC-utilities
from smac.tae.execute_func import ExecuteTAFuncDict
from smac.configspace import Configuration
from smac.scenario.scenario import Scenario
from smac.facade.psmac_facade import PSMAC
import numpy as np
```
So far the only important difference is that I replaced SMAC with PSMAC. Next I create an arbitrary configuration space and scenario, along with a function to evaluate a given configuration.
```
cs = ConfigurationSpace()
mu = UniformFloatHyperparameter("mu", 0.1, 4.0, default_value=0.5)
cs.add_hyperparameters([mu])

def eval_config(cfg):
    """ Returns the error for a network with a given configuration.
 
        Args:
            cfg : a configuration dictionary.
        Returns:
            error : A random float.
    """   
    return np.random.random() + cfg['mu']

scenario = Scenario({"run_obj": "quality",   # we optimize quality (alternatively runtime)
                     "runcount-limit": 50,   # maximum function evaluations
                     "cs": cs,               # configuration space
                     "deterministic": "false",
                     "shared_model": True,
                     "ta" : eval_config,
                     "wallclock_limit" : 5.,
                     "input_psmac_dirs": "smac3_outz"
                     })
```
Now I create a PSMAC object. I got to this point looking around the source code of the PSMAC class and some others.
```
psmac = PSMAC(scenario=scenario, rng=np.random.RandomState(42),
              tae=ExecuteTAFuncDict, n_optimizers=2, validate=False)
incumbent = psmac.optimize()
inc_value = eval_config(incumbent[0].get_dictionary())
print("Optimized Value: %.2f" % (inc_value))
```
#### Results and quick fix
Running the code above results in a lengthy error message that culminates with:
```
TypeError: can only join an iterable
  File "/Users/sergio/Library/Python/3.7/lib/python/site-packages/smac/utils/io/output_writer.py", line 122, in _parse_argument
    return " ".join(value)
TypeError: can only join an iterable
```
To avoid this, I modified smac/utils/io/output_writer.py at line 120 like this:
```
elif key == 'ta' and value is not None:
            if callable(value):  # modifying to avoid psmac error...
                return value.__name__
            else:
                # Reversing the callback on 'ta' (shlex.split)
                return " ".join(value)
```
This gets rid of the error, and presumably permits the parallel SMAC execution. I get a couple of warnings, though:
```
/home/z/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/z/.local/lib/python3.5/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```
I would appreciate your input, regarding whether this seems like a correct way to execute PSMAC from Python, and on how to configure the instances. If my "fix" is of any value, I can also do a pull request.

#### Versions
0.10.0

**Comment by sharpe5** [comment]
One of the [pull requests](https://github.com/automl/SMAC3/pull/855) has example code for using pSMAC:

https://github.com/automl/SMAC3/pull/855/commits/4d8ffbe37ee6a26118a8ef8f47326cc88aa67fc8
