### ISSUE TITLE
No module named 'smac.facade.smac_facade'

### ISSUE THREAD

**Issue by nabhoth** [automl/SMAC3#527]
#### Description
I installed all components required for SMAC3 from git repository. I installed it as a part of Autofolio. 

Example:
```
python3
from smac.facade.smac_facade import SMAC
ModuleNotFoundError: No module named 'smac.facade.smac_facade'

However import smac.facade works
```

#### Expected Results
Should import it
#### Versions
SMAC 3

**Comment by mlindauer** [comment]
Hi,

Sorry, we renamed the facades in SMAC, but I haven't upated AutoFolio.
AutoFolio should use the `smac.facade.smac_ac_facade`.

Best,
Marius

**Comment by nabhoth** [comment]
Hello,

actually I played with all facades in the facade folder. If the same command is issued, that is
from smac.facade.smac_ac_facade import SMAC

the error becomes 

ImportError: cannot import name 'SMAC'

regards
Martin

**Comment by mlindauer** [comment]
Yes, the class also changed its name to `SMAC4AC`.
Maybe, there are more little changes I would need to check.

**Comment by nabhoth** [comment]
Perhaps,

could you tell  me where I should pick up version of SMAC3 0.9 because that one seems to be matching the requirements of autofolio?

**Comment by mlindauer** [comment]
you could use pypi:
https://pypi.org/project/smac/0.9.0/

or all releases are also part of the repo:
https://github.com/automl/SMAC3/releases/tag/v0.9.0

**Comment by nabhoth** [comment]
Thank you
