### ISSUE TITLE
Source code for get_default_configuration()

### ISSUE THREAD

**Issue by Milad-abbaszadeh** [automl/SMAC3#528]
Hi all,

Actually I need to understand how 'config' builds under _select_configuration function. it means I need to access to source code of get_default_configuration() which I could not find it. 
https://automl.github.io/SMAC3/stable/_modules/smac/initial_design/default_configuration_design.html#DefaultConfiguration

I would be really grateful if you let me know how I can find this source code. I already check the java version of SMAC and python version but unfortunately, I did not find respect class.

Thanks,
Milad

**Comment by mlindauer** [comment]
Hi Milad,

That's part of our `ConfigSpace` package:
https://github.com/automl/ConfigSpace

Best,
Marius
