### ISSUE TITLE
Issue with optimization of test functions

### ISSUE THREAD

**Issue by rruizdeaustri** [automl/SMAC3#535]
I have installed latest version of SMAC3 and the optimization of the test functions: Branin and Rosenbrock does not work run with python. 

For Branin I get:

 INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: 1
INFO:smac.stats.stats.Stats:#Target algorithm runs: 10 / 10.0
INFO:smac.stats.stats.Stats:#Configurations: 10
INFO:smac.stats.stats.Stats:Used wallclock time: 5.69 / inf sec 
INFO:smac.stats.stats.Stats:Used target algorithm runtime: 0.06 / inf sec
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Final Incumbent: Configuration:
  x1, Value: 2.1278362889646063
  x2, Value: 3.3360020206759655

INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Estimated cost of incumbent: 4.942542
Optimum at [2.12783629 3.33600202] with cost of 4.94254177280993

which is not the right minimum.
 

 Thanks,
 Roberto

**Comment by mlindauer** [comment]
Dear Roberto,

Thank you for your interest in SMAC.

Please note two things:
i) I would recommend to use the SMAC4BO interface for continuous, artificial functions;
ii) You gave SMAC 10 function evaluations (`target algorithm runs`). I think it is fairly hard for any BO tool (which is not only designed for Branin) to hit the optimum with only 10 function evaluations.

Best regards,
Marius

**Comment by mfeurer** [comment]
Should we maybe adopt the examples to run for longer?
