### ISSUE TITLE
Question: Defining hyper parameter space with varying dimesions

### ISSUE THREAD

**Issue by mohanrobotics** [automl/SMAC3#538]
I am trying to optimize the hyper-parameters like anchor box scales of object detection. 
The anchor box scales are usually a list with varying length. 

For eg. I want a list of anchor scale with min1 and max 5 . The anchor scales must be in range 1 to 32. How to define the hyper-parameter space for this type of problems.

My hyperparameters are 
**Num_of_anchor_scale :** N         **type:** discrete       **Range :**[1,2,..5]
**Anchor scales** : [s_1,....s_N]       **type:** discrete but a list with N items       **Range:** [1.........32]

**Comment by renesass** [comment]
You have to use conditional hyperparameters.
Please create a new question [here](https://github.com/automl/ConfigSpace) if you have further questions.
