### ISSUE TITLE
Bottleneck in selecting new neighbors for Local Search

### ISSUE THREAD

**Issue by Yatoom** [automl/SMAC3#540]
#### Description
![](https://i.imgur.com/8OUPoEv.png)

There seems to be a bottleneck in selecting new neighbors for Local Search, which slows down SMAC as a whole. Using the Pycharm profiler, I profiled the execution times of a SMAC optimization run for 150 iterations: see the call graph above.

If we look at the orange box with `_do_search`, which is a method of the `LocalSearch` class, we see that it calls a built-in method `next()`, which can be found on this line: 

https://github.com/automl/SMAC3/blob/81eba541e67c09aa307f2ba23d583f94c60b6125/smac/optimizer/ei_optimization.py#L350

This line requests the next configuration from a generator that is created via `get_one_exchange_neighbourhood()`: 

https://github.com/automl/SMAC3/blob/81eba541e67c09aa307f2ba23d583f94c60b6125/smac/optimizer/ei_optimization.py#L327-L328 

which comes from the [ConfigSpace package](https://github.com/automl/ConfigSpace/blob/a5de09d56b87e01b77bc2eaec15b59c5a646e52b/ConfigSpace/util.pyx#L93).

From the call graph we can furthermore see that running the target algorithm and making the predictions with the surrogate model both require significantly less time than selecting the next neighborhood.

A short explanation of where we can find these processes in the graph:
- The process of running the target algorithm evaluator, which is in my case called `tat` (short for target algorithm tester) can be found in the chain on the right: `_race_challenger > start > run > tat`.
- The process of making predictions with the surrogate model can be seen in the chain on the top left: `predict_marginalized_over_instances > predict`
- Lastly, the training time is included within the `choose_next`'s own time (it's very small because it's only run once per iteration)

#### Versions
SMAC version: 0.11.1

**Comment by mlindauer** [comment]
Dear Yatoom,

Thank you for your interest in SMAC and the detailed profiling.
I wonder a bit what your results suggests:
a) do we have to improve the code for obtaining the local neighbors? (if yes, we should move the issue to the issue tracker of the configspace package)
or
b) do we should implement something else instead of local search?

Please note that SMAC is designed for optimizing expensive functions (/target algorithms). Thus, a bit of overhead in the Bayesian Optimization part of SMAC, typically is acceptable. If you have a cheap function to be optimized, you should consider to use a different tool.

@mfeurer could you please take care of this issue report.

Best,
Marius

**Comment by Yatoom** [comment]
Hi @mlindauer, thank you for your response.

> a) do we have to improve the code for obtaining the local neighbors? (if yes, we should move the issue to the issue tracker of the configspace package)

It could indeed be that the long times are caused by the ConfigSpace package, in which case I agree we should move this issue there. However, it could also be that the way that the function from this package is queried could be optimized.

> Please note that SMAC is designed for optimizing expensive functions (/target algorithms). Thus, a bit of overhead in the Bayesian Optimization part of SMAC, typically is acceptable. If you have a cheap function to be optimized, you should consider to use a different tool.

I understand that this is the case. However, I would expect that generating the neighbor samples should take less time than predicting with a Random Forest. I think the overhead for generating these samples can be reduced a lot.

Thanks,
Jeroen

**Comment by Yatoom** [comment]
**Update:** I managed to reduce the overhead of selecting neighbors from around **230 seconds** to **75 seconds** for 150 iterations, searching over 5 hyperparameters. See `<built-in method builtins.next>`

![](https://i.imgur.com/hkxMfvk.png)

It turns out that the call to `np.any()` in [this line](https://github.com/automl/ConfigSpace/blob/31a09923597dbcfb2b25153f2a2dd0f37bcc655f/ConfigSpace/hyperparameters.pyx#L488) and [this line](https://github.com/automl/ConfigSpace/blob/31a09923597dbcfb2b25153f2a2dd0f37bcc655f/ConfigSpace/hyperparameters.pyx#L808) were very expensive. I added a check to make sure the `np.any()` is really needed, which was never the case I believe.

```python
if isinstance(vector, np.ndarray) and np.any(np.isnan(vector)):
    return None
elif np.isnan(vector):
    return None
```

The function that made the call is the `_transform()` method, which gets called if you call the `get_neighbors()` method from a UniformIntegerHyperparameter or UniformFloatHyperparameter. So this should save a lot of time, especially if you add more hyperparameters to the search space.

And because I used local copies of these classes in Python code, rather than Cython code, it might save even more time.

**Comment by mfeurer** [comment]
Thanks a lot for this report. A few questions for clarification:

* Do I understand the issue correctly that you have an overhead of ~75s for 150 iterations?
* Could you please post your searchspace?
* Are you using the ConfigSpace from pypi or from github?

Finally, if the changes you made to transform do not break the unit tests, could you please create a pull request for them?

CC @KEggensperger who also had issues with the speed of generating integer hyperparameters.

**Comment by mfeurer** [comment]
I pushed a new release of the `ConfigSpace` package to pypi which should fix this issue. Please reopen if that's not the case.
