### ISSUE TITLE
max_steps in EI optimization ignored

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#541]
I just realized that the variable "max_steps" is ignored in the local search. This is not urgent, but we might want to fix it at some point by either removing or implementing it.

https://github.com/automl/SMAC3/blob/development/smac/optimizer/ei_optimization.py#L183

**Comment by mlindauer** [comment]
We implicitly replaced that by `n_steps_plateau_walk` after introducing plateau walks. I don't know whether we want to consider `max_steps` again or simply dropping it entirely. 
(I recently read a paper that suggested that finding the optimum of the acq function is quite important to achieve good performance -- however, they used GPs and not RFs)
