### ISSUE TITLE
Documentation: SVM-example use log hyperparam

### ISSUE THREAD

**Issue by stheid** [automl/SMAC3#544]
This issue is not a bug, but a changerequest for the documentation

in line 68 of the codesample in [quickstart>svm](https://automl.github.io/SMAC3/master/quickstart.html#using-smac-in-python-svm) the line 

```
C = UniformFloatHyperparameter("C", 0.001, 1000.0, default_value=1.0)
```

should rather be
```
C = UniformFloatHyperparameter("C", 0.001, 1000.0, default_value=1.0, log=True)
```
As the [documentation for ConfigSpace](https://automl.github.io/ConfigSpace/master/API-Doc.html#float-hyperparameters) is hard to find, its particularly important that the examples express the intended usage!

For a novice user it might not be obvious, that such a hyperparameter should be sampled logarithmic and how to achieve it.

**Comment by gamer01** [comment]
https://automl.github.io/ConfigSpace/master/API-Doc.html#categorical-hyperparameters

This documentation says you cant use booleans as choices, which is additionally stressed with line  46 in the `svm_from_cfg()` function. [quickstart>svm](https://automl.github.io/SMAC3/master/quickstart.html#using-smac-in-python-svm)

However this is not true. Boolean choices and default values work just fine!!!

**Comment by mlindauer** [comment]
Thank you for reporting this issue and the concrete recommendations on how to improve our documentation.
We would highly appreciate if you would provide a PR (directed to the dev branch) with your suggestions.

**Comment by gamer01** [comment]
I dont know how i would make a pullrequest for the ConfigSpace api documentation.

**Comment by mfeurer** [comment]
The ConfigSpace API documentation is in the respective classes and methods. You can make a PR to the API docs by changing the docstring of the classes and methods.
