### ISSUE TITLE
Question - SMAC3 implementation with a CNN

### ISSUE THREAD

**Issue by WrightKD** [automl/SMAC3#552]
Trying to use smac with a simple CNN.My [code](https://github.com/WrightKD/SMAC/blob/master/smac.py)

I followed the example of the SVM , and tried to implement it with a CNN.Please show me where I went wrong if possible. And how to improve the results from SMAC which I'm comparing to gridsearch.

**Comment by mlindauer** [comment]
Hi,

I would start with increasing your limits:
`"runcount-limit": 5, "cutoff-time":10,`
and defining a useful configuration space.

I'm very sorry but we can't provide general support for applications of SMAC. We might can help with specific questions or real issues.

Best,
Marius
