### ISSUE TITLE
Broken Hyperband

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#560]
#### Description

Hi, 
I wanted to use the new hyperband package, but the example is not running, see below.
I saw that the new PR will change again quite a bit in how we use intensifiers, but I don't know whether that will fix that bug.
Anyway, could you please look into it.

PS: I'm surprised that travis-ci has not complained, since I thought it also executes the examples. @mfeurer do we still do that?

#### Steps/Code to Reproduce

```
$ python examples/SMAC4HPO_sgd_hyperband_instances.py

[...]

INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: 0
INFO:smac.stats.stats.Stats:#Target algorithm runs: 123 / inf
INFO:smac.stats.stats.Stats:#Configurations: 27
INFO:smac.stats.stats.Stats:Used wallclock time: 17.92 / 60.00 sec 
INFO:smac.stats.stats.Stats:Used target algorithm runtime: 12.17 / inf sec
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Final Incumbent: Configuration:
  alpha, Value: 0.1875
  eta0, Value: 0.0003651741272548377
  l1_ratio, Value: 0.3125
  learning_rate, Value: 'adaptive'

INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Estimated cost of incumbent: 0.012143
Traceback (most recent call last):
  File "examples/SMAC4HPO_sgd_hyperband_instances.py", line 139, in <module>
    incumbent = smac.optimize()
  File "/home/lindauer/anaconda3/lib/python3.7/site-packages/smac/facade/smac_ac_facade.py", line 552, in optimize
    incumbent = self.solver.run()
  File "/home/lindauer/anaconda3/lib/python3.7/site-packages/smac/optimizer/smbo.py", line 216, in run
    time_bound=max(self.intensifier._min_time, time_left))
AttributeError: 'Hyperband' object has no attribute '_min_time'

```

#### Versions

Development branch

**Comment by ashraaghav** [comment]
Hello,

This bug has been addressed in the next pull request. (#551)

This was not caught in travis-ci because the execution was completed before it reached this section (the main BO loop). It seems the wallclock time limit for the example was not enough for that processor. I will increase it a little more, if that is okay.

**Comment by mfeurer** [comment]
> I will increase it a little more, if that is okay.

Yes, that's fine. Currently, the examples are running for 6 minutes, we can easily go up to ~8-10 minutes before it becomes a real issue.

**Comment by mlindauer** [comment]
The bug, I reported above, was already triggered after 18 seconds. If each example runs for at most 6 minutes, something else is broken. If all examples together can use up to 6 minutes, is there a way to prioritize the examples? Fast one first, slow ones later.

**Comment by mfeurer** [comment]
Hey @mlindauer could you please check the current version from the development branch whether this is still an issue?

**Comment by mlindauer** [comment]
Thanks. I can run it now.
However, there is a warning from sklearn now, which is quite annoying.
```
  FutureWarning
/home/lindauer/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
```

**Comment by mfeurer** [comment]
This is fixed by the latest changes to the examples I merged in after your comment. I'll close this for now.
