### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#568]
Suggestions:

* organize examples by interfaces #1137 
* add new examples
    * different initial design #1135 
    * optimization on a fixed grid of hyperparameters #1136 
    * #562
    * target function with additional arguments #1134

**Comment by eddiebergman** [comment]
[ ] How to warm start SMAC
[ ] More advanced uses of SMAC for `ask` and `tell` with multiple-objectives, see #950

**Comment by benjamc** [comment]
- [ ] #831

**Comment by timruhkopf** [comment]
- [] #975

**Comment by benjamc** [comment]
- [ ] Document how to setup dask client in facade (e.g. run on slurm)

**Comment by eddiebergman** [comment]
> * [ ]  Document how to setup dask client in facade (e.g. run on slurm)

Do you use `dask_jobqueue` by any chance?

**Comment by benjamc** [comment]
@eddiebergman 
> Do you use dask_jobqueue by any chance?

Yes, I am using dask_jobqueue and the slurm cluster and it works like a charm. :)

**Comment by helegraf** [comment]
All enhancement regarding documentation mentioned in this thread are their own issues now, thus I am closing this issue as it is a huge collection of stuff that no one will tackle at once.
