### ISSUE TITLE
ConfigSpace's version not accurate in requirements.txt

### ISSUE THREAD

**Issue by RukawaKaede** [automl/SMAC3#578]
#### Description

In line 218 of smac/initial_design/initial_design.py, ConfigSpace's method "deactivate_inactive_hyperparameters" method has 3 parameters. But I checked ConfigSpace-0.4.7 and ConfigSpace-0.4.8, this method only accepts 2 parameters. I think the line "ConfigSpace>=0.4.6,<0.5" in requirements.txt will mislead people. :-)

**Comment by mfeurer** [comment]
Thanks a lot for reporting this. I just created a fix in PR #585.

**Comment by mfeurer** [comment]
Fixed in #585.
