### ISSUE TITLE
pSMAC can change file while other process still reads it

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#591]
As described in https://github.com/automl/auto-sklearn/issues/712

A try/except around the read function could help here.

**Comment by agtoever** [comment]
I'd recommend a [retry](https://pypi.org/project/retry/) decorator around `pSMAC`. Here is a diff:

```
--- pSMAC_orig.py
+++ pSMAC.py
@@ -4,6 +4,7 @@
 import typing
 import logging
 import glob
+import retry
 
 from smac.runhistory.runhistory import RunHistory
 from smac.configspace import ConfigurationSpace
@@ -12,6 +13,7 @@
 RUNHISTORY_RE = r'runhistory\.json'
 
 
+@retry.retry(Exception, delay=10, tries=-1)
 def read(run_history: RunHistory, 
          output_dirs: typing.Union[str, typing.List[str]],
          configuration_space: ConfigurationSpace,
```
Safe this to a file `pSMAC.patch` and do `patch <path_to_smac_optimizer>/pSMAC.py pSMAC.patch`.

**Comment by jendrikseipp** [comment]
I'm running into the same problem. @mfeurer, which fix did you have in mind for this exactly? Or is it the same as https://github.com/automl/SMAC3/issues/591#issuecomment-602011463?

**Comment by mfeurer** [comment]
I think a simply try/except around the function call to [`read`](https://github.com/automl/SMAC3/blob/master/smac/optimizer/smbo.py#L178) would prevent SMAC from failing. I'm a bit reluctant to adding new packages to the dependency list

**Comment by mfeurer** [comment]
Actually, we have fixed this quite a while ago and SMAC only prints a warning. The issue in Auto-sklearn is due to an old SMAC version which will be fixed in the next Auto-sklearn release.
