### ISSUE TITLE
Change directory name generated after optimization run 

### ISSUE THREAD

**Issue by DiezPablo** [automl/SMAC3#592]
When I run an iteration of a program optimizing a function, I get a directory with files with stats of the execution. I want to know if it's possible to modify that file name.

Thanks!

**Comment by mlindauer** [comment]
Hi,

Do you refer to the output of SMAC?
If yes, there is an option called "--output-dir". You can use it on the command line and as part of the scenario object.

Best,
Marius

**Comment by DiezPablo** [comment]
That's it!

Thank you!
