### ISSUE TITLE
Can't run smac3 in google colab

### ISSUE THREAD

**Issue by DiezPablo** [automl/SMAC3#615]
Hello, I am trying to run smac in google colab, I have installed it with all the requierements and also with the installation of "swig". 

I import smac and run the cell it throws me, that error:
IncorrectPackageVersionError: 'scikit-learn 0.22.1' version mismatch (<0.22)

I've checked the version with pip3 freeze and the scikit-learn version is 0.21.3.

Do anyone know how to solve that?

**Comment by mlindauer** [comment]
Hi,

I can verify that problem. I don't know why but `pkg_resources.get_distribution("scikit-learn")` points to another installation of sklearn, which actually does not exist anymore.

A quick and dirty hack would be to deactivate the requirement checking of smac by deleting the requirements.txt
```
with open("/usr/local/lib/python3.6/dist-packages/smac/requirements.txt", "w") as fp:
  fp.write("")
```

Best,
Marius

**Comment by DiezPablo** [comment]
It was solved restarting the environment, that was the problem.

Anyway, one thing to know, whenever you initiate a Google Colab Session with your notebook is necessary to reinstall everything to run your experiment, it's not saved for that notebook.

Thanks!
