### ISSUE TITLE
How to know the exact iteration number where we get the best result of an optimization.

### ISSUE THREAD

**Issue by DiezPablo** [automl/SMAC3#624]
Hello,

I'm trying to optimize XGBoost, using SMAC3 in a simple problem. So, I run 50 iterations of Bayesian Optimitazion using SMAC4HPO and i want to know in which of those iterations I obtain the optimized value.

I don't know if it is possible to know and to get a print like print("The best result happens itn the iteration: " , num_iteration) or something like that.

Thanks!

Pablo.

**Comment by mlindauer** [comment]
Hi Pablo,

your `smac` object has a function `get_trajectory()`. This is a list of [TrajEntry](https://github.com/automl/SMAC3/blob/master/smac/utils/io/traj_logging.py#L16). The field you are looking for is `ta_runs`.

Best,
Marius
