### ISSUE TITLE
Weird Behavior-not sure if bug or what

### ISSUE THREAD

**Issue by rlecover007** [automl/SMAC3#630]
#### Description
I was attempting to use the binary python values [True, False] in a categorical hyperparameter. However, while the initial configuration would run fine, the optimization would fail, since the configuration dictionary appeared to get truncated. I'm not sure exactly what happened behind the scenes, but this was strange behavior to me, so this note is mostly for future programmers who encounter this. I got around this by passing in strings instead of boolean values. 

#### Steps/Code to Reproduce

use_text_features = CategoricalHyperparameter("use_text_features", ["True", "False"], default_value = "True")
#### Actual Results
INFO:smac.intensification.intensification.Intensifier:First run, no incumbent provided; challenger is assumed to be the incumbent
{'hidden_init_type': 'ZEROS', 'hidden_size': 272, 'lr': 0.005005, 'min_seq_len': 8, 'pad_method': 'LONGEST', 'rare_feat_thresh': 0.30000000000000004, 'window_width': 60}
ERROR:smac.tae.execute_func.ExecuteTAFuncDict:'use_text_features'
Traceback (most recent call last):
  File "/home/rachel/.local/lib/python3.7/site-packages/smac/tae/execute_func.py", line 190, in run
    rval = self._call_ta(self._ta, config, obj_kwargs)
  File "/home/rachel/.local/lib/python3.7/site-packages/smac/tae/execute_func.py", line 281, in _call_ta
    return obj(config, **obj_kwargs)
  File "<string>", line 44, in runGRUPlusSVM
KeyError: 'use_text_features'

#### Versions

0.12.0

**Comment by mlindauer** [comment]
Dear Rachel, 

Thank you very much for reporting this issue. It sounds like a major bug and we would like to understand what is happening. I tried to use strings and bools as values for a categorical hyperparameter and could not reproduce the problem.
Could you please provide a full minimal-working example to reproduce the issue.

Best,
Marius

**Comment by rlecover007** [comment]
I figured out what was going on while attempting to create a MWE-the command
```
cfg = {k: cfg[k] for k in cfg if cfg[k]}
```
was dropping by boolean parameters. So, the error is on my part, not on yours.

**Comment by mlindauer** [comment]
Thanks for clarifying that :-)
