### ISSUE TITLE
BUG: 'NoneType' object has no attribute 'get_dictionary'

### ISSUE THREAD

**Issue by gvelev123** [automl/SMAC3#640]
#### Description
I am performing hyperparameter optimization for MLP using SMAC. I set the max trials to 50. The first  time I run the optimization, everything is okay. However, if I try running it again, I get the error: 
'NoneType' object has no attribute 'get_dictionary'. Only when I restart the kernel, I can run it again one time only.

#### Steps/Code to Reproduce
#CREATE A SCENARIO OBJECT:
scenario_mlp = Scenario({"run_obj": "quality",  
                     "runcount-limit": 50,  
                         "cs": cs_mlp,  
                     'abort_on_first_run_crash':False
                     })

#CHOOSE THE OPTIMIZER: SMAC4HPO,BOHB4HPO
print("Optimizing! Depending on your machine, this might take a few minutes.")
smac_mlp = SMAC4AC(scenario=scenario_mlp,
               tae_runner=smac_objective_mlp,
               initial_design=DefaultConfiguration
               )

best_result_mlp=smac_mlp.optimize()

where cs_mlp is the search space I defined for the MLP and smac_objective_mlp is my objective function.

#### Expected Results
I would expect the optimization to be able to run again since it already ran successfully one time. 

#### Actual Results
The optimization crashes and I have to restart my kernel.

#### Versions
SMAC Version: '0.12.0'

**Comment by mlindauer** [comment]
Could you please provide a complete minimal working example and give some more details about your environment. I would guess that you use some kind of jupyter notebook? or colab? 

Thanks,
Marius
