### ISSUE TITLE
SMAC validate does not support budgets yet

### ISSUE THREAD

**Issue by shukon** [automl/SMAC3#644]
#### Description

SMAC's Validator (which is supposed to run target algorithm for interesting configurations and instances to generate data) does not yet work for budgets.

Since I seem to be the only one using the validator - is this even compatible with the new architecture (i.e. the Configurator 'pulling' the runs)?

So:
1) Should I fix this? (Do we want to keep it?)
2) Anything I should look out for while fixing in terms of new architecture?
3) Any guide as to how to use EPM's with budgets (how are `Configuration`s estimated? only on same budget-data?)

#### Steps/Code to Reproduce

```
from ConfigSpace.configuration_space import ConfigurationSpace
from ConfigSpace.hyperparameters import UniformIntegerHyperparameter
from smac.runhistory.runhistory import RunHistory
from smac.scenario.scenario import Scenario
from smac.tae.execute_ta_run import StatusType
from smac.utils.validate import Validator

if __name__ == '__main__':
    scenario = Scenario({'run_obj': 'quality'})
    configspace = ConfigurationSpace()
    configspace.add_hyperparameter(UniformIntegerHyperparameter('parameter', lower=1, upper=5, default_value=3))
    scenario.cs = configspace
    runhistory = RunHistory()
    runhistory.add(config=configspace.get_default_configuration(), cost=0.4, time=0.2, seed=1, status=StatusType.SUCCESS, budget=5)
    trajectory = [{
                    'cpu_time' : time,
                    'total_cpu_time' : None,
                    "wallclock_time" : time,
                    "evaluations" : 1,
                    "cost" : cost,
                    "incumbent" : config,
                  } for time, cost, config in [[0.2, 0.4, configspace.get_default_configuration()]]]

    validator = Validator(scenario=scenario, trajectory=trajectory)
    validator.validate_epm('def+inc', 'train+test', 1, runhistory=runhistory)
```

#### Expected Results

Validator should be able to parse and validate budgeted `RunHistory`s, probably even with an option to validate specific budgets.

#### Actual Results

Raises an error, since the corresponding budget is not passed and the default of 0 is assumed, leading to a KeyError.
```
(...)
validator.validate_epm('def+inc', 'train+test', 1, runhistory=existing_runhistory)
  smac/utils/validate.py", line 339, in validate_epm
    runs, rh_epm = self._get_runs(config_mode, instance_mode, repetitions, runhistory)
  smac/utils/validate.py", line 452, in _get_runs
    cost, time, status, additional_info = runhistory.data[runkey]
KeyError: RunKey(config_id=1, instance_id=None, seed=42, budget=0.0)
```

#### Versions

0.12.0

**Comment by alexandertornede** [comment]
Since the interface between 1.4 and 2.0 changed considerably, we close this issue.
