### ISSUE TITLE
Bug: result not recorded when restoring from the previous SMAC run

### ISSUE THREAD

**Issue by dengdifan** [automl/SMAC3#646]
**Description**
I want to restore the previous SMAC run and continue that optimization process. However, the new run will not create a directory that records the new run result.  When "restore_incumbent" is not None,  "smac.output_dir" is correctly initialized and created.

**Steps/Code to Reproduce**
run examples/branin/restore_state.py or simply the following code:
`import os
import shutil

from smac.facade.smac_bo_facade import SMAC4BO

from smac.configspace import ConfigurationSpace
from ConfigSpace.hyperparameters import UniformFloatHyperparameter

from smac.runhistory.runhistory import RunHistory
from smac.scenario.scenario import Scenario
from smac.stats.stats import Stats
from smac.utils.io.traj_logging import TrajLogger

def rosenbrock_2d(x):
    x1 = x["x0"]
    x2 = x["x1"]
    val = 100. * (x2 - x1 ** 2.) ** 2. + (1 - x1) ** 2.
    return val

cs = ConfigurationSpace()
x0 = UniformFloatHyperparameter("x0", -5, 10, default_value=-3)
x1 = UniformFloatHyperparameter("x1", -5, 10, default_value=-4)
cs.add_hyperparameters([x0, x1])

orig_scen_dict = {'run_obj': 'quality',
                  'runcount-limit': 2,
                  "cs": cs,
                  'deterministic': True,
                  'output_dir': 'restore_me'}
original_scenario = Scenario(orig_scen_dict)
smac = SMAC4BO(scenario=original_scenario,
               run_id=1,
               tae_runner=rosenbrock_2d)
smac.optimize()
old_output_dir = os.path.join(original_scenario.output_dir, 'run_1')

new_scenario = Scenario(orig_scen_dict,
                        cmd_options={'runcount-limit': 5,  # overwrite these args
                                     'output_dir': 'restored'})

rh_path = os.path.join(old_output_dir, "runhistory.json")
runhistory = RunHistory()
runhistory.load_json(rh_path, new_scenario.cs)

stats_path = os.path.join(old_output_dir, "stats.json")
stats = Stats(new_scenario)
stats.load(stats_path)

traj_path = os.path.join(old_output_dir, "traj_aclib2.json")
trajectory = TrajLogger.read_traj_aclib_format(
    fn=traj_path, cs=new_scenario.cs)
incumbent = trajectory[-1]["incumbent"]

smac = SMAC4BO(scenario=new_scenario,
               runhistory=runhistory,
               stats=stats,
               restore_incumbent=incumbent,
               run_id=1,
               tae_runner=rosenbrock_2d)

print(smac.output_dir)
new_traj_path = os.path.join(new_scenario.output_dir, "run_1", "traj_aclib2.json")
shutil.copy(traj_path, new_traj_path)

smac.optimize()`

**Expected Results**
a new directory "restored" should be created

**Actual Results**
Only the directory "restore_me" is created. "smac.output_dir" is None. The new directory "restored" is not created and hence an error occurs:
FileNotFoundError: [Errno 2] No such file or directory: 'restored/run_1/traj_aclib2.json'

**Versions**
SMAC Version: '0.12.0'

**Comment by stwerner97** [comment]
Did you find a solution to this issue? I am currently stuck with restoring past SMAC runs. The logs suggest that no output directory is specified for the scenario and trajectory logging,

**Comment by juliagviu** [comment]
I was having the same issue and I found out that the problem is the scenario attribute 'output_dir_for_this_run'. It is set to None in the scenario constructor so SMAC considers there is no output directory specified and does not log anything. Just change it when defining the new_scenario like this:

new_scenario = Scenario(orig_scen_dict,
cmd_options={'runcount-limit': 5, # overwrite these args
'output_dir': 'restored',
'output_dir_for_this_run': 'restored/run_1'}) # it is run_1 in this case because you specified run_id=1 in SMAC4BO function, but you should change it if specified directly

Hope this helps! :)
