### ISSUE TITLE
Store time stams of start and end of a function evaluation in runhistory

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#647]
This allows for easier printing of a trajectory if we do not actually use the trajectory file, but the runhistory to get the results.

**Comment by tschechlovdev** [comment]
@mfeurer Does this mean it is possible to get the runtime for each function evaluation? Could you tell me how to get this?
From the Stats object, I'm only getting the runtime for the whole optimization procedure (at least when "run_obj" is quality).

Moreover, is it possible to get more detailed information for each function evaluation? For example, my target algorithm consists of two steps and I want to measure the time for each step. Is it possible to also store this information somewhere?

**Comment by mfeurer** [comment]
Could you please open a new issue @tschechlovdev. These are excellent questions, but they do not belong into this issue.

**Comment by mfeurer** [comment]
Added via #659.
