### ISSUE TITLE
Value for tuner_timeout is ignored

### ISSUE THREAD

**Issue by jendrikseipp** [automl/SMAC3#651]
#### Steps/Code to Reproduce

```
scenario = Scenario(
    {
        ...
        "tuner_timeout": 1000,
    }
)
print(getattr(scenario, 'tuner_timeout', 200))
smac = SMAC4AC(
    scenario=scenario,
   ...
)
print(getattr(smac.scenario, 'tuner_timeout', 300)) 
```
#### Expected Results

1000
1000

#### Actual Results

200
300

It's unclear to me whether "tuner_timeout" is obsolete and should just be removed from the code base or its value should be present in the Scenario object. 

#### Versions

0.12.1.dev0

**Comment by benjamc** [comment]
Should be fixed in 2.x
