### ISSUE TITLE
Question: Detailed information for each function evaluation

### ISSUE THREAD

**Issue by tschechlovdev** [automl/SMAC3#652]
#### Description

I want to get detailed information about each function evaluation of my target algorithm, i.e., my target algorithm contains two steps and I want to measure the runtime for each step separately. Is it possible to do this? 

Also, I want to measure the whole runtime for SMAC (particularly, SMAC4HPO) after each function evaluation. I do not see the runtime in the runhistory object (at least when using objective "quality"). In the "runhistory.json", I only find the runtime for each function evaluation but NOT for the whole optimization (like the wallclock time used). 
So, I want something similar to the stats object (or the "stats.json"), but for each iteration of SMAC and not only for the whole optimization process.
Is it possible to access the information like in the "stats.json" for each iteration? 

#### Version
0.12.0

**Comment by tschechlovdev** [comment]
I have seen that there is a possibility to return "additional_info" for each evaluation of the target algorithm. This field is "{}" in the "runhistory.json". It would definitely be ok for me, if I could write the information I need into this field but I don't know how I can set the "additional_info" field.

**Comment by mfeurer** [comment]
> I need into this field but I don't know how I can set the "additional_info" field.

If you directly optimize a python function, you can return a tuple with the 2nd return value being a dict, see [here](https://github.com/automl/SMAC3/blob/v0.12.1/smac/tae/execute_func.py#L165). 

> Is it possible to access the information like in the "stats.json" for each iteration?

Unfortunately, this doesn't exist yet.

**Comment by tschechlovdev** [comment]
@mfeurer Thanks, got it working now!
