### ISSUE TITLE
Docstrings: runhistory2epm success_states 

### ISSUE THREAD

**Issue by shukon** [automl/SMAC3#662]
In the current master-branch, there is [this](https://github.com/automl/SMAC3/blob/d5b93811aa74e0513e580576ebb0fbf857e18f1a/smac/runhistory/runhistory2epm.py#L64-L66) in the docstrings stating `success_states` are optional. This is [not the case](https://github.com/automl/SMAC3/blob/d5b93811aa74e0513e580576ebb0fbf857e18f1a/smac/runhistory/runhistory2epm.py#L117-L118) anymore. Doc-strings should be modified.

**Comment by dengdifan** [comment]
Thanks for the reporting! This issue is fixed by https://github.com/automl/SMAC3/pull/772
