### ISSUE TITLE
SMAC4BO - new assert in 0.12.2 - brackets

### ISSUE THREAD

**Issue by lucasplagwitz** [automl/SMAC3#665]
Up to version 0.12.1 I am able to use BO without restrictions.  
Since 0.12.2 I get a bug in smac/facade/smac_bo_facade.py line 107:
`
assert len(cont_dims + len(cat_dims)) == len(scenario.cs.get_hyperparameters())
`

 Is it possible that the brackets simply need to be changed to
`
assert (len(cont_dims) + len(cat_dims)) == len(scenario.cs.get_hyperparameters())
`
? Then everything runs as before, but maybe I am missing something important.

**Comment by lucasplagwitz** [comment]
I would have two additional observations. Perhaps one could make a short statement about them:
1. Since version>=0.12.1 the BO-facade leads to a continuous loop. With version<0.12.1 everything runs normally.
2. All non BO-Facades run only on Linux. E.g. HPO with pyrfr 0.8 on macOS generates a Segmentation fault: 11 error.

**Comment by mfeurer** [comment]
> Then everything runs as before, but maybe I am missing something important.

**Comment by mfeurer** [comment]
Hey, I just merged a fix to the development branch. Could you please have a look whether it fixes your issues?

**Comment by lucasplagwitz** [comment]
Hey, I have tested the Branch and can use the BO-Facade again without restrictions. Thank you very much.

**Comment by mfeurer** [comment]
Hey @lucasplagwitz we finally pushed a new release fixing this issue also in the version you get from pypi. Thanks for reporting and checking the fix.
