### ISSUE TITLE
SMAC-HB always samples the same budget

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#699]
#### Description
Run a modified version of `BOHB4HPO_mlp.py`. It will always sample the call the target function with the same budget.

#### Steps/Code to Reproduce
Run the provided script. I only changed the min and max budget, and return a random objective value to save time.
[always_the_same_budget.zip](https://github.com/automl/SMAC3/files/5384490/always_the_same_budget.zip)

#### Expected Results
SMAC calls the target function with different budgets ranging from [0.1, 100] or raises an exception that the lowest budget has to be >1. Interestingly, if the upper budget is set to 1, it work fine. So the problem is most likely the combination of min_budget<1 and max_budget>1.

#### Actual Results
SMAC calls the target always with the same budget 0.137174

#### Versions
0.13.0

**Comment by franchuterivera** [comment]
If we take algorithm 1 from https://arxiv.org/pdf/1807.01774.pdf, hyperband dictates that there should be:

```
s_max = log(max_budget /initial_budget) / log(eta) = 6
```

Which dictates that there should be a total of 729 initial configurations:
```
# Here s=6 as it is the first iteration, which starts decreasingly
n_challengers = (s_max + 1) / (s + 1)) * eta ** s) = 729
```
So the initial budget of 0.1371742112482853 needs to be run for 729 configurations before trying the budgets [ 0.13717421   0.41152263   1.2345679    3.7037037   11.11111111  33.33333333 100. ]

I think you limit the run to 100 seconds, which is not enough for 729 configurations with an average of 1 second runtime. If you run for 1000 seconds for instance, you see how the budget is changed. To me this behavior complies with the paper's algorithm.

Please let me know if you consider something has to be changed.

**Comment by KEggensperger** [comment]
Yes, indeed. Maybe in the far future we should raise an issue if it is unlikely to complete one SH run given the timelimits, but for now this is fine, thanks a lot.
