### ISSUE TITLE
Wrong initial budget

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#701]
#### Description
SMAC w/ Hyperband uses the wrong initial budget. 

There seems to be a numerical issue when initializing SH as part of HB with the current budget as the initial budget. SH should use exactly the given budget as the lowest budget (see [here](https://github.com/automl/SMAC3/blob/9d7d09dd6ab08281beeacd2567a79841d5631409/smac/intensification/hyperband.py#L287)), but potentially due to rounding issues it uses the next higher budget.

#### Steps/Code to Reproduce
Copy the files below to examples and run 
`python hyperband_mlp.py`

[budgets.zip](https://github.com/automl/SMAC3/files/5430829/budgets.zip)

#### Expected Results
SMAC computes the budgets `[  2.4691358    7.40740741  22.22222222  66.66666667 200. 600.]` (see bottom of output) and starts with the lowest budget, i.e. `2.4691358`

#### Actual Results
SMAC computes the correct budgets but starts with the second lowest budget, i.e. `7.40740741`

#### Versions
0.13.0

**Comment by mfeurer** [comment]
Fixed via #702.
