### ISSUE TITLE
illegal value for UniformFloatHyperparameter with Log Sampling

### ISSUE THREAD

**Issue by hamid-arjmandi** [automl/SMAC3#708]
Hello,

I am using SMAC 0.12.2 with ConfigSpace 0.4.15.
I defined a hyperparameter as follows:

`dt_ratio = UniformFloatHyperparameter("dt_ratio", 100.0, 10000.0, default_value=100.0, log=True)`

I added this hyperparameter to the configuration space. After calling smac.facade.smac_hpo_facade.SMAC4HPO  I get the following error:

`
ValueError: Trying to set illegal value '0.0' (type '<class 'float'>') for hyperparameter 'dt_ratio, Type: UniformFloat, Range: [100.0, 10000.0], Default: 100.0, on log-scale' (default-value has type '<class 'numpy.float64'>').`

I checked it with other hyperparameters and it turned out that it happens only for `log=True`. I should also mention that it happens randomly and sometimes it proceeds without any error or warning. 

Best regards,
Hamid

**Comment by benjamc** [comment]
Hello Hamid,

is this still an issue for SMAC 1.0.1?
If so, could you provide a minimal working example so that we can reproduce the 

Best regards
