### ISSUE TITLE
[Question] Testing algorithm across multiple instances

### ISSUE THREAD

**Issue by gentrexha** [automl/SMAC3#710]
#### Description

I've created my version of the Simulated Annealing algorithm to solve AutoML problems. Now I'm trying to optimize my initial Temperature parameter. For this, I've taken the [OpenML CC-18 Benchmark Suite](https://docs.openml.org/benchmark/#openml-cc18) and started running SMAC for each dataset in the benchmark.

Resulting in an optimal temperature value different for each dataset. I want to find an optimized temperature value for all datasets. Is there a way to give the datasets as a parameter to my scenario and let SMAC try out different datasets?

I haven't found much useful material regarding this (ref: [#454](https://github.com/automl/SMAC3/issues/454) & [smac_ac_facade docs](https://automl.github.io/SMAC3/master/apidoc/smac.facade.smac_ac_facade.html)). It is clear to me that SMAC4HPO does not support instances. But on the other hand, while SMAC4AC does, I am not sure how to make use of that.

#### Steps/Code to Reproduce

As of now, I am using SMAC4HPO and iterating over the datasets in the benchmark suite like this:

```
benchmark_suite = openml.study.get_suite("OpenML-CC18") # Obtain the benchmark suite

for task_id in benchmark_suite.tasks:
    cs = ConfigurationSpace()
    T = UniformIntegerHyperparameter("T", 1e4, 1e10, default_value=1e7)
    task_id = Constant("task_id", task_id)
    cs.add_hyperparameters([T, task_id])

    # SMAC scenario object
    scenario = Scenario(
        {
            "run_obj": "quality",
            "runcount-limit": 10,
            "cs": cs,
            "deterministic": "true",
            "memory_limit": 4096,
        }
    )

    # To optimize, we pass the function to the SMAC-object
    smac = SMAC4HPO(
        scenario=scenario, rng=np.random.RandomState(42), tae_runner=sa_from_cfg
    )
```

Inside my `sa_from_cfg` function I just load the dataset from `openml` through the `task_id`, train-test-split it, and call my `SimulatedAnneal.fit(X_train, y_train)` function which does all the AutoML work and returns the F1 score of the test data. 

#### Expected Results

Provide a list of datasets, or directory containing datasets, and SMAC returns the optimal value for all instances.

#### Actual Results

Currently, I am receiving one optimal temperature value per dataset, while providing the dataset as a `Constant`. I could choose the `task_id` randomly between all the options, and therefore optimizing my algorithm over "all" instances, but this feels very hacky to me. Therefore, I wanted to know if there are any other alternatives to this?

#### Versions

0.13.1

**Comment by renesass** [comment]
Hi, sorry for our late reply.
Indeed it's not well documented how to use instances. We will add this documentation shortly.

There are basically two ways how to include instances.
1. You can create an external file and pass the filename to the scenario, e.g. {'instance_file' = 'instances.txt'}.
2. You can add the instances directly to the scenario, e.g. {'instance': [0, 1, 2]}.

Additionally to the instances, you can add instance features, which are passed as dict to the scenario object, e.g. {'features': {0: (15, 15, 15), 1: (15, 15, 16)}}. Those features are used to train the surrogate model (see https://github.com/automl/SMAC3/blob/master/smac/runhistory/runhistory2epm.py#L122).

Finally, you can use this example to integrate the instances:
https://automl.github.io/SMAC3/master/examples/SMAC4MF/SMAC4MF_mlp_example.html#sphx-glr-examples-smac4mf-smac4mf-mlp-example-py.

Best,
René
