### ISSUE TITLE
[bug]  Segmentation fault when trying to use SMAC on Mac OS

### ISSUE THREAD

**Issue by ravinkohli** [automl/SMAC3#711]
#### Description

I tried running the fmin_rosenbrock example available in the examples/fmin_rosenbrock.py. I am using anconda 4.9.2. I have installed swig 3.0.12 and I have apple's gcc installed with the following output when I run gcc --version
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
#### Steps/Code to Reproduce

The code is available on examples/fmin_rosenbrosk.py
#### Expected Results

SMAC should run and should print the best x found with cost
#### Actual Results

I get a segmentation fault. The traceback is as follows:
```
INFO:smac.utils.io.cmd_reader.CMDReader:Output to smac3-output_2020-12-01_20:53:44_989626
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Optimizing a deterministic scenario for quality without a tuner timeout - will make SMAC deterministic and only evaluate one configuration per iteration!
[1]    1572 segmentation fault  python examples/fmin_rosenbrock.py
```
#### Versions

0.13.1

**Comment by brenting** [comment]
I have the exact same issue on a different system:
Ubuntu 20.04
Python 3.6.12 (and 3.8.5)
SWIG 3.0.12
GCC 9.3.0

However, it does work on an older Ubuntu version:
Ubuntu 18.04
Python 3.6.9
SWIG 3.0.12
GCC 7.5.0

**Comment by darogans** [comment]
I am also facing the same issue on Ubuntu 20.04 while running SMAC4HPO examples. SMAC4BO_rosebrock.py runs fine though. Can you please check?
Thanks

**Comment by liuq** [comment]
Same issue on ubuntu 20.04 and SMAC4AC
