### ISSUE TITLE
[Question] How to call Keras predict() in target function 

### ISSUE THREAD

**Issue by Ellyuca** [automl/SMAC3#716]
Hi everyone. 

First of all I want to apologize for my ignorance regarding SMAC. I just started using it and I have no experience with it whatsoever.

I want to use SMAC to optimize some parameters of a given function based on the outcome of a Keras neural network model (pretrained and/or custom Convolutional neural networks). In particular, I need to call inside the target function a method _get_predictions()_ which inside calls the the _predict()_ of Keras. 
The result from the _get_predictions()_ will be used to compute the final return value of the target function. So I have something like this:
********************************************************************************************************
```{python}
#building a configuration space to define parameters and their range
 cs = ConfigurationSpace()

 gamma = UniformFloatHyperparameter('gamma', 0, 1, default_value='0.5')
 mom = UniformFloatHyperparameter('mom', 0 , 1, default_value='0.5')   
 c s.add_hyperparameters([gamma,mom])

#define target function
target_function(cfg):
      ...
     cfg = {k : cfg[k] for k in cfg if cfg[k]}
     print('Config is', cfg)

     p = get_predictions() #get_predictions calls model.predict(x) of Keras, where x is an image.
     r = manipulate_p with cfg parameters
     return r

#configuration of scenario
   scenario = Scenario({
    "run_obj": "quality",   # we optimize quality (alternatively runtime)
    "runcount-limit": 10,  # maximum function evaluations
    "cs": cs,               # configuration space
    "deterministic": "false"
})
#calling smac 
smac =  SMAC4HPO(scenario =scenario, rng = np.random.RandomState(42), tae_runner = target_function)

incumbent= smac.optimize ()
```
********************************************************************************************************

When trying to do this I encountered several issues. Initially I thought  that the target function cannot properly "see" the _predict()_ method. So instead of having get_predictions to handle the output from predict() I modified the structure of the script in order to call _model.predict()_ directly inside the target function. I continued to have the same problems. I used both a pretrained Resnet50 Keras model and a MLP model. I also tried reading the image x inside the target_function and also passing it as one of its arguments. For this test I used the Keras with tensorflow_gpu. 

I get the following error when I used _predict()_ inside the target function:
********************************************************************************************************
```bat
INFO:smac.utils.io.cmd_reader.CMDReader:Output to smac3-output_2021-02-19_14:12:07_366064
INFO:smac.initial_design.sobol_design.SobolDesign:Running initial design for 2 configurations
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:<class 'smac.facade.smac_hpo_facade.SMAC4HPO'>
INFO:smac.optimizer.smbo.SMBO:Running initial design
INFO:smac.intensification.intensification.Intensifier:First run, no incumbent provided; challenger is assumed to be the incumbent

Config is {'gamma': 0.5, 'mom': 6}

INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: -1
INFO:smac.stats.stats.Stats:#Submitted target algorithm runs: 0 / 10.0
INFO:smac.stats.stats.Stats:#Finished target algorithm runs: 0 / 10.0
INFO:smac.stats.stats.Stats:#Configurations: 0
INFO:smac.stats.stats.Stats:Used wallclock time: 103.98 / inf sec 
INFO:smac.stats.stats.Stats:Used target algorithm runtime: 0.00 / inf sec
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Final Incumbent: None
```
********************************************************************************************************

I did some research and I saw that some people used smac with sklearn classifiers. So i tried using a _sklearn.neural_network.MLPClassifier_ instead of a Keras model. In this case I can call the _predict()_ on the MLPClassifier without any issues and SMAC seems to work just fine.  Since sklearn doesn't support GPU I thought that the problems I had with Keras were related to the GPU. Therefore I switched to Keras with tensorflow_cpu and I repeated the same tests as mentioned above. I was getting warnings telling me that I should install emcee, skopt and pyDOE and retry to run the code again.  I install the suggested packages. This time the execution seems to be stuck. I get the following output:

********************************************************************************************************
```bat
INFO:smac.utils.io.cmd_reader.CMDReader:Output to smac3-output_2021-02-19_15:13:05_898283
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Optimizing a deterministic scenario for quality without a tuner timeout - will make SMAC deterministic and only evaluate one configuration per iteration!
INFO:smac.initial_design.sobol_design.SobolDesign:Running initial design for 2 configurations
INFO:smac.facade.smac_hpo_facade.SMAC4HPO:<class 'smac.facade.smac_hpo_facade.SMAC4HPO'>
INFO:smac.optimizer.smbo.SMBO:Running initial design
INFO:smac.intensification.intensification.Intensifier:First run, no incumbent provided; challenger is assumed to be the incumbent

Optimizing! Depending on your machine, this might take a few minutes.
SMAC <smac.facade.smac_hpo_facade.SMAC4HPO object at 0x7f80a2e54358>
Config is {'gamma': 0.5, 'mom': 0.5}
```
********************************************************************************************************

I let it run for more than one hour but nothing changes. The output remains the same. 

Does anyone have any idea on how to fix this problem? It is possible to use SMAC and Keras together?
All suggestions are welcomed since I honestly have no idea how to solve it. At this point I am willing to try anything xD.

Sorry for the long post.
Thank you all in advance for your time and help.

**Comment by mlindauer** [comment]
Hi,

Using SMAC on GPUs has the problem that our memory and time limits induced by the package ``pynisher` are not working correctly, leading to different kind of problems. Could you please try to deactivate the pynisher by adding the following line to your `Scenario` :

``` "limit_resources": True,```

See also: https://automl.github.io/SMAC3/master/examples/hyperband_mlp.html?highlight=pynisher

Best,
Marius

**Comment by Ellyuca** [comment]
Hi Marius,

Thank you for your help.
Unfortunately even with  ``` "limit_resources": True ``` I get the same behavior: for CPU remains in execution without any updates on the output; for GPU the same error with  ``` INFO:smac.facade.smac_hpo_facade.SMAC4HPO:Final Incumbent: None ```

**Comment by mlindauer** [comment]
Sorry, my mistake. You should try to set it to `false` and not to `true`-

**Comment by Ellyuca** [comment]
Hi Marius. You are a genius!

With ```"limit_resources": False```  it works! I can successfully call predict() of a Keras model.

THANKS A LOT!
Stay safe and healthy.
Best,
Alina
