### ISSUE TITLE
[question] Using instance features causes a large drop of time spent on the target algorithm

### ISSUE THREAD

**Issue by brenting** [automl/SMAC3#721]
#### Description
I am using pSMAC to automatically configure a target algorithm with 13 parameters (3 integer, 2 categorical, 8 real) based on quality. I use the SMACCLI interface for this and the older SMAC facade (version 0.10.0). I run pSMAC on a computing cluster in 300 parallel jobs each assigned a wallclock budget of 4 hours, 2 processing cores, and 12Gb of RAM, for a total budget of 1200 hours.

The target algorithm is configured on a training set of instances of size 1120 and each instance takes somewhere between 0-60 seconds. Since my instance set is heterogeneous, I provided SMAC with 14 pre-calculated features per instance. To study the efficacy of these features, I have run the configuration procedure 4 times with instance features and 4 times without instance features. The only modification I made here is removing the instance feature file path from the "scenario.txt" file.

I noticed that without instance features ~85% of the time budget is spent on the target algorithm. However, after providing the instance features to SMAC, this percentage dropped to ~50%. I find it difficult to explain this extreme drop in target algorithm time as there are only 14 instance features that should only increase the internal model size. It now causes SMAC to use an addition 420 hours of the total wallclock budget (or 1.4 hours per parallel job).

An analysis of the target algorithm calls showed that the total amount of target algorithm calls dropped (~100000 to ~70000) by a number that is proportional to the drop in percentage and there is no significant difference in the average time spent on every instance. My conclusion here is that there is no difference in the behaviour of the target algorithm.

Is there an explanation for this behaviour?

#### Steps/Code to Reproduce
If there isn't a logical explanation for this behaviour, I will see if I can set up a smaller-scale experiment that replicates this issue.

#### Expected Results
Providing 14 instance features to the SMAC procedure should only minorly increase the amount of time spent on the internals of SMAC.

#### Actual Results
The SMAC procedure uses 35% more of the wallclock time-budget while using 14 instance features instead of no instance features.

#### Versions

0.10.0

**Comment by mlindauer** [comment]
Maybe let's move the discussion from the email thread to the issue tracker s.t. everyone can read that up also later again.

The code for marginalizing over instance features is not very efficient.
https://github.com/automl/SMAC3/blob/master/smac/epm/rf_with_instances.py#L255
If there are no instance features, we can do everything in C++.
Most likely moving the marginalization into the C++ code of the `pyrfr` package would lead to a substantial speedup for getting predictions.

Two more remarks:
* I would strongly recommend to move to the recent SMAC version since we fixed a lot stuff and also added a much nicer parallelization scheme under the hood (see e.g., https://github.com/automl/SMAC3/blob/master/examples/parallel_sh_mlp.py)
* If your instance set is heterogeneous, I would anyway not recommend to use SMAC in the first place but a PIAC approach.

Best,
Marius

**Comment by brenting** [comment]
Hi Marius,

Thanks for the info.
Since the original post, I did update SMAC to the newest version, but the same problem occurred. However, I use the manual parallelization method through the SMACCLI on a Slurm cluster, and not the build-in parallelization scheme.

Concerning the PIAC approach, I think the instance set is sufficiently homogeneous for SMAC to make sense. I find it a bit difficult to draw the line between heterogeneous and homogeneous in this case.
Furthermore, my goal is to obtain configurations for an agent/algorithm such that its performance generalizes well to a never-before-seen instance set and apply portfolio selection on this set. Given this use case, I think using a PIAC approach would make less sense, but do correct me if I am wrong.

Some other observations:
- The amount of time spent on local search is largely influenced by how many of the parallel SMAC sessions start simultaneously. The fewer sessions that start simultaneously, the more time is spent in the internals of SMAC. The amount of time spent on the target algorithm can drop to 20% in this case.
- The local search procedure won't be cut off if SMAC is overtime or if the division of time spent on SMAC vs on the target algorithm is off balance. In extreme cases, I have seen SMAC exceeding the wallclock budget by more than 5 hours, on a budget of 4 hours.


Best regards,
Bram

**Comment by mlindauer** [comment]
Hi, 

We internally discussed this a bit. As mentioned before, we strongly suspect that the marginalization across the instances is too slow in Python. In our next hackathon on SMAC, we will try to move this code into our RF-package in C++. Hopefully, this will solve this partially.

> The amount of time spent on the target algorithm can drop to 20% in this case.

I would still expect that roughly 50% of the time is spent on the target algorithm runs. Could you please provide a mini-example s.t. we can reproduce this error on our machines?

> The local search procedure won't be cut off if SMAC is overtime or if the division of time spent on SMAC vs on the target algorithm is off balance.

In fact, SMAC only checks the overall configuration budget from time to time. There is no interrupting timer in the background. So, if the local search is really a big bottleneck for hours, SMAC will indeed use too much time. However it will not add any new runs to the trajectory file anymore. In fact, the trajectory file should always be up to date; so the job scheduler on your HPC cluster could simply kill the SMAC process if you are only interested in the trajectory file.

Best,
Marius

**Comment by brenting** [comment]
Hi Marius, 

Good to hear that you are working on speed improvements.

> I would still expect that roughly 50% of the time is spent on the target algorithm runs. Could you please provide a mini-example s.t. we can reproduce this error on our machines?

I could try to create an example, though I would expect that it would not be "mini". Besides, I think this could also be explained intuitively.
Suppose I would start two four-hour parallel SMAC processes on a cluster of which one is delayed as there are no resources available. The first process would roughly divide its time 50-50 on SMAC and the target algorithm. If the first SMAC process produces a large run history before the second SMAC process start, then the second process might immediately hang in the local search procedure. Because of this, the full 4 hours will be spent on SMAC and little on the target algorithm, and the total division of budget will be 75-25 for SMAC v.s. target algorithm.


Bram

**Comment by mlindauer** [comment]
I see. Our assumption is that SMAC has at least time for several iterations (acq. func optimization & target algorithm runs) s.t. should corner cases do not apply. So, hopefully with fixing the RF speed, this problem will be also resolved.
