### ISSUE TITLE
lazy_import uses GPLv3

### ISSUE THREAD

**Issue by Ennosigaeon** [automl/SMAC3#725]
`lazy_import` is using a GPLv3 license while SMAC itself uses a BSD-3 license. As far as I understand, it is not possible to use a GPL based dependency in a BSD-3 license. I am by no means an expert with licensing and just want to point out this possible license violation. Maybe, you can have a look at this...

**Comment by mlindauer** [comment]
Thanks for notifying us. That's seems like to be a real issue. Unfortunately, I don't know whether there is an alternative to lazy_import. Do you know any?

**Comment by Ennosigaeon** [comment]
I don't have a good alternative. I shortly checked the source code and if I understand it corretly, `lazy_import` is only used for the extra requirements so that components using those optional requirements can still be loaded without an `ImportError`. Maybe it is feasible to just provoke the `ImportError` and handle it gracefully, disabling the according components. I am not sure which components would be affected. I assume `LHDesign` and all GaussianProcess-based stuff.

**Comment by tmielika** [comment]
:+1: This has implications of using also the downstream projects like auto-sklearn.

**Comment by mfeurer** [comment]
Dropped as of release 0.14.0. Thank you for notifying us!
