### ISSUE TITLE
scipy 1.7.0 ModuleNotFoundError 'scipy.optimize._shgo_lib.sobol_seq'

### ISSUE THREAD

**Issue by lgoldbach** [automl/SMAC3#729]
Using scipy 1.7.0 I get:

"ModuleNotFoundError: No module named 'scipy.optimize._shgo_lib.sobol_seq'"

when importing HPO facades.

Reverting to scipy 1.6.3 obviously fixes that, I just wanted to let you know in case you didn't already.

**Comment by mfeurer** [comment]
Fixed via #731
