### ISSUE TITLE
Intensification may target the same configuration forever due to adaptive capping

### ISSUE THREAD

**Issue by filipbartek** [automl/SMAC3#748]
#### Description

If a challenger run is skipped due to adaptive capping (adaptive cutoff drops below 0), the same challenger may be targeted in the next iteration of SMBO and be skipped for the same reason. This continues ad infinitum.

The configuration space includes a real-valued parameter, so a fresh configuration could be generated.
The target algorithm is considered deterministic.

#### Steps/Code to Reproduce

[infinite-loop.zip](https://github.com/automl/SMAC3/files/6925988/infinite-loop.zip)

- `out.log`: Beginning of the output of an infinite SMAC optimization. If I let it run longer, the last paragraph repeats forever.
- `run.sh`: Run this to repeat the SMAC optimization. Note that the target algorithm replays a run history, so it depends tightly on the SMAC version, seed, etc.

To reach the looping state in a debugger, set a breakpoint at `smac/intensification/intensification.py:813`.

#### Expected Results

A new challenger is evaluated eventually.

#### Actual Results

One challenger is evaluated repeatedly ad infinitum. See `out.log` in the attached archive.

#### Versions

SMAC: 0.14.0 3df3a749f3050d971af4110d051dae0cd795d615
Python: 3.8.10
OS: Ubuntu 20.04.2

**Comment by dengdifan** [comment]
Closed as this is fixed by https://github.com/automl/SMAC3/pull/749
