### ISSUE TITLE
Bug importing SMAC library to google colab

### ISSUE THREAD

**Issue by alissonycc** [automl/SMAC3#763]
Hello!

I was running some code using SMAC in Google Colab, then the following error appears:

`IncorrectPackageVersionError: 'scipy 1.4.1' version mismatch (>=1.7.0)`

It appears when I try to import SMAC library. I've been using SMAC for the last few months and it is the first time I get this error.

This only appeared after SMAC version changed from 0.13.1 to 0.14.0. It also appears in the current version (1.0.1).
I tried downgrading scipy to the version mentioned in the error, but I was not able to make it work (although it was some days ago). 
I was able to get it working by installing version 0.13.1 and downgrading scipy to version 1.6.

Hope you can solve the problem and I am sorry if I made any mistakes, first time contributing to the project.

**Comment by dengdifan** [comment]
Hi,
can you upgrade scipy together with SMAC to the latest version? 
THe new smac version(0.14.0, 1.0.1) requires the latest version of scipy (>=1.7.0)

**Comment by alissonycc** [comment]
Hello,

it works just after installing smac and restarting the runtime.
It seems this issue may be related to Google Colab, not to SMAC.

Thanks.
