### ISSUE TITLE
`question` Read a set of initial configurations

### ISSUE THREAD

**Issue by nicolasemilio** [automl/SMAC3#766]
`question`

#### Description

Hello!

I'm Nicolás Rojas-Morales and I'm working on the design of an initialization 
strategy for parameter tuners.
I'm studying the effect of injecting a set of particular initial configurations 
to different tuners (e.g. irace, Evoca, SMAC).
I'm trying to see how this can work in SMAC (in its different versions),
but I haven't found how to do it. 
Is there any way to do it? Like a command in the scenario file?
If it's not, can you help me with some guidelines to implement this?

Thank you very much for your time!

Nicolás.

**Comment by mfeurer** [comment]
Hey, you can check how we implemented this in Auto-sklearn: https://github.com/automl/auto-sklearn/blob/4597152e3a60cd6f6e32719a3bef26e13951b102/autosklearn/smbo.py#L207

You can also have a look at how we use the initial design classes in the different SMAC facades: https://github.com/automl/SMAC3/tree/master/smac/facade

**Comment by nicolasemilio** [comment]
Thank you very much @mfeurer!
I injected a pair of configurations in the initial_configurations set (considering also the default one)
and this is the trace:

[Configuration:
  cr, Value: 0.32
  mr, Value: 0.01
  ps, Value: '48'
, Configuration:
  cr, Value: 0.13
  mr, Value: 0.01
  ps, Value: '48'
, Configuration:
  cr, Value: 0.95
  mr, Value: 0.3
  ps, Value: '6'
INFO:   Running initial design for 3 configurations
INFO:   Running initial design
INFO:   First run, no incumbent provided; challenger is assumed to be the incumbent
INFO:   First run, no incumbent provided; challenger is assumed to be the incumbent
INFO:   Updated estimated cost of incumbent on 1 runs: 432.0000
INFO:   Updated estimated cost of incumbent on 2 runs: 50232.0000
INFO:   Challenger (50208.0000) is better than incumbent (50232.0000) on 2 runs.
INFO:   Changes in incumbent:
INFO:     cr : 0.32 -> 0.13
INFO:   Updated estimated cost of incumbent on 3 runs: 33520.0000
INFO:   Challenger (140.0000) is better than incumbent (33520.0000) on 3 runs.
INFO:   Changes in incumbent:
INFO:     cr : 0.13 -> 0.95
INFO:     mr : 0.01 -> 0.3
INFO:     ps : '48' -> '6'


When an initial design is provided (with a set of K configurations),
these configurations will be used and evaluated iteratively by SMAC?
(unless the resource budget is finished?).

Thank you for your time!!

**Comment by mfeurer** [comment]
Yes, exactly. If you provide a list of configurations, these configurations are evaluated one after the other. Alternatively, you can also provide other classes for initial design, you can see the relevant code [here](https://github.com/automl/SMAC3/blob/master/smac/facade/smac_ac_facade.py#L485) and [here](https://github.com/automl/SMAC3/tree/master/smac/initial_design).
