### ISSUE TITLE
`bug` Forbidden Configuration

### ISSUE THREAD

**Issue by vmanriq** [automl/SMAC3#770]
#### Description

I'm trying to give a set of forbidden configuration but smac throw me an error 
`ValueError: Forbidden clause must be instantiated with a legal hyperparameter value for 'param1, Type: UniformInteger, Range: [1, 50], Default: 3', but got '6'
`
#### Steps/Code to Reproduce

Generate a .pcs with the folowing format

```
param1 integer [1,50] [3] 
 
 # Forbiddens:
{param1=6, param1=5, param1=3}
```

#### Expected Results

Value 6, 5, 3 forbidden for param1 

#### Actual Results

`ValueError: Forbidden clause must be instantiated with a legal hyperparameter value for 'param1, Type: UniformInteger, Range: [1, 50], Default: 3', but got '6'
`
#### Versions

1.0.1

**Comment by dengdifan** [comment]
Hi,
thanks for reporting, this is a bug related to ConfigSpace, I create an issue under https://github.com/automl/ConfigSpace/issues/193

Before that, you could directly define your configuration with a python scrip or a json file.

Since this is an issue related to ConfigSpace, I will close this issue here. Feel free to reopen it when you have further question

**Comment by mlindauer** [comment]
Actually, I don't think it is a real bug. 
You said that the default setting of param1 should 3. But at the same time, you say that it is forbidden to set param1 to 3.

There might be actually a bug in the sense, it makes no sense to list the same parameter multiple times in the same forbidden clause. Please note that you have to read it like: It is forbidden to set "param1=6 AND param1=5 AND param1=3". Of course, this should never be true. You want to use:
```
param1 integer [1,50] [50] 
{param1=6}
{param1=5}
...
```

**Comment by vmanriq** [comment]
@mlindauer sorry it was a typo, if i use this .pcs also throwme an error 
`param1 integer [1,50] [3] 
 
{param1=6}
{param1=5}`

ValueError: Forbidden clause must be instantiated with a legal hyperparameter value for 'param1, Type: UniformInteger, Range: [1, 50], Default: 3', but got '6'

**Comment by mlindauer** [comment]
okay, than it really is a bug in the configspace and you should follow up the issue created by Difan.

**Comment by vmanriq** [comment]
I could fix it  the problem was beacuse the forbbiden value was not parsed when the FordibenClause was crated. You need to parsed in the pcs_new.py file of the library  in the line 422. This work for me 
![image](https://user-images.githubusercontent.com/20822528/132951482-e3b1b1d9-0028-4086-97ab-54c93f3b7e41.png)

**Comment by dengdifan** [comment]
> I could fix it the problem was because the forbbiden value was not parsed when the FordibenClause was crated. You need to parsed in the pcs_new.py file of the library in the line 422. This work for me
> ![image](https://user-images.githubusercontent.com/20822528/132951482-e3b1b1d9-0028-4086-97ab-54c93f3b7e41.png)

This might only be a temporal solution. It does not work for other hyperparameters(float, or categorical hyperpameters).
