### ISSUE TITLE
`question` Replicate behavior with seed

### ISSUE THREAD

**Issue by vmanriq** [automl/SMAC3#771]
#### Description

I am trying to replicate the run with the same seed, but SMAC gives me a different result with the same seeds

#### Steps/Code to Reproduce

Run muliples time smac with the command `python3 scripts/smac --scenario scenario.txt --seed 3`
#### Expected Results

The same output in multiples runs

#### Actual Results

Diferent parameters values using the same initial seed
#### Versions

1.0.1

**Comment by dengdifan** [comment]
hi,
how is the function that you want to optimize looks like? If the function cannot output fixed value with fixed seed, then it is very likely that SMAC will generate different incumbent values

**Comment by vmanriq** [comment]
The function i want to optimize can recibe a seed to get same value every time ! The parameters of the alghoritm is the seed, one parameter to optimize and the instance

**Comment by dengdifan** [comment]
Sorry for the late reply, this is truely a bug when working with multi-instances problems, intensifier will not suggest the same configuration when doing intensification, we will figure this out and hopefully fix that in the next release

**Comment by timruhkopf** [comment]
Hi, 
I have been looking into your problem -- in the new release, there won't be a cmd interface anymore. But multiple instances with seeds are deterministic now.

Should you unexpectedly face the issue after the release please let us know.
