### ISSUE TITLE
Instances + Multi-Fidelity

### ISSUE THREAD

**Issue by renesass** [automl/SMAC3#779]
Having this interface
```
model_from_config(cfg, seed, instance, budget)
```
is it possible to use both instance and budget?

For example, if I set instances in the scenario object, then budget is None. If I remove instances from the scenario object, then instance is None. Imagine you want to use subsets as instances and train a MLP with epochs as multi-fidelity. How are you going to do that if either of instance or budget is None?

**Comment by mfeurer** [comment]
I think the definitions here are:
* instances: unsorted
* budget: sorted
So subsets should in my opinion not be represented by instances. If you want to tune both you would have to extend SMAC to have multiple budgets.
