### ISSUE TITLE
Replace Rosenbrock 4d by Rosenbrock 2d

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#79]
Currently, the Rosenbrock 4d function seems to wrong if compared to wikipedia. It should read like:

```
(100 (x1**2 - x2) + (x1 - 1) **2) + (100 (x3**2 - x4) + (x3 - 1)**2)
```

Since the Rosenbrock 2d function seems to be more common, I propose to replace the 4d version with the 2d version which reads like:

```
100. * (x2 - x1 ** 2.) ** 2. + (1 - x1) ** 2.
```

We can then also easily compare our results to the results on wikipedia.

**Comment by mlindauer** [comment]
Originally, we used this function to show different types of parameters (i.e., example from pysmac). To have a very easy example, I removed this. 
I'm fine with switching to the common 2d function, but I believe that SMAC will suck on it anyway.
