### ISSUE TITLE
`question` runhistory.json add description missing in data field

### ISSUE THREAD

**Issue by RvonGlahn** [automl/SMAC3#795]
#### Description

The runhistory.json file has a field called 'data'. It provides information about the runs but there is no description of the data.
Am I missing out on something or doesn´t it exist? 

#### Steps/Code to Reproduce

Just run smac. Should be reproducible for all runs. 
Tested on linux.

#### Expected Results

I would expect a description of data´s values. 
Either in the file or the documentation.

#### Actual Results

data is provided but no info about the values is given.

```
"data": [
    [
      [
        1,
        "7",
        0,
        0.0
      ],
      [
        5.222332266458619,
        0.5964994430541992,
        {
          "__enum__": "StatusType.SUCCESS"
        },
        1636464468.6889162,
        1636464469.3033726,
        {}
      ]
    ],
```

#### Versions

version 0.13.1

**Comment by renesass** [comment]
Indeed it's not really pointed out in the documentation.
This should help you:
`
smac.optimize()
        rh = smac.get_runhistory()
        for (config_id, instance_id, seed, budget), (cost, time, status, starttime, endtime, additional_info) in rh.data.items():
            config = rh.ids_config[config_id]
`

**Comment by RvonGlahn** [comment]
Thank you. That is what I was looking for. :)
