### ISSUE TITLE
Improve save-results-instantly?

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#797]
I'm currently including the functionality to store the runhistory in every iteration to Auto-sklearn. By doing so I was wondering two things:

1. Should we maybe enable this as a default? We write so many things to disk, we might as well dump the runhistory to disk in every iteration. 
2. SMAC emits a warning if I pass it as `"save-results-instantly"` in the scenario dict. There must be an issue in the creation of the aliases for this scenario argument.

**Comment by renesass** [comment]
Yes, that's a known bug. Do you know what's going wrong there?

**Comment by mfeurer** [comment]
No, I don't know.

**Comment by benjamc** [comment]
Is fixed in the multi-objective PR #801 and is set as default.
