### ISSUE TITLE
Round Real Parameters

### ISSUE THREAD

**Issue by vmanriq** [automl/SMAC3#799]
#### Description

There is a way to round real parameters ? I want a parameter like this 
parameter [0.1, 1] [0.1]
but i wanna to go up only  +0.1

**Comment by mfeurer** [comment]
You can use the `q` argument of the [float hyperparameter](https://automl.github.io/ConfigSpace/master/API-Doc.html#ConfigSpace.hyperparameters.UniformFloatHyperparameter).

**Comment by vmanriq** [comment]
But how you use it in the .pcs file ?

**Comment by mfeurer** [comment]
I don't think the pcs file support the `q` argument. @mlindauer ?

**Comment by mlindauer** [comment]
No, it doesn't. Sorry. But you could use an ordinal hyperparameter instead and enumerate all possible values.
