### ISSUE TITLE
Starting points for local search

### ISSUE THREAD

**Issue by KEggensperger** [automl/SMAC3#8]
Originally reported by: **Matthias Feurer (Bitbucket: [mfeurer](https://bitbucket.org/mfeurer), GitHub: [mfeurer](https://github.com/mfeurer))**

---

```
We compute EI for all configuations used in previous target algorithm runs, pick the ten configurations with maximal EI, and initialize a local search at each of them.
```

---
- Bitbucket: https://bitbucket.org/aadfreiburg/smac3/issue/8

**Comment by mfeurer** [comment]
This has been fixed in PR #158. Thanks @jtuyls
