### ISSUE TITLE
algo_runs_timelimit seems no effect so smac3 optimize cost very long time

### ISSUE THREAD

**Issue by bladesaber** [automl/SMAC3#806]
question or bug  

#### Description

Hello, everyone, I set the scenario param like below:

scenario = {
    'abort_on_first_run_crash': False,
     'run_obj': 'quality',
    "runcount-limit": 10,
    "algo_runs_timelimit": 1,
    "wallclock_limit": 10
 }

What I want is to limit the runtime of single trail, but when I use SMAC4AC optimize, the longest time of single trail is longer than 2 minutes. I record the time in the tae_runner function like below:

def trainable(self, config:Configuration):
    X, y = load_boston(return_X_y=True) #dataset from sklearn  
    start_time = time.time()
    model = SVC() # SVC from sklearn package
    model.fit(X, y)
    print('cost: ', time.time()-start_time)

Sometimes, the most time used is less than 1s but sometime smac3 need a long time without any cut. Is it I make a wrong scenario setting ???

Looking forward to your help . Thanks very much ^_^

**Comment by bladesaber** [comment]
Oh I write a wrong class, SVC is wrong, it should be SVR. But it cost a long time is what I meet

**Comment by timruhkopf** [comment]
Hi Bladesaber, 

First of all you can actually use smac options in the `scenario` object. In particular, there is the [limit_resources](https://automl.github.io/SMAC3/master/pages/details/arguments.html?highlight=limit_resource), that you can make use of. It is by default True, indicating that `pynisher `should cut off when the resources limit is exceeded 

 In your specification, `algo_run_timelimit=1` means, that the _tae_ runs at most for one second; so you should change that to e.g. 120. You then can remove `wallclock_limit`. Last but not least to continue your run after cutting off a _tae_, you should set `abort_on_first_run_crash` back to True.
