### ISSUE TITLE
Add mapping from status type to human readable text

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#81]
Currently, the status is an integer between 1 and 5. It cannot be easily displayed to the user without explaining it. It would be helpful to add a mapping back to a human readable string, so that I can do:

```
>>> print(mapping[status])
Memout
```

In the course of implementing this, we could also start using the [Enum](https://docs.python.org/3/library/enum.html#enum.Enum) class which was added in python3.4.

**Comment by mlindauer** [comment]
Yes, very good idea to use Enum

**Comment by shukon** [comment]
Enum affects the JSON-serialization. It is implemented in #151, using a customized JSON-Encoder. I assume, that the JSON-files are only ever read in by smac (more precise: the runhistory)?
mapping is realized by "status.name", which returns the status in human-readable form (-> "SUCCESS").
