### ISSUE TITLE
Condition in PCS file 

### ISSUE THREAD

**Issue by vmanriq** [automl/SMAC3#811]
#### Description
I wanna replicate this configuration made by the IRACE TUNNER, but i need to add some restriccions in the pcs file, its possible to do it ?
 The image show that the q0 parameter is only use when algorithm parameter take the value of "acs"
![image](https://user-images.githubusercontent.com/20822528/149528165-dd59ceea-5376-427f-aa9d-1f02761f9130.png)

**Comment by benjamc** [comment]
Hi vmanriq,
this is an issue regarding ConfigSpace.
You can create conditions like in this [example](https://automl.github.io/SMAC3/master/pages/examples/python/svm_cv.html) and have a look at the [documentation](https://automl.github.io/ConfigSpace/master/API-Doc.html#conditions). In addition, you can have a look at [serialization](https://automl.github.io/ConfigSpace/master/API-Doc.html#serialization) on how to create/read configuration files (from json or pcs-new).
Does that answer your question?
