### ISSUE TITLE
Pynisher isn't required unless limiting resources

### ISSUE THREAD

**Issue by eddiebergman** [automl/SMAC3#822]
There is an issue which essentially prevents SMAC from being used on Windows.

SMAC uses `pynisher` for **optionally** limiting resources, however by importing pynisher in an ungaurded fashion, pynisher will then try to `import resources` which is a unix only library.

The fix for this is to only import `pynisher` when resources have to be limited. This will prevent `pynisher` trying to `import resources` and crashing on windows.

A hack around this was to create a `resource.py` file, i.e. it can be imported but empty, meaning pynisher is happy until it needs to run something. Thankfully due to it being optional, nothing will be run unless limited.

However this hack present problems as libraries like `dask.distributed`, [specifically here](https://github.com/dask/distributed/blob/main/distributed/system.py#L30), will then fail. It finds the empty `resources` and think's it exists but really it's empty.

Another possible hack is just have an empty `pynisher` module.

Either way, these hacks are not ideal.
CC @Steven-Adriaensen

**Comment by mfeurer** [comment]
As an alternative, we could also work on porting the pynisher to Windows. As a lead we could use [this SO thread](https://stackoverflow.com/questions/54949110/limit-python-script-ram-usage-in-windows). However, we'd need to have someone who has the time to maintain the pynisher (i.e. refactor tests etc., test on different systems, etc...)

**Comment by renesass** [comment]
https://github.com/automl/pynisher/tree/api_changes

**Comment by renesass** [comment]
See #854
