### ISSUE TITLE
[Doc] Document the callback signature better in docs

### ISSUE THREAD

**Issue by eddiebergman** [automl/SMAC3#823]
Code:
* https://github.com/automl/SMAC3/blob/master/smac/callbacks.py

Docs:
* https://automl.github.io/SMAC3/master/apidoc/smac.callbacks.html

There is no example and the only way to know about the signature required is to look into the code.

@renesass I assume Sphinx is hiding dunder methods? Is there a way to remove this for a specific module?

Edit: Better solution is probably just add the documentation to the class docstring

**Comment by eddiebergman** [comment]
This needs an example or something more prominent, I don't think there's enough around for a user to figure out how to do early stopping at the moment, as needed in #877

**Comment by renesass** [comment]
Check this out:
https://github.com/automl/SMAC3/blob/development-2.0/smac/callback.py

Integrated the callbacks here:
https://github.com/automl/SMAC3/blob/development-2.0/smac/smbo.py

Docs is also (nearly) ready:
https://automl.github.io/SMAC3/development-2.0/advanced_usage/callbacks.html
