### ISSUE TITLE
What does EPM stand for?

### ISSUE THREAD

**Issue by nabenabe0928** [automl/SMAC3#826]
I could not find the definition of EPM anywhere in the documentation.

**Comment by eddiebergman** [comment]
As far as I'm aware its used to predict model performance.

https://automl.github.io/SMAC3/master/pages/glossary.html

**Comment by nabenabe0928** [comment]
@eddiebergman Thanks eddie!

**Comment by mlindauer** [comment]
EPM stands for empirical performance model.
Please see the following paper by Hutter et al: https://www.sciencedirect.com/science/article/pii/S0004370213001082
