### ISSUE TITLE
Extend PCS format

### ISSUE THREAD

**Issue by mlindauer** [automl/SMAC3#83]
Hi,

we (i.e., Frank, Holger, Kevin, Thomas, Manuel and I) extensively discussed at the Dagstuhl seminar, that
the new pcs format (see AClib 2.0 format spec or the latest SMAC pcs format) will be the standard in AClib in the near future. 
Therefore, I think, it will be also crucial to support it in SMAC3.
Irace does already support it.

Best,
Marius

**Comment by mfeurer** [comment]
@sfalkner @Krxsy you mentioned that you're working on this for the fANOVA, right?

**Comment by Krxsy** [comment]
Yes, I'm working on it. The ordinal parameters are the only ones missing in the new version right now . I'm going to talk to Stefan about that today and send a pull request afterwards.

**Comment by mfeurer** [comment]
I'm not sure if Marius only means the ordinal parameters, but also the new conditions etc.

@mlindauer I thought the ACLIB standard is not yet final/official, that's at least what I understand from your comment on PR #45. Since the SMAC and AClib2.0 specification are different, it would be good to know what exactly you mean.

**Comment by mlindauer** [comment]
Here a summary of the format:

```
parameter_name categorical {value_1, ..., value_N} [default value]
parameter_name ordinal {value_1, ..., value_N} [default value]
parameter_name integer [min_value, max_value] [default value]
parameter_name integer [min_value, max_value] [default value] log
parameter_name real [min_value, max_value] [default value]
parameter_name real [min_value, max_value] [default value] log

Conditionals:
  child_name | condition [&&,||] condition ...

Condition Operators: 
  parent_x [<, >] parent_x_value (if parameter type is ordinal, integer or real)
  parent_x [==,!=] parent_x_value (if parameter type is categorical, ordinal or integer)
  parent_x in {parent_x_value1, parent_x_value2,...}

Forbiddens:
  {parameter_name_1=value_1, ..., parameter_name_N=value_N}
```

**Comment by mfeurer** [comment]
Some more questions?

* Are `child_name` in conditionals still allowed to appear in multiple lines and have to be merged?
* How does the file itself look like? Are conditionals preceded by the term 'Conditionals' (and forbiddens) as well.
* Are there forbidden characters as in the SMAC2 pcs files?

**Comment by mlindauer** [comment]
> Are child_name in conditionals still allowed to appear in multiple lines and have to be merged?

No

> Are conditionals preceded by the term 'Conditionals' (and forbiddens) as well.

No key words such as Conditionals or Forbiddens, but the file should be in the following order: 1. parameters, 2. conditionals, 3. forbiddens

> Are there forbidden characters as in the SMAC2 pcs files?

I don't know.

**Comment by mfeurer** [comment]
@mlindauer I think you can try again with the latest commits to the master branch of the ConfigSpace repository.

**Comment by mfeurer** [comment]
Just merged #132, this should by done now.

**Comment by HYDesmondLiu** [comment]
Hi experts,
    I tried to put " x1 integer [0, 10] [7]" in my PCS file, however error is reported. How do I limit the solution of optimization to be integer?

**Comment by mlindauer** [comment]
Hi,

First of all, please don't re-open old issues where you were not involved in. Furthermore, closed issues are not shown in the issue overview and thus, we will loose track for these.
Furthermore, your problems does not provide sufficient information. Which error was thrown? Which version have you used? Can you please provide a mini-example to reproduce the error?

So, please open a new issue ticket and provide all required details.

Best,
Marius
