### ISSUE TITLE
Advertise entry points

### ISSUE THREAD

**Issue by BastianZim** [automl/SMAC3#839]
Currently, the CLI is described as an entry point in its file: https://github.com/automl/SMAC3/blob/29355618b35dcf4b3ce3e773d633109f036dba17/smac/smac_cli.py#L236

It would be great if that could properly be advertised in the setup.py like an entry point which makes building the package easier.

Ref:

* https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point
* https://setuptools.pypa.io/en/latest/userguide/entry_point.html#console-scripts
* https://stackoverflow.com/questions/18787036/difference-between-entry-points-console-scripts-and-scripts-in-setup-py

**Comment by renesass** [comment]
Thanks for pointing this out. It got lost due the tool updates. Will be integrated within the next version again. :)

**Comment by renesass** [comment]
Can you check if #840 satisfy your needs? :)

**Comment by BastianZim** [comment]
That‘s perfect, thank you! :)
