### ISSUE TITLE
[Q] different incumbent values

### ISSUE THREAD

**Issue by rlaanen** [automl/SMAC3#844]
#### Description

Hi,

I am currently using the SMAC3 tool within my ML pipeline. Within this pipeline, I would like to optimize several parameters in the preprocessing phase as well as the parameters of a classification model. If I set a seed for the classification model (e.g. Random Forest) and a seed in the SMAC object, I obtain similar incumbent values for multiple independent runs. However, if I leave out one or both of the seeds, I get different incumbent values. I am wondering if it is possible to omit one or both random seeds and still get similar results for independent runs? 

Thank you for your consideration. 

#### Steps/Code to Reproduce
def uwb_pipeline(cfg)
      ...
      model = RandomForestClassifier(....random_state = 42)
      ...

scenario = Scenario({
        "run_obj": "quality",  
        "runcount-limit": 50, 
        "cs": cs,
        "abort_on_first_run_crash": True,
        "deterministic" : True,
    })

    smac = SMAC4AC(scenario=scenario, tae_runner=uwb_pipeline, rng = np.random.RandomState(42))

**Comment by renesass** [comment]
Hey,

I actually don't see your problem here. If you use a different seed on `SMAC4AC` then also different configurations are sampled, resulting (depending how big/small your configspace is) in a different incumbent.

Please note that the seed is passed to the `tae_runner`.
If you have more questions I'm happy to answer them :)

**Comment by rlaanen** [comment]
Thank you for your reply.

If I understand it correctly, passing the same seed on SMAC4AC should result in similar incumbents? For instance, if I utilise the same seed on SMAC4AC and set the seed in the Random Forest model to None, the optimizer returns different incumbents. Is this the expected behaviour?

**Comment by renesass** [comment]
Depends. If your TAE is deterministic and you pass and utilize the seed (to your random forest) then yes. Otherwise not.
