### ISSUE TITLE
SMAC crashes when trying to abort when the first run crashes

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#85]
In `default_configuration_design`, if the status of the first run is CRASHED or ABORT, SMAC tries to exit, but crashs itself in the following code:

```
if status in [StatusType.CRASHED or StatusType.ABORT]:
    self.logger.critical("First run crashed -- Abort")
    sys.exit(1)
```

Reasons are a missing import of `sys` and a missing logger.

**Comment by mlindauer** [comment]
already fixed
