### ISSUE TITLE
Dask `distributed` dropped support for Python 3.7

### ISSUE THREAD

**Issue by eddiebergman** [automl/SMAC3#854]
Maybe it's time we do too?
* https://github.com/dask/distributed/blob/b59a322756a125540c912522f6769eb3cb18b807/setup.py#L35
---
Brings in nice typing things, walrus operators `:=`, `f"{value=}"` debug strings if we do :)

**Comment by renesass** [comment]
Would be nice.

**Comment by alexandertornede** [comment]
Since we do not have support for 3.7 in SMAC 2.0, this issue will be resolved with it.
