### ISSUE TITLE
Github Pages Documentation link is broken

### ISSUE THREAD

**Issue by fjlacroix-outpoint** [automl/SMAC3#878]
#### Description
Hello SMAC contributors. The documentation seems to be currently broken. The page lands on a 404.

#### Steps/Code to Reproduce
When trying to reach the following link https://automl.github.io/SMAC3/master/ I am met with a 404 from Github Pages.

#### Expected Results
Some documentation.

#### Actual Results
![image](https://user-images.githubusercontent.com/90932978/184268577-a992ed0b-1463-43fe-83a8-67ce4cc8e992.png)

#### Versions
Latest

**Comment by renesass** [comment]
Hey,

that's correct as we changed the "master" branch to the "main" branch.
You find the docs here: https://automl.github.io/SMAC3/main/

**Comment by ARoefer** [comment]
Why have you not committed the updated link? Sorry to sound sour about this, but you could even update the readme from your browser, there's no need for this.

**Comment by eddiebergman** [comment]
Hi @ARoefer,

Even updating the readme from our browser was not enough as redirects have to happen to make the link `https://automl.github.io/SMAC3` work. It was a little more involved.

We're all busy and distractions happen, but sorry to hear this impacted you as it seems it has, really a friendly "bump" would have been enough.

Anywho, It's fixed, going to close the issue.

Best,
Eddie

**Comment by ARoefer** [comment]
Hi @eddiebergman,

I was not aware that it was this involved. I guess I was feeling impatient and it seemed needless to have the solution here but not having it applied.
I'm sorry, that was unnecessarily rude of me. It's great to see that this project is as actively maintained.
I'm looking forward to using it.

Best,
Adrian
