### ISSUE TITLE
List of structures that SMAC3 supports to model surrogate and acquisition functions

### ISSUE THREAD

**Issue by akmandor** [automl/SMAC3#879]
Does SMAC3 currently support structures other than GP to model the surrogate function?

- For example, after reading [this paper](https://link.springer.com/chapter/10.1007/978-3-642-25566-3_40), I thought [SMAC4BB](https://github.com/automl/SMAC3/blob/main/smac/facade/smac_bb_facade.py), which is used in the [Minimal Example](https://github.com/automl/SMAC3#minimal-example), models the surrogate function by random-forest structure. However, while reading through the [code](https://github.com/automl/SMAC3/blob/main/smac/facade/smac_bb_facade.py), I learned that it uses GP instead of random-forest.
- Also I found facades other than SMAC4BB: [HB4AC](https://github.com/automl/SMAC3/blob/main/smac/facade/hyperband_facade.py), [PSMAC](https://github.com/automl/SMAC3/blob/main/smac/facade/psmac_facade.py), [ROAR](https://github.com/automl/SMAC3/blob/main/smac/facade/roar_facade.py), [SMAC4AC](https://github.com/automl/SMAC3/blob/main/smac/facade/smac_ac_facade.py), [SMAC4BOING](https://github.com/automl/SMAC3/blob/main/smac/facade/smac_boing_facade.py), [SMAC4HPO](https://github.com/automl/SMAC3/blob/main/smac/facade/smac_hpo_facade.py), [SMAC4MF](https://github.com/automl/SMAC3/blob/main/smac/facade/smac_mf_facade.py). However, their differences in terms of surrogate function model is not clear to me. Saying that, does the SMAC4HPO use random-forest to represent surrogate function?

By the way, it would be great if you could explicitly include in README which model types does SMAC3 support to define surrogate and acquisition functions.

**Comment by renesass** [comment]
Please have a look here:
https://automl.github.io/SMAC3/main/details/facades.html

But we will consider that in the next release. Thank you!

**Comment by akmandor** [comment]
Thank you so much pointing me that documentation page. I actually missed that!
