### ISSUE TITLE
SMAC does not stop after it hit it's timelimit

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#88]
Currently, there is a timelimit for both SMAC and the target algorithm run. The target algorithm runner checks the time limit before it starts the target algorithm run, but does not reduce it if it would run over the overall time limit:

```
if self.stats.is_budget_exhausted():
            self.logger.debug(
                "Skip target algorithm run due to exhausted configuration budget")
return StatusType.ABORT, np.nan, 0, {"misc": "exhausted bugdet -- ABORT"}
```

There should be at least an option to make SMAC reduce the time given to the target algorithm. This issue was actually raised as [#76](https://github.com/automl/auto-sklearn/issues/76).

**Comment by mlindauer** [comment]
right now, we can use at most "running time cutoff" (-epsilon) more time than specified in the scenario. Is this a real issue?

**Comment by mfeurer** [comment]
If both limits are equal and the user uses pSMAC, apparently yes.

**Comment by mfeurer** [comment]
I just fixed this downstream in auto-sklearn.
