### ISSUE TITLE
Dead link on github.io-page

### ISSUE THREAD

**Issue by mb706** [automl/SMAC3#882]
The github-link at the top right of https://automl.github.io/SMAC3/main/ leads to `https://github.com/https://github.com/automl/SMAC3`, which has `https://github.com/` in it one too many times.

![image](https://user-images.githubusercontent.com/15801081/192153940-c4cfa4ce-bf76-490d-af90-001f0c1557f2.png)

**Comment by renesass** [comment]
Thank you very much for pointing this out. I'm going to change it in our big release 2.0.

**Comment by renesass** [comment]
Closed by #875
