### ISSUE TITLE
Forbidden Clauses & Acquisition Functions

### ISSUE THREAD

**Issue by HadiKutabi** [automl/SMAC3#905]
I have a question regarding strict config spaces with forbidden clauses and the acquisition functions:

As I understand, the acquisition function decides on the next points to evaluate. However, it is not clear to me how random forests or gaussian processes as surrogates can handle a strict config spaces with forbidden neighborhoods, such that the acquisition function doesn't query points from forbidden neighborhoods. 

Is their a mechanism that regulates this? or do  underlying models just have to learn (by entering forbidden neighborhoods and being punished) where the invalid points are? 

Thank you!

**Comment by mlindauer** [comment]
Hi,

the logic for that is hidden in the `configspace` package. The configspace is responsible to sampling valid configurations or providing valid neighbors of configurations.

The surrogate model and the acquisition function will never see forbidden configurations.

Best,
Marius

**Comment by HadiKutabi** [comment]
Thank you very much! This is very helpful to know.
