### ISSUE TITLE
Run profiler to see if there are any bottlenecks for multiprocessing

### ISSUE THREAD

**Issue by alexandertornede** [automl/SMAC3#913]
Run the profiler and analyze whether the multiprocessing part can be improved.

**Comment by benjamc** [comment]
Profiler runs look fine

Multi-processing SVM Example
![multiprocessing_svm_example (1)](https://user-images.githubusercontent.com/75323339/219325339-bd57c7a8-a65c-4280-9664-132bd524bef8.png)

Multi-processing Multi-Fidelity Example
![multiprocessing_multifidelity_nn_example (1)](https://user-images.githubusercontent.com/75323339/219325355-a5f6d9af-e7ee-4b09-b46e-555162dcdd6b.png)
