### ISSUE TITLE
Update Copyright issue in all source files?

### ISSUE THREAD

**Issue by alexandertornede** [automl/SMAC3#914]
Do we need to update the copyright issues in all source files?

**Comment by mlindauer** [comment]
No, I would recommend updating these the moment you update one of the files anyway.

**Comment by helegraf** [comment]
I have done a superficial search, and this indeed seems to be the accepted way:

- https://opensource.stackexchange.com/questions/6389/how-do-the-years-specified-in-a-copyright-statement-work
- https://stackoverflow.com/questions/9039698/which-years-to-write-into-copyright-header

So the current year should be added to the copyright notice in addition to the previous years once a file is updated (gaps possible). Can we add this to a checklist somewhere?

**Comment by benjamc** [comment]
Solution:
- add instructions in "contributing" to add the current year for the file that is modified (new functionality not formatting)
- leave the rest as is

**Comment by helegraf** [comment]
Added to CONTRIBUTING.md
