### ISSUE TITLE
Incumbent gets reset to default config and trajectory reports `"origin": null`

### ISSUE THREAD

**Issue by benediktsatalia** [automl/SMAC3#917]
#### Description
I am trying to tune two hyper parameters of a randomised optimisation algorithm based on multiple instances. I am calling smac via python using `smac.facade.smac_ac_facade`. The problem is that in some (not all) of my tuning runs I see in the trajectory that it resets the incumbent to the default values, even though this is definitely worse than some parameters found before. In one case it terminated even with the default values as "optimal parameters" although it definitely found better parameters during the run.

#### Steps/Code to Reproduce
Since I cannot share the code/instances this is hard to reproduce, I can share however the output of my runs, see actual results section.

As for the input:

This is the configspace.json log file:

```
{
  "name": "destroyRatioParameterSpace",
  "hyperparameters": [
    {
      "name": "lower_bound",
      "type": "uniform_float",
      "log": false,
      "lower": 0.0,
      "upper": 1.0,
      "default": 0.1
    },
    {
      "name": "upper_bound",
      "type": "uniform_float",
      "log": false,
      "lower": 0.0,
      "upper": 1.0,
      "default": 0.15
    }
  ],
  "conditions": [],
  "forbiddens": [
    {
      "left": "upper_bound",
      "right": "lower_bound",
      "type": "RELATION",
      "lambda": "LESS"
    },
    {
      "left": "upper_bound",
      "right": "lower_bound",
      "type": "RELATION",
      "lambda": "EQUALS"
    }
  ],
  "python_module_version": "0.6.1",
  "json_format_version": 0.4
}
```

This is the scenario.txt log file:

```
execdir = .
deterministic = False
run_obj = quality
multi_objectives = cost
overall_obj = par10
save_results_instantly = True
par_factor = 10
cost_for_crash = 2147483647.0
algo_runs_timelimit = inf
wallclock_limit = 11000.0
always_race_default = False
ta_run_limit = inf
train_inst_fn = smac3-output_2023-02-08_19:42:50_856987/run_2062583628/train_insts.txt
initial_incumbent = DEFAULT
pcs_fn = smac3-output_2023-02-08_19:42:50_856987/run_2062583628/configspace.json
```

#### Expected Results
The expected result is that the incumbent only always is better than the previous configuration and doesn't reset to the default value at some point.

#### Actual Results
This is the trajectory.json log file:

```
{"cpu_time": 0.0, "wallclock_time": 0.00012183189392089844, "evaluations": 0, "cost": 2147483648.0, "incumbent": {"lower_bound": 0.1, "upper_bound": 0.15}, "budget": 0, "origin": "Default"}
{"cpu_time": 10.538874864578247, "wallclock_time": 10.540849208831787, "evaluations": 1, "cost": 419065.7145, "incumbent": {"lower_bound": 0.1, "upper_bound": 0.15}, "budget": 0, "origin": "Default"}
{"cpu_time": 52.01389670372009, "wallclock_time": 52.02358365058899, "evaluations": 4, "cost": 251361.0944, "incumbent": {"lower_bound": 0.3649271547267141, "upper_bound": 0.6661805873493466}, "budget": 0, "origin": "Random Search"}
{"cpu_time": 586.2781836986542, "wallclock_time": 588.1075491905212, "evaluations": 41, "cost": 3689633.0194, "incumbent": {"lower_bound": 0.037206287787872716, "upper_bound": 0.5664917758972194}, "budget": 0, "origin": "Random Search (sorted)"}
{"cpu_time": 2505.922083377838, "wallclock_time": 2513.2841329574585, "evaluations": 175, "cost": 4499689.2765, "incumbent": {"lower_bound": 0.0691762878804697, "upper_bound": 0.7906348942108925}, "budget": 0, "origin": "Random Search"}
{"cpu_time": 8506.42845749855, "wallclock_time": 8532.615861654282, "evaluations": 579, "cost": 4487607.0706, "incumbent": {"lower_bound": 0.08873662418517025, "upper_bound": 0.8842985036701126}, "budget": 0, "origin": "Random Search"}
{"cpu_time": 9392.480768680573, "wallclock_time": 9420.968469381332, "evaluations": 664, "cost": 4487591.7234, "incumbent": {"lower_bound": 0.1, "upper_bound": 0.15}, "budget": 0, "origin": null}
```

We can see in the last line of this json log file the incumbent gets set to the default values and the `"origin": null` additionally indicates to me that this is an unintended bug. In the runhistory I can see that the default settings get run quite often (on various instances with various seeds) over the course of the full tuning, but it is not the last configuration that gets run.

#### Versions

When I run `import smac; print(smac.__version__)` as suggested in the issue template I get: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'smac' has no attribute '__version__'
```
To give some version information I ran `pip show smac`:
```
Name: smac
Version: 1.4.0
Summary: SMAC3, a Python implementation of 'Sequential Model-based Algorithm Configuration'.
Home-page: https://www.automl.org/
Author: Marius Lindauer, Katharina Eggensperger, Matthias Feurer, André Biedenkapp, Difan Deng,
        Carolin Benjamins, Tim Ruhkopf, René Sass and Frank Hutter
Author-email: fh@cs.uni-freiburg.de
License: BSD 3-Clause License
Location: {path_to_venv}/lib/python3.8/site-packages
Requires: pyrfr, distributed, emcee, pynisher, scipy, dask, scikit-learn, regex, ConfigSpace, numpy, psutil, joblib
Required-by:
```

**Comment by dengdifan** [comment]
Hi, thanks for the report. However, now it is hard to locate the problem with the current information. Could you please provide more information, such as `runhistory.json`?
Coming back to your issue. 
`Trajectory.json` only records the losses of one configuration once it becomes incumbent, in which case we might not have evaluated all the instances. Therefore, their actual costs might still be changed and not be recorded by `Trajectory.json`.  That's why sometimes the cost even increases when a new incumbent is found. However, without any further information, we cannot say where the problem comes from.

**Comment by benediktsatalia** [comment]
Hi @dengdifan, thanks for answering on this one. Here is a [zip](https://github.com/automl/SMAC3/files/10802958/runhistory.zip) that contains the runhistory.json  for the above described run.

I see your point that due to evaluations of additional instances incumbents can change and increase cost, but what made me think this is a bug is the `"origin": null` part + the fact that if I run the resulting config on all instances it results in higher cost than other configs that were evaluated.

**Comment by dengdifan** [comment]
so, according to your runhistory:
the configid of your second last incumbent `{"lower_bound": 0.08873662418517025, "upper_bound": 0.8842985036701126}` is `127`, the configid of your default setting is `1`
Then, we can compute their average losses withe the following codes:

```
import json
import numpy as np

with open("runhistory.json","r") as f:
    rh = json.load(f)

data = rh['data']

default_id = 1  # the default configuration
challenger_id = 127 # the challenger configuration (your second last incumbents)

costs_default = []
costs_challenger = []

for i, rh_info in enumerate(data):
    cfg_id = rh_info[0][0]
    cost = rh_info[1][0]
    if cfg_id == default_id:
        costs_default.append(cost)
    elif cfg_id == challenger_id:
        costs_challenger.append(cost)

# we compare the challenger and incumbents under the same number of evaluations as this is how they become the incumbent
costs_default = costs_default[:len(costs_challenger)]

print(f'Default loss {np.mean(costs_default)}')
print(f'Challenger loss {np.mean(costs_challenger)}')
```

The result is:
```
Default loss 4487591.723365315
Challenger loss 4487607.070627396
```
So, basically, the cost (loss) for the challenger is still higher than the default loss, as indicated by your runhistory.
You could also check the other configurations in a similar way. 


> but what made me think this is a bug is the "origin": null part
This is indeed strange, we will check that some days later. 

>  the fact that if I run the resulting config on all instances it results in higher cost than other configs that were evaluated.
Did you also evaluate the other configurations on all instances? It seems like config with id 127 only has 127 evaluations, while the default configuraiotn has 128 evaluations. You need to compute their avergae costs under the same number evaluation runs (as the code I posted above). Thereby, if you allow SMAC to run more time, then maybe it is able to find that config 127 performs better than the config 1.

Hope that answers all your questions.

**Comment by alexandertornede** [comment]
@benediktsatalia We close this issue for now as you did not give a response to  @dengdifan's comment. If this is not the case, feel free to re-open it.
