### ISSUE TITLE
download v1.4 from github without 'requirements.txt'

### ISSUE THREAD

**Issue by Strawberry9583** [automl/SMAC3#923]
#### Description
I want to clone the environment from GitHub according to your installation guideline.

#### Steps/Code to Reproduce
```
git clone https://github.com/automl/SMAC3.git && cd SMAC3
pip install -r requirements.txt
pip install .
```

#### Actual Results
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

#### Versions
v1.4

**Comment by renesass** [comment]
It's enough to call the following only:
```
pip install .
```

or if you want to make changes:
```
pip install -e .[dev]
```

**Comment by sarah-krebs** [comment]
Updated installation guide
