### ISSUE TITLE
ValueError: Instance information in runhistory is not part of the defined instances in scenario.

### ISSUE THREAD

**Issue by davidmurray** [automl/SMAC3#927]
#### Description
Restarting SMAC seems to crash because a str is being compared to an int, which yields False when it should really be True.
The code that crashes is here:
https://github.com/automl/SMAC3/blob/c861ae4b69d08e8a379d944ed079ded70327ef5d/smac/intensifier/abstract_intensifier.py#L154-L157

`self._scenario.instances` contains _int_s while _k.instance_ is a str (as it's loaded from disk, we seem to lose type information). This makes it so that `k.instance not in self._scenario.instances` is False, so a ValueError is raised.

#### Steps/Code to Reproduce
1. Code
```python
scenario = Scenario(cs,
            walltime_limit=168*60*60
            deterministic=False,
            instances=list(range(1, 8)), # 7 zones
            instance_features={val:[val] for val in list(range(1, 8))}, # ---> this yields a list [1, 2, 3, 4, 5, 6, 7]
            n_trials=5000)
```

2. Start running SMAC
3. Interrupt Python
4. Restart SMAC
5. Code crashes because a _str_ is being compared to an _int_ on reloading runhistory.json

#### Expected Results
No crash

#### Actual Results
```python
Traceback (most recent call last):
  File "/home/dmurray/code/osm/algo/genetic_algorithm.py", line 434, in <module>
    incumbent = smac.optimize()
  File "/home/dmurray/SMAC3/smac/facade/abstract_facade.py", line 289, in optimize
    incumbents = self._optimizer.optimize()
  File "/home/dmurray/SMAC3/smac/main/smbo.py", line 279, in optimize
    trial_info = self.ask()
  File "/home/dmurray/SMAC3/smac/main/smbo.py", line 151, in ask
    trial_info = next(self._trial_generator)
  File "/home/dmurray/SMAC3/smac/intensifier/intensifier.py", line 105, in __iter__
    self.__post_init__()
  File "/home/dmurray/SMAC3/smac/intensifier/abstract_intensifier.py", line 162, in __post_init__
    raise ValueError(
ValueError: Instance information in runhistory is not part of the defined instances in scenario.
```

#### Versions
SMAC 2.0.0b1

**Comment by renesass** [comment]
Hi David,

if I remember correctly, this issue has been solved in 2.0.0b2 (#898). Otherwise, I recommend using strings instead of integers. For example:
```
instances = [f"instance-{i}" for i in range(1, 8)]
instance_features = {instance:[instance] for instance in instances}
```

Best,
René

**Comment by davidmurray** [comment]
Hi @renesass

Sorry, I made a mistake in my original message. I was actually running the latest version on the development branch, not 2.0.0b1. This issue happens on the development branch.

**Comment by renesass** [comment]
Please check if you still have the issue. :)

**Comment by davidmurray** [comment]
Yep! That fixed it. Thanks !
