### ISSUE TITLE
[Feature] Enable method to disable custom logging of SMAC.

### ISSUE THREAD

**Issue by eddiebergman** [automl/SMAC3#948]
The parameter [`logging_level`](https://github.com/automl/SMAC3/blob/731854e8effe72d76cb07636458e783143f32dc5/smac/facade/abstract_facade.py#L109) is always used with the function [`setup_logging`](https://github.com/automl/SMAC3/blob/731854e8effe72d76cb07636458e783143f32dc5/smac/facade/abstract_facade.py#L113), no matter what is passed in. This prevents users from just using the logging that they have set up themselves. I'm not sure exactly why this is done but my guess is because the `logger` get's passed around for some multi-processing reasons.

I made a PR in #947

**Comment by renesass** [comment]
Good spot!

**Comment by 2-5** [comment]
I have encountered the same problem, SMAC messing up existing logging, and I don't think this PR fully solves the issue.

There is another call to `setup_logging` right at `smac` module import:

https://github.com/automl/SMAC3/blob/main/smac/__init__.py#L28

**Comment by eddiebergman** [comment]
Thanks for finding this!

**Comment by eddiebergman** [comment]
Handled in #970
