### ISSUE TITLE
[Question] Help using API

### ISSUE THREAD

**Issue by Game4Move78** [automl/SMAC3#949]
#### Description
I tried running the following simple ask-tell loop for benchmarking SMAC3 performance on the multi-fidelity case. Unfortunately I keep running into a StopIteration error on when the [intensifier iterable is used to get the next trial info](https://github.com/automl/SMAC3/blob/731854e8effe72d76cb07636458e783143f32dc5/smac/main/smbo.py#L151). I would greatly appreciate if anyone can help me with proper usage.

#### Steps/Code to Reproduce

[Code snippet](https://gist.github.com/Game4Move78/dc77fb35f80a8ea1195d376b6523fc6e)

It occurs after 259 finished trials and approximately 49k seconds on the HPOBench implementation of the tabular slice localization benchmark.

#### Expected Results
No error

#### Actual Results
StopIteration

#### Versions
```
(Pdb) smac.version
'2.0.0'
```

**Comment by renesass** [comment]
Hi,

thank you for reporting your error. Can you please execute it with `logging_level=0` and paste the log here?

Best,
René

**Comment by Game4Move78** [comment]
Adding a config_selector instance did allow it to complete the allocated budget of 10e6, so thanks! Here are the [debug outputs](https://gist.github.com/Game4Move78/6ff73fcf5ed7b34bab45fd439f390e2d) for the original error, in case you find it useful.

**Comment by renesass** [comment]
Thank you! And I'm happy that I could help you. :)
