### ISSUE TITLE
Do not use the pynisher if no memory limit and cutoff time are given

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#95]
Currently, the pynisher is used regardless of whether the target algorithm has a memory limit and a cutoff time given. In case it doesn't have any limits, it would be nice if we could just bypass the pynisher. Is there any reason not to do so?

**Comment by mlindauer** [comment]
> Is there any reason not to do so?

The code gets more complicated?
Does the pynisher hurt in your use case?

**Comment by mfeurer** [comment]
No, actually, I need to rewrite my code such that it can be used as a target function. I didn't see this in the beginning.
