### ISSUE TITLE
SMAC3 version 1.4 working in windows 10

### ISSUE THREAD

**Issue by carlosricardocm** [automl/SMAC3#952]
#### Description
HI, for all you guys that want to use this library in Windows, I succesfully install it in Windows 10 and 11.

#### Steps/Code to Reproduce

The steps for install it are as follows:

1. Create an environment with 
    conda create -n SMAC python=3.9.7 (but also could work with python 3.10)

2. Install swig version 4.1.1 and add to path globally 
    http://prdownloads.sourceforge.net/swig/swigwin-4.1.1.zip

3. Install m2w64-gcc as compiler
    conda install -c conda-forge m2w64-gcc

4. Install smac ver. 1.4 with pip (version 2.0 won't work)
    pip install smac=1.4

5. Search where pip installed smac ( with $pip list -v you could find where is installed, in my case is in d:\anaconda3\envs\audio\lib\site-packages ) and in the source code
    search for string dates changing colons for hypens (because in windows is imposible create folders o files that contains colons )

#### Expected Results
Libary working in Windows 10

#### Actual Results
I succesfully run examples of optimization using the following libraries:

from ConfigSpace import Configuration, ConfigurationSpace, UniformIntegerHyperparameter, UniformFloatHyperparameter
from smac.scenario.scenario import Scenario
from smac.facade.smac_bb_facade import SMAC4BB as BBFacade
from smac.facade.smac_hpo_facade import SMAC4HPO as HPOFacade
from smac.initial_design.default_configuration_design import DefaultConfiguration

#### Versions
smac 1.4

**Comment by drdaxxy** [comment]
I had no problems installing and using SMAC3 from the development branch (I also installed stable 2.0.2 while troubleshooting something else, but didn't really run it) on Windows 10 natively (i.e. no WSL2) -- with MSVC, not GCC.

That's in a Python 3.10 conda environment (full Anaconda distribution, not miniconda), with `swig` from Anaconda's main channel and VS2019 Build Tools (using the Developer PowerShell profile).

**Comment by benjamc** [comment]
Closed by #1155
