### ISSUE TITLE
Make InstanceSeedPairs named tuple a module member

### ISSUE THREAD

**Issue by mfeurer** [automl/SMAC3#97]
Currently, the named tuple is defined within a method.

**Comment by shukon** [comment]
Is this about the runhistory.py? It seems to be done and merged to master, close?

`21: InstSeedKey = collections.namedtuple(`
`22: 'InstSeedKey', ['instance', 'seed'])`
(https://github.com/automl/SMAC3/blob/master/smac/runhistory/runhistory.py#L21-L22)

**Comment by mfeurer** [comment]
Yes :)
