### ISSUE TITLE
SMAC Data Collection

### ISSUE THREAD

**Issue by benjamc** [automl/SMAC3#996]
create `metadata.json` containing info about how the SMAC run was generated, i.e. should contain

- “project_name”: “...”
- “repository”: “...”
- “commit”: “...”

Could create a user callback with which we can init the information and it is automatically logged to the correct place.
Should accept any other kwargs.

**Comment by eddiebergman** [comment]
I'll add you can find out the command used to actually run the program too which might be useful to log using `sys.argv`.

**Comment by eddiebergman** [comment]
Closed in #999
